lib/helper/WebDriverIO.js

Reference from: http://webdriver.io/guide/getstarted/configuration.html

Fix wrong WebDriverIO option name

---

README.md

helper links were pointing to non-existent pages.

Update WebdriverIO and Filesystem helper links

---

docs/helpers/WebDriverIO.md
lib/helper/WebDriverIO.js
test/unit/helper/WebDriverIO_test.js

@DavertMik: I have added the feature that I proposed in https://github.com/Codeception/CodeceptJS/issues/51

add waitToHide

---

docs/helpers/WebDriverIO.md
lib/helper/WebDriverIO.js
test/unit/helper/WebDriverIO_test.js

@DavertMik 
I came up with a new feature: counting the appearances in the dom of a given element
this is very useful when working with tables or auto generated fields.

I.countAppearances

---

lib/helper/WebDriverIO.js
test/unit/helper/WebDriverIO_test.js

@DavertMik please review, this is the adapted version of `wd.getHTML`
http://webdriver.io/api/property/getHTML.html

grabHTMLFrom

---

docs/webapi/clearElement.mustache
docs/webapi/clearField.mustache
lib/helper/WebDriverIO.js
test/unit/helper/WebDriverIO_test.js

@DavertMik please review this feature!
It is the adaption of [clearElement](http://webdriver.io/api/action/clearElement.html)

I.clearField()

---

docs/helpers/Protractor.md
docs/helpers/SeleniumWebdriver.md
docs/helpers/WebDriverIO.md
docs/webapi/fillField.mustache
docs/webapi/grabAttributeFrom.mustache
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
test/unit/helper/Protractor_test.js
test/unit/helper/webapi.js

@DavertMik I realized that we use grabTextFrom, grabValueFrom, but we always had grabAttribute
So I changed it to grabAttributeFrom to stick to the style of the other functions
I also implemented doubleClick for selenium (please have a look at this, not 100% sure)

Chore/fixes v0.3.0

---

docs/quickstart.md

Problem:
Quickstart page now is in bad condition cause of unresolved merge conflict.
Contribution:
Quickstart **markdown** restored with information from http://codecept.io/quickstart.

Quickstart.md markdown restored

---

quickstart/index.html

Problem:
Quickstart page now is in bad condition cause of unresolved merge conflict.
Contribution:
Quickstart **HTML** page restored with information from http://codecept.io/quickstart.
HTML generated with mkdocs, as in other pages of project.

Quickstart HTML page restored

---

lib/command/generate.js

added parentheses around the regex on line 44, fixes #105

Fixed bug in generate.js

---

lib/codecept.js
lib/command/run.js
lib/interfaces/codeceptjs.js

Reverts Codeception/CodeceptJS#97

Revert "Bug/run test suite"

---

README.md

Use generic wording to avoid future conflicts.

docs(readme): update number of helpers

---

docs/helpers/WebDriverIO.md
lib/helper/WebDriverIO.js
test/unit/helper/WebDriverIO_test.js

_locateClickable, _locateCheckable and _locateFields helpers on WebDriver

---

README.md
docs/helpers.md

Hi guys! This project is awesome <o/
This is a tiny doc update to make explicit how to use CodeceptJS with TypeScript based on #120 and #135.

Typescript support docs

---

.travis.yml
examples/codecept.json
examples/github_test.js
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/helper/clientscripts/nightmare.js
lib/recorder.js
package.json
test/data/app/controllers.php
test/data/app/view/form/doubleclick.php
test/unit/helper/Nightmare_test.js
test/unit/helper/SeleniumWebdriver_test.js
test/unit/helper/WebDriverIO_test.js
test/unit/helper/webapi.js

Initial Nigthmare integration.

[WIP] Nightmare

---

.travis.yml
CHANGELOG.md
gulpfile.js
lib/helper/Protractor.js
test/helper/Nightmare_test.js
test/helper/Protractor_test.js
test/helper/SeleniumWebdriver_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js

Travis updates

---

lib/helper/WebDriverIO.js

Linked to https://github.com/Codeception/CodeceptJS/issues/178

Fix typo in webdriverio config timeout

---

lib/helper/Protractor.js

removes console.log from amOutsideAngularApp

---

package.json

added translations directory to the files property. fixes issue #199

---

lib/helper/Protractor.js

updated Protractor to handle different protractor versions correctly

---

lib/helper/SeleniumWebdriver.js

added support for special keys in pressKey of Protractor

---

lib/command/definitions.js

Container does not have getTranslations() method, just translation().

Fix def command

---

docs/pageobjects.md

As suggested in https://github.com/Codeception/CodeceptJS/blob/master/CHANGELOG.md#022 , otherwise the example code might not work as expected.

Use global actor function in Page Objects docs

---

docs/helpers.md

Added better configuration section description with examples on how to enable helper manually

Update to helpers docs

---

lib/helper/WebDriverIO.js
test/data/app/data.php
test/helper/webapi.js

* Fixed false positive tests for attach files
* Fixed async for attachFile in WebDriverIO 
* Improved php server for upload testing

Fixed file uploads fro WebDriverIO

---

lib/codecept.js
lib/event.js

fix issue https://github.com/Codeception/CodeceptJS/issues/262

do not throw error in dispatcher

---

docs/webapi/moveCursorTo.mustache
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/helper/clientscripts/nightmare.js
test/data/app/view/form/hover.php
test/helper/Nightmare_test.js
test/helper/webapi.js

Added moveCursorTo to Protractor, Nightmare, SeleniumWebdriver

---

lib/helper/Protractor.js
test/helper/Protractor_test.js

Thanks to advice in #278 
Few tests added

[Protractor] simplified behavior of amOutsideAngularApp

---

CHANGELOG.md
docs/webapi/executeAsyncScript.mustache
docs/webapi/executeScript.mustache
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
test/helper/webapi.js

Fixes for executeScript executeAsyncScript in different helpers

---

lib/scenario.js

Fixed exit code for errors in Before hook. 

---

docs/webapi/waitForInvisible.mustache
docs/webapi/waitForNotAttached.mustache
docs/webapi/waitForStalenessOf.mustache
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

Add waitForInvisible and waitForNotAttached in Selenium/Webdriver.io and Protractor helpers.
Not implemented in Nightmare as I'm unfamiliar with the tool.

Add waitForInvisible and waitForNotAttached methods

---

lib/output.js

Change 'pending' to 'skipped'

---

docs/webapi/waitForVisibleThenClick.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
test/data/app/view/dynamic.php
test/helper/webapi.js

This is one of the custom methods we're using in our test suite. We use it so much that I'm betting others would find it useful as well (hence this PR :smiley: )

Add wait for visible then click method to helpers

---

lib/helper/Protractor.js
test/helper/Protractor_test.js

Updated Protractor 4.0.12+ support.

---

test/data/app/view/form/example20.php
test/helper/webapi.js

Demonstration selecting elements with the same name using CSS and XPath locators.
See #322

Elements same name test

---

lib/helper/Nightmare.js

Fix for issue #274. Didn't find a way for maximize to work, but this should help to at least resize windows.

Fix for Issue #274 with I.resizeWindow (nightmare)

---

lib/interfaces/bdd.js

Proposal for flaky mode in Features
I my opinion this should be enough because the problems with flaky states is almost when an emulator or an browser at selenium / cloud based system like browserstack, saucelab, ... is not starting. Then the test should be retried.
It shouldn't be used to mark tests as flaky because i think in this case the test was not correct implemented.
That's why i think in Feature it should be enough but i am open for any other ideas / problems ;)

Added flaky mode for Feature

---

docs/webapi/clearField.mustache
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
test/helper/Nightmare_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js

Added `clearField` to Nightmare and SeleniumWebdriver

Clear field

---

lib/interfaces/bdd.js

We came across this bug also and decided to fix it to get us moving - so I made a pull request for you!
#347

Pass empty opts object to test when skipping

---

examples/github_test.js
lib/actor.js
test/unit/actor_test.js

`say` can be used to print comment to screen
```js
I.say('now I want to edit user');
```
Closes #313

Added I.say method

---

lib/helper/Nightmare.js
test/helper/webapi.js

[Nightmare] clearCookie should clear all cookies

---

lib/listener/helpers.js

Could this be right? (I know, I f*d up the commit message ..) ¯\_(ツ)_/¯

fix for _test() helpersHook not working

---

lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

When restart: false and `keepCookies`: true, cookies will be kept between tests
Closes #374

added keepCookies option to keep cookies between restart

---

lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js

Added waitForTimeout to Protractor

---

.travis.yml
lib/helper/Protractor.js
package.json
test/data/app/db
test/helper/Protractor_test.js

Protractor 4 and Protractor5 support

Protractor5

---

docs/pageobjects.md

To create different kinds of pageobject by running the command "codeceptjs go --kind step" output the following error:
error: unknown option `--kind'
The option "--kind" should be use "--type", eg: "codeceptjs go --type step"

[Command error] error: unknown option `--kind'

---

lib/listener/exit.js

update process exit code so that mocha saves reports before exit

---

docs/reports.md

Fix reporter name

---

docs/basics.md
lib/helper/Nightmare.js
lib/helper/clientscripts/nightmare.js
lib/within.js

Codecept can now work for iFrames.
Changes is implemented with the help of within() and _withinBegin(). The changes are done only for Nightmare wrapper as example for now.

Codecept support for iFrames

---

lib/helper/Nightmare.js

Fix locating nightmare-upload

---

docs/basics.md
docs/helpers/Protractor.md
docs/helpers/SeleniumWebdriver.md
docs/helpers/WebDriverIO.md
lib/codecept.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

Fixed loading hooks synchronously

Plugins fix

---

docs/acceptance.md

remove the the diff format from git merge

finish the git merge

---

docs/acceptance.md

The example contained a wrong xpath expression

Fix xpath expression

---

README.md

Just a note on node.js minimum version, re #505 Minimum version of node required is not documented

Adding minimum node version note

---

docs/hooks.md

Hi there,
While reading through the docs, I've stumbled upon a small typo.
Keep up the good work!

Fixed small typo in example

---

Dockerfile
docker/run.sh

I tried to run as a docker image, but this failed with an error saying "unable to find config file".
This seems to be because "run.sh" executes in "/" (and so does "codecept.js"), but the config file is in "/tests/".  I've made a couple of small changes (to the Dockerfile and docker/run.sh) to cd to the /tests/ directory and also to allow a CODECEPT_ARGS rather than GREP env var (I'm assuming the docker file is based on an earlier codecept.js syntax).
Happy to discuss.

Update to docker files

---

lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

Let's respect promises. Introduced by 21d4996.

Fix webdriver helpers: return merged promise when clearing cookies

---

.travis.yml
docs/helpers/Appium.md
docs/helpers/WebDriverIO.md
lib/helper/Appium.js
test/helper/Appium_test.js

* Added basic Appium reference
* Removed Appium testing from Travis and moved to Semaphore CI
* Renamed `dontSeeDeviceIsLoced` to `seeDeviceIsUnlocked`

Appium Docs

---

docs/helpers/Nightmare.md
docs/helpers/SeleniumWebdriver.md

Nothing too exciting; simply helping out

Update syntax highlighting in helper docs

---

lib/helper/Appium.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

Fix https://github.com/Codeception/CodeceptJS/issues/560

Fix maximize

---

lib/actor.js
lib/command/definitions.js
lib/command/list.js
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/utils.js
package.json

`list` and `def` commands prints optional params

Added default params to all helpers

---

lib/codecept.js
lib/container.js
lib/dataTable.js
lib/helper/Appium.js
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/index.js
lib/interfaces/bdd.js
lib/scenario.js
lib/utils.js
test/data/sandbox/codecept.ddt.json
test/data/sandbox/ddt_test.ddt.js
test/helper/AppiumWeb_test.js
test/runner/interface_test.js

Our goal: https://github.com/Codeception/CodeceptJS/issues/239
TO-DO list:
Status of current realization:
```
Feature('@smoke tests');
Before((I) => {
I.amOnPage("/");
});
let accounts = new dataTable(['login', 'password']); <- new class, that will store dataTable
dataTableb.add(['davert', '123456']); <- adding  records to table
dataTableb.add(['admin', '123456']);
Scenario('Test some crazy', accounts, (I, scenarioContext) => {
I.fillField('Username', scenarioContext.login); <- access to scenarioContext
I.fillField('Password', scenarioContext.password);
I.click('Sign In');
I.see('Welcome '+ scenarioContext.login);
});
output
@smoke tests --
Test some crazy {"login":"davert","password":"123456"}
• I am on page "/"
• I fill field "Username", "davert"
• I fill field "Password", "123456"
• I …
```

Support Data Driven Testing

---

docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/SeleniumWebdriver.md
docs/helpers/WebDriverIO.md
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

Add uniqueScreenshotNames for Protractor, nightmare, SeleniumWebdriverJS
disable screenshot option https://github.com/Codeception/CodeceptJS/issues/536

Add disable screenshot option. Add uniqueScreenshotNames option.

---

lib/helper/WebDriverIO.js
lib/utils.js
test/data/app/view/index.php
test/data/app/view/info.php
test/helper/WebDriverIO_test.js

new Methods:
* grabCssPropertyFrom
* seeTitleEquals
* seeTextEquals
* seeCssPropertiesOnElements
* seeAttributesOnElements
* grabNumberOfVisibleElements
* waitInUrl
* waitUrlEquals
* waitForValue
* waitNumberOfVisibleElements
* switchToNextTab
* switchToPreviousTab
* closeCurrentTab
* openNewTab
* refreshPage
* scrollPageToBottom
* scrollPageToTop
* grabBrowserLogs
add url decoding before assertion

New Webdriverio methods

---

lib/helper/WebDriverIO.js
test/helper/WebDriverIO_test.js

Fixed seeNumberOfVisibleElements

---

CHANGELOG.md
docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/SeleniumWebdriver.md
docs/helpers/WebDriverIO.md
docs/pageobjects.md
docs/reports.md
lib/actor.js
lib/codecept.js
lib/helper/Appium.js
lib/helper/Mochawesome.js
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/listener/steps.js
lib/mocha_factory.js
lib/reporter/cli.js
lib/scenario.js
test/helper/Protractor_test.js
test/helper/SeleniumWebdriver_test.js

Our goals
* https://github.com/Codeception/CodeceptJS/issues/379
* https://github.com/Codeception/CodeceptJS/issues/514
* https://github.com/Codeception/CodeceptJS/issues/629
* Fix Scenario Steps output for failed tests (We printed extra steps, that wasn't executed after fail step)
* Update docs
* fix Unhandled promise rejection (rejection id: 1): Error: Unknown wait type: pageLoad
* support tests with retries in html report (In html report you will see latest retry or passed test)
* be sure that change window size and timeouts completes before test

Multi reports and Mochawesome helper

---

lib/helper/WebDriverIO.js
test/helper/WebDriverIO_test.js

fix https://github.com/Codeception/CodeceptJS/issues/647

[WebdriverIO] fix inner click

---

lib/helper/Nightmare.js
test/helper/Nightmare_test.js

Added refresh function requested in Issue 528
https://github.com/Codeception/CodeceptJS/issues/528

Adding refresh function to Nightmare Helper - Issue 528

---

lib/event.js
lib/listener/steps.js
lib/listener/trace.js
lib/scenario.js
test/data/helper.js
test/data/sandbox/codecept.testhooks.json
test/data/sandbox/testhooks_test.testhooks.js
test/runner/codecept_test.js

* https://github.com/Codeception/CodeceptJS/issues/206 Add generators support in scenario hooks BeforeSuite/Before/AfterSuite/After;
* Add Scenario Steps output for hooks, when they fails

Hooks generators

---

lib/helper/Protractor.js

Fix https://github.com/Codeception/CodeceptJS/issues/458 - amOutsideAngularApp is needed before all lines when test non-Angular app

fix Protractor reinject outside app

---

lib/helper/Mochawesome.js
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/listener/exit.js
lib/utils.js

* Fix https://github.com/Codeception/CodeceptJS/issues/447 - Tests fail silently if they have the same name as other tests. Now we will track test uuid to monitor failed/passed tests
* Now we are using test uuid in screenshot names, when `uniqueScreenshotNames: true`
* Remove obsolete util `HashCode`

Fix unique names issue

---

lib/helper/ApiDataFactory.js

Fixed requireg in ApiDataFactory

---

ISSUE_TEMPLATE.md

Fix issue template

---

lib/helper/Nightmare.js

Should resolve #693.
@DavertMik could you please point me into direction on how to cover it with tests? :)

[Nightmare] fix executeScript return value

---

lib/helper/WebDriverIO.js

Fix variable name in waitUntil

Fix variable name in waitUntil

---

lib/recorder.js

Handle cases when result is not a promise

Ensure a valid promise is always passed

---

lib/helper/WebDriverIO.js

Ignore local storage clean error, if we try to clean localStorage on data urls

Ignore local storage clean error, if we try to clean on data urls

---

lib/helper/WebDriverIO.js
lib/helper/errors/ElementNotFound.js
test/helper/WebDriverIO_test.js
test/unit/helper/element_not_found_test.js

I always use objects in locators.
In many methods I got errors like "[object Object] was not found by.."
I tried to fix it.

Fix "[object Object] was not found by.." error message

---

lib/data/context.js
lib/data/table.js
lib/helper/Mochawesome.js
lib/interfaces/bdd.js
lib/step.js

BeforeSuite addMochawesome Context support
Add `xadd` for datatables to ignore this tests in run
Add `Data(table).only.Scenario` to give ability to launch only `Data` tests

BeforeSuite addMochawesome Context support and DDT improve

---

lib/command/run.js
lib/utils.js

Fix https://github.com/Codeception/CodeceptJS/issues/571 - Unable to pass absolute path for output

Absolute output fix

---

lib/data/context.js
package-lock.json
test/runner/interface_test.js
test/unit/data/table_test.js

Root cause seems to be a "data" property for DataTable row objects needing to be accessed.

Fixed 2 failing tests from master.

---

docker/README.md

[Docker/README] Add info about CODECEPT_ARGS var

---

.hound.yml

HoundCI is a CI to print eslint errors in comments

Added hound config

---

Dockerfile
package.json

Getting closer to Node v8. Closes #795

Updated version in package json and in dockerfile

---

lib/helper/WebDriverIO.js

Issue described: #832 
Original refactoring commit: https://github.com/Codeception/CodeceptJS/commit/24bf12d7bfdbb17cb7958d487fd9327ba3634209

fix #832: bad refactoring WebDriverIO:waitForInvisible

---

.travis.yml
Dockerfile
lib/helper/ApiDataFactory.js
lib/interfaces/bdd.js
package.json
test/data/app/view/spinner.php
test/helper/Nightmare_test.js
test/helper/ProtractorWeb_test.js
test/helper/Protractor_test.js
test/helper/Puppeteer_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js
test/rest/REST_test.js

Also added `tsc` to travis step to ensure it runs !

Fixed bug with bdd scenario where data wasn't valid parameter to addScenario

---

lib/helper/REST.js

REST helper refactor

---

lib/helper/Nightmare.js

Integrate with nightmare-har-plugin

---

lib/helper/Puppeteer.js

[Puppeteer] Fixed issue when generating the list of commands. Fixes #919

---

lib/helper/Nightmare.js
test/helper/Nightmare_test.js

Implemented I.seeNumberOfElements() in Nightmare

Added I.seeNumberOfElements() to Nightmare helper

---

lib/scenario.js

Case when async function used without await and then we have other await function

Fix unhandled rejection

---

docs/acceptance.md
docs/basics.md
docs/nightmare.md
docs/webapi/grabSource.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/WebDriverIO.js

* Fixes following documentation issues: #490, #658, #656, #732

[Documentation] Small doc fixes

---

.travis.yml
lib/interfaces/bdd.js
test/.env
test/acceptance/codecept.WebDriverIO.js
test/acceptance/within_test.js
test/docker-compose.yml
test/helper/ProtractorWeb_test.js
test/helper/Protractor_test.js
test/helper/Puppeteer_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js
test/rest/ApiDataFactory_test.js

* Added headless testing to test (seems more reliable than xvfb)
* Updated selenium/standalonechrome 3.9.1
* [Puppeteer] Added retries to Puppeteer tests
* [Puppeteer] Added some waits in test cases when switching/closing tabs
* Various Travis and Circle CI config changes (setting shm_size and DBUS_SESSION_BUS_ADDRESS)
* Refactored REST Helper tests to use async/await (for better readability)

[Tests] Improving reliability of the CI tests (Travis and Circle CI)

---

lib/helper/Puppeteer.js
lib/helper/WebDriverIO.js
test/data/app/view/form/wait_enabled.php
test/data/app/view/form/wait_num_elements.php
test/data/app/view/form/wait_value.php
test/helper/Puppeteer_test.js
test/helper/WebDriverIO_test.js

* Added waitForEnabled, waitForValue and waitNumberOfVisibleElements
* Added some extra tests to the WebDriverIO helper and change some error messages so they are the same as those generated by the Puppeteer helper (limited to the new Puppeteer functions).
Now I'm pretty sure the Puppeteer Helper is feature parity with the WebDriverIO helper  🎉 🍻

[Puppeteer] Added waitForEnabled, waitForValue and waitNumberOfVisibleElements

---

lib/helper/Puppeteer.js

Added comment about how to access the browser and current page object from custom helper. #963

[Docs|Puppeteer] Added comment about how to access the browser and current page object from custom helper

---

lib/command/run-multiple.js
test/data/sandbox/codecept.multiple.json
test/data/sandbox/tests_test_override.multiple.js
test/docker-compose.yml
test/runner/run_multiple_test.js

[feature] Enable overriding of `config.tests` for `run-multiple`

---

lib/codecept.js
test/data/sandbox/codecept.glob.json
test/data/sandbox/fs_test.glob.js
test/docker-compose.yml
test/runner/codecept_test.js

[feature] Enable glob patterns in `config.test` / `Codecept.loadTests`

---

docs/pageobjects.md

Remove misleading info

---

CHANGELOG.md
lib/listener/helpers.js
test/data/helper.js
test/runner/codecept_test.js

Removed double call to Helper._init

---

docs/puppeteer.md
lib/helper/Puppeteer.js

Puppeteer fix

---

examples/codecept.json
examples/yahoo_test.js
lib/codecept.js
lib/command/run-multiple.js
lib/command/run-multiple/collection.js
lib/command/run.js
lib/utils.js
test/data/sandbox/codecept.multiple.json
test/runner/run_multiple_test.js

Fixed parallel test execution

---

docs/reports.md

this will fix #865 which is already closed but I thought it is a good idea to add the info on the docs as well

updated documentation on reporters

---

lib/helper/Nightmare.js
test/helper/webapi.js

Based on analysis on slack channel, method for grabNumberOfVisibleElements now reflects methodology as used by seeElement. Als mention for Jinbo Jinboson for looking into this issue.

Fix for grabNumberOfVisibleElements, fixes #1081

---

lib/config.js
lib/output.js
lib/reporter/cli.js
lib/step.js
lib/within.js
test/data/sandbox/codecept.po.json
test/data/sandbox/fs_test.po.js
test/data/sandbox/support/custom_steps.js
test/data/sandbox/support/my_page.js
test/runner/interface_test.js
test/runner/run_multiple_test.js
test/runner/session_test.js
test/runner/within_test.js

This enhancement allows displaying steps from page objects as well as their corresponding callers.

Nested steps implementation

---

docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriverIO.md
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/WebDriverIO.js
test/data/app/view/form/wait_js.php
test/helper/Nightmare_test.js
test/helper/ProtractorWeb_test.js
test/helper/Puppeteer_test.js
test/helper/WebDriverIO_test.js

`I.waitUntil(fn)` runs `fn` in context of node, not browser.

Run waitUntil script in browser context for WebDriverIO

---

lib/helper/Protractor.js
lib/helper/WebDriverIO.js

This is the solution for
https://codeceptjs.slack.com/archives/C94G8JXJB/p1528297919000909

https://codeceptjs.slack.com/archives/C94G8JXJB/p1528297919000909 and https://github.com/Codeception/CodeceptJS/issues/1026

---

CHANGELOG.md
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
test/helper/webapi.js

Fixed compatibility with other helpers
Fixes #1102 
Fixes #1128

Grab from compatibility

---

examples/codecept.json
examples/features/google.feature
examples/step_definitions/steps.js
lib/interfaces/gherkin.js
lib/scenario.js
test/data/sandbox/features/async.feature
test/data/sandbox/features/step_definitions/my_other_steps.js
test/data/sandbox/features/step_definitions/my_steps.js
test/runner/bdd_test.js
test/unit/bdd_test.js

Reproduce issue

---

.gitignore
lib/command/definitions.js
lib/parser.js

generates TS declarations for custom steps (like login(user,pass) ) and say(msg).

Reinstate typescript generation for custom steps

---

docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriverIO.md
docs/webapi/waitForFunction.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/WebDriverIO.js
test/helper/Nightmare_test.js
test/helper/ProtractorWeb_test.js
test/helper/Puppeteer_test.js
test/helper/WebDriverIO_test.js

Add ability to pass arguments to `waitForFunction`.

Add arguments pass for waitForFunction

---

CHANGELOG.md
docs/basics.md
lib/helper/WebDriverIO.js
lib/pause.js

Added next to interactive shell

---

docs/advanced.md

Adding in the debug part of the documentation
• Visual Studio Code configuration information for debugging.

documentation:  add vscode config

---

lib/helper/Puppeteer.js

@DavertMik - My first ever commit to open source project, let me know if need to run any tests. I create test project that open website then pause(), no errors generated.

Fix typo and duplicate content in Puppeteer JSDoc Example #2

---

Dockerfile
docker/run.sh
docs/docker.md

This to fulfill this https://github.com/Codeception/CodeceptJS/issues/1264

Introduce run-multiple into CODECEPT_ARGS in Docker-Compose

---

package.json

Updated inquirer version in order to fix audit issues

---

lib/command/definitions.js

https://github.com/Codeception/CodeceptJS/issues/1370

avoid error as reported at issues 1370

---

docs/angular.md
docs/basics.md
docs/plugins.md
docs/puppeteer.md
docs/reports.md
docs/translation.md
lib/command/run-multiple.js
lib/plugin/stepByStepReport.js

Updated occurrences of invalid image urls which were forgotten when changing support documentation.

Properly render images linked in support documentation

---

docs/helpers/ApiDataFactory.md
docs/helpers/Appium.md
docs/helpers/FileSystem.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/REST.md
docs/helpers/WebDriver.md
examples/codecept.json
examples/github_test.js
lib/codecept.js
lib/helper/ApiDataFactory.js
lib/helper/Appium.js
lib/helper/FileSystem.js
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/REST.js
lib/helper/WebDriver.js
lib/listener/steps.js
lib/pause.js
lib/plugin/autoDelay.js
lib/plugin/retryFailedStep.js
lib/step.js
lib/store.js

* retryFailedStep and autoDelay plugins - no more disturbs interactive pause
* meta step detection disabled in interactive pause, so no more `Interface: parseInput` printed
* introduced new `store.js` to save global information for the test run...

Improved pause

---

lib/helper/WebDriver.js
package.json

* Use `isElementEnabled` instead of previously named `getElementEnabled`.

Update webdriverio package to version 5.2.2.

---

lib/plugin/allure.js
lib/ui.js

+ Add tags to allure report
+ when set tag like `@skip-wdio` codeceptjs collected only `@skip`

add tags to allure report + fix collect tag

---

lib/interfaces/scenarioConfig.js
lib/ui.js
test/unit/ui_test.js

fix https://github.com/Codeception/CodeceptJS/issues/1358
fix https://github.com/Codeception/CodeceptJS/issues/1472

Fix Dynamic Injection

---

package.json

add linter run on pre-commit
and linter with test runs on pre-push

add husky rules for pre-commit and pre-push

---

lib/helper/WebDriver.js

Regarding this https://github.com/Codeception/CodeceptJS/issues/1517

update the deprecated method of wdio v5

---

docs/reports.md

I spend few hours before understand how use XUnit with Mocha Multi Reports.
Thanks God I found example of configuration in https://github.com/Codeception/CodeceptJS/issues/1502

Add junit example in Multi Reports

---

docs/plugins.md
lib/plugin/autoLogin.js

Issue: https://github.com/Codeception/CodeceptJS/issues/1545

fixed autoLogin local storage example

---

lib/helper/Puppeteer.js
lib/plugin/autoLogin.js

Yeah, it was not working. Sorry

Fixed autologin with cookies for Puppeteer

---

lib/plugin/autoLogin.js

for more complex login functions it's sometimes necessary to grab
information from the page
this isn't possible without this fix

fix async login, check + fetch for autologin plugin

---

lib/plugin/wdio.js

Added wdio plugin to run webdriverio services

Feature: plugin to execute wdio services

---

docs/reports.md
lib/plugin/screenshotOnFail.js

feat for this https://github.com/Codeception/CodeceptJS/issues/1502

(feat)-Enabled the adding screenshot to failed test for moch-junit-reporter

---

lib/listener/trace.js
lib/recorder.js
lib/session.js
lib/within.js
test/unit/plugin/retryFailedStep_test.js

fix https://github.com/Codeception/CodeceptJS/issues/1629
fix https://github.com/Codeception/CodeceptJS/issues/1622

do not retry within and session

---

CHANGELOG.md
docs/changelog.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md
docs/helpers/WebDriverIO.md
docs/webapi/refreshPage.mustache
lib/container.js
package.json

Fix autologin

---

lib/helper/WebDriver.js
test/helper/WebDriver_test.js

fix https://github.com/Codeception/CodeceptJS/issues/1655

Fix checkOption and uncheckOption in WebDriver Helper

---

lib/command/definitions.js

Added definition of global `inject` function.
Added definition of scenario's `injectDependencies` function and updated `ICodeceptCallback` generation, to support dynamic injection.
Slightly updated definition template generator to be more linter-according.

Update typescript definitions for inject

---

lib/interfaces/gherkin.js
test/data/sandbox/features/IncludeExamplesInDataTable.feature
test/data/sandbox/features/step_definitions/my_steps.js
test/runner/bdd_test.js

Hello,
With this PR when you create a gherkin file that combine a scenerio outline and Table: Example value will be replaced inside the table.
I added a new test : IncludeExamplesInDataTable.feature

Updated gherkin interface in order to update table with placholder of exemple for scenario outlines

---

lib/helper/WebDriver.js
test/helper/WebDriver_test.js

* unit test
* fix linter issues

fix (#1677) session browser window dimensions and timeout

---

docs/basics.md
docs/commands.md
lib/command/definitions.js
lib/command/init.js
test/runner/list_test.js

- bugfix for typescript type definition
- can auto-complete in `Data(string).Scenario(string, callback)`
- using tsconfig.json altenate to reference path

Improve method auto-completion

---

lib/plugin/allure.js

There were too few functions in allure plugin

updated allure plugin

---

lib/helper/Appium.js

Solution: handle webdriverio specs correctly

Fix issue of "host" configuration not work correctly on Appium.

---

CHANGELOG.md
docs/changelog.md

[WIP] doc: fix broken link in changelog.md

---

lib/scenario.js

style: fix ESLint errors

---

lib/command/run-multiple.js
lib/hooks.js
test/data/sandbox/codecept.async.bootstrapall.multiple.code.js
test/runner/run_multiple_test.js

Async bootstrapAll invoked after calling done.
And when I need to override configuration parameters like "tests" I can't do that because bootstrapAll has an asynchronous function that codeceptjs wasn't waiting

fix(multiple): async bootstrapAll must be called before creating chunks

---

package.json

chore: update package nyc to 14.1.1

---

lib/command/run-multiple.js
lib/utils.js
test/unit/utils_test.js

Bug:
If value in config has falsy value, then multiple config does not overwrite original value.
Fixes #1754

Fix multiple run falsy parameter overriding

---

docs/helpers/Puppeteer-firefox.md
docs/helpers/Puppeteer.md
docs/puppeteer.md
lib/helper/Puppeteer.js

Adding support of Puppeteer-firefox to Codeceptjs
https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox

Puppeteer firefox to codeceptjs

---

lib/helper/Polly.js

Added some preconditions to check for puppeteer page is open or not.
resolves #1767

fix: add preconditions to check for puppeteer page availability

---

lib/step.js

fix: skip Runner to detect MetaStep

---

docs/advanced.md
lib/interfaces/scenarioConfig.js
test/acceptance/config_test.js

In some cases the decision about the config needs to be take asynchronously.

feat: async dynamic config

---

lib/helper/TestCafe.js
lib/helper/testcafe/testcafe-utils.js
test/helper/webapi.js

Fixes and more helper method implementations

Testcafe fixes

---

lib/helper/Polly.js
lib/utils.js
test/acceptance/codecept.Puppeteer.js
test/acceptance/mock_test.js

**Problem:** No config `url` specific for Polly helper.
**Solution:** Use Puppeteer helper configs.
resolves #1766

refactor: Use puppeteer config for Polly

---

lib/helper/Puppeteer.js

...by making Puppeteers .type(...) delay configurable (option pressKeyDelay)

Puppeteer: Speed up tests with large forms

---

bin/codecept.js

`codeceptjs -V`
It is intended to have a dedicated `-V` flag which shows up the version information.

feat(cli): Adds version flag

---

bin/codecept.js

`codeceptjs`
```bash
Usage:  <command> [options]
Options:
-h, --help                                      output usage information
Commands:
init [path]                                     Creates dummy config in current dir or [path]
migrate [path]                                  Migrate json config to js config in current dir or [path]
shell|sh [options] [path]                       Interactive shell
list|l [path]                                   List all actions for I.
def [options] [path]                            Generates TypeScript definitions for all I actions.
gherkin:init|bdd:init [options] [path]          Prepare CodeceptJS to run feature files.
gherkin:steps|bdd:steps [options] [path]        Prints all defined gherkin steps.
gherkin:snippets|bdd:snippets [options] [path] …
```

fix(cli): Fixup usage info

---

bin/codecept.js

`codeceptjs junkcmd`
```bash
Unknown command junkcmd
Usage: codeceptjs [options] [command]
Options:
-h, --help                                      output usage information
Commands:
init [path]                                     Creates dummy config in current dir or [path]
migrate [path]                                  Migrate json config to js config in current dir or [path]
shell|sh [options] [path]                       Interactive shell
list|l [path]                                   List all actions for I.
def [options] [path]                            Generates TypeScript definitions for all I actions.
gherkin:init|bdd:init [options] [path]          Prepare CodeceptJS to run feature files.
gherkin:steps|bdd:steps [options] [path]        Prints all defined gherkin steps. …
```

feat(cli): warn on unknown commands

---

lib/actor.js
lib/interfaces/gherkin.js
lib/reporter/cli.js
test/runner/bdd_test.js

- Can we fire events for I.say()
- and add the return value of commands (e. g. from REST requests) to step.passed?
Specifically useful for codepress.

Fire event on I.say() and add return val to step.passed

---

lib/helper/Puppeteer.js

Prior only initial page would have configuration applied, new pages/tabs or (incognito) sessions would have default values.

Ensure configured user agent and/or window size is applied to all pages.

---

lib/config.js

Config hooks allow to set functions to update complex configs on the fly.
For instance, you can use them to enable/disable headless modes, window sizes, etc.

Introduced config hooks

---

docs/changelog.md
docs/locators.md
examples/codecept.conf.js
lib/plugin/customLocator.js
test/unit/plugin/customLocator_test.js
website/core/Footer.js
website/i18n/en.json
website/pages/en/help.js

Simplified declaring custom plugins
```js
// replace this:
I.click({ css: '[data-test-id=register_button]');
// with this:
I.click('$register_button');
```
config:
```js
// in codecept.conf.js
plugins: {
customLocator: {
enabled: true
attribute: 'data-test-id'
}
}
```

custom locator plugin

---

docs/visual.md

This is adding the docs for visual check using Applitools. I know this is very primitive. Any suggestions are more than welcome.

(docs): visual check using applitools

---

website/static/css/custom.css

fix search icon

---

docs/webapi/grabElementBoundingRect.mustache
docs/webapi/grabElementSize.mustache
lib/helper/Puppeteer.js
lib/helper/WebDriver.js
test/helper/Puppeteer_test.js
test/helper/WebDriver_test.js

https://github.com/Codeception/CodeceptJS/issues/1867
this would add `grabElementBoundingRect`method for WDIO and Puppeteer.

implement grabElementBoundingRect for wdio and puppeteer helpers

---

CHANGELOG.md
docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/WebDriverIO.md
docs/plugins.md
lib/helper/REST.js

Rest headers

---

Dockerfile
docker/README.md
docker/run.sh

- include the `run-workers`
- update README

update the docker image to include run-workers

---

lib/helper/TestCafe.js

https://testcafe-discuss.devexpress.com/t/api-how-to-clear-a-text-input/402/11 
MarinaRukavitsyna's answer (platform independent solution)

Fix of #1989

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

[ ] Webdriver
[ ] Puppeteer
[ ] Nightmare
[ ] REST
[ ] Appium
[ ] Protractor
[ ] TestCafe
- Some minor fixes on templates.

update minor things in templates

---

lib/helper/Puppeteer.js
test/helper/webapi.js

fix addresses this issue https://github.com/Codeception/CodeceptJS/issues/1863

fix XPath is not a function for waitForText

---

docs/webapi/executeAsyncScript.mustache
docs/webapi/executeScript.mustache

Expect them to happen more often when I bump into them :)

Small JSDoc additions

---

docs/helpers/Protractor.md
docs/helpers/WebDriver.md
docs/helpers/WebDriverIO.md
lib/helper/Protractor.js
lib/helper/WebDriver.js
lib/helper/WebDriverIO.js

- Webdriver
- Puppeteer
- Documentation changes/updates

Improve headless chrome example

---

lib/command/definitions.js
test/data/sandbox/configs/definitions/codecept.inject.po.json
test/data/sandbox/configs/definitions/po/custom_steps.js
test/runner/definitions_test.js

fix(ts): FIx relative path for PageObject

---

lib/helper/Puppeteer.js
test/helper/Puppeteer_test.js

fix(#2026): Failed to read the 'localStorage' property from 'Window'

---

CHANGELOG.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/REST.md
docs/helpers/WebDriver.md
docs/helpers/WebDriverIO.md
package.json

2.3.6 release

---

.github/PULL_REQUEST_TEMPLATE.md

change docs generating command

---

.github/CONTRIBUTING.md
docs/changelog.md
docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/TestCafe.md
docs/helpers/WebDriver.md
docs/helpers/WebDriverIO.md
docs/webapi/grabCookie.mustache
package.json
runio.js

fix(docs): Incorrect types in docs for helpers

---

docs/pageobjects.md
lib/helper/FileSystem.js

fix(docs): fix export information for pageobjects

---

README.md

fix(docs): Add contributing guide and code of conduct to README.md

---

docs/helpers/Appium.md
docs/helpers/WebDriver.md
docs/webapi/scrollIntoView.mustache
lib/helper/Appium.js
lib/helper/WebDriver.js
test/data/app/view/form/scroll_into_view.php
test/helper/WebDriver_test.js
typings/types.d.ts

See https://webdriver.io/docs/api/element/scrollIntoView.html

Introduce scrollIntoView for WebDriver & Appium

---

docs/basics.md
docs/plugins.md
examples/codecept.conf.js
lib/plugin/pauseOnFail.js
typings/types.d.ts

Pause on fail

---

runio.js
test/runner/definitions_test.js

* Typings should be generated before `definitons_test`
* Typings should be generated before release

Fixed typings, stabilized release process

---

.github/PULL_REQUEST_TEMPLATE.md

Add the key words to close issue once the PR is merged.

(doc): update PULL_REQUEST_TEMPLATE.md

---

docs/translation.md
lib/ui.js
test/data/sandbox/configs/translation/codecept.conf.js
test/data/sandbox/configs/translation/translation_test.js
test/runner/translation_test.js
test/unit/container_test.js
translations/it-IT.js

Added support to translate Feature, Scenario, Before, After, BerforeSuite and AfterSuite
Fixes #2083

feat: Add translation ability to context methods

---

test/acceptance/mock_test.js

increase timeout on waitForText

(improvement): fix failed case

---

.gitignore
examples/selenoid-example/browsers.json
examples/selenoid-example/codecept.conf.js
examples/selenoid-example/git_test.js
lib/plugin/selenoid.js

To integrate selenoid with CodeceptJS.
Supported features :
- Create/start/stop selenoid docker image automatically
- Video recording
- Log recording
currently supported Webdriver. For Windows machine, docker will not be created automatically but start and stop will work
Fixes #2117 
Resolves #1267

feat: Add selenoid plugin

---

docs/basics.md
examples/github_test.js
lib/pause.js

Fixed pause

---

docs/hooks.md

fix(docs): Incorrect import for custom runner example

---

CHANGELOG.md
docs/plugins.md
docs/puppeteer.md
docs/webdriver.md
examples/selenoid-example/codecept.conf.js
lib/pause.js
lib/plugin/selenoid.js
lib/reporter/cli.js
package.json
test/runner/bdd_test.js

Please review this update.
This PR includes fixes to several other pull requests:
* selenoid plugin - updated with better logging and documentation. Added allure support.
* `event.step.comment` removed comments for meta steps. This feature never worked fine and it broke allure reports when @PeterNgTr introduced allure reports for `I.say` commands
* changed and updated documentation in various places

Release 2.4.2

---

docs/helpers/FileSystem.md
docs/plugins.md
lib/helper/FileSystem.js
test/data/sandbox/configs/bootstrap/failed_test.js
test/data/sandbox/configs/bootstrap/fs_test.js
test/helper/Puppeteer_test.js

- add waitForFile Resolves #1587
- add seeFileContentsEqualReferenceFile
- fix encoding

improve file system helper

---

lib/command/init.js

(fix): refer the wrong key compilerOptions

---

lib/command/definitions.js

Resolves: https://github.com/Codeception/CodeceptJS/issues/2084

Update definitions.js to fix @bad slash in steps.d.ts bug typescript

---

.github/workflows/check.yml

This aims to make check tests action run on forked PR.

(fix): github actions run on forked PR

---

typings/index.d.ts

fix(ts): add typing for Scenario.todo

---

lib/helper/Puppeteer.js
test/data/app/controllers.php
test/data/app/index.php
test/data/app/view/redirect_long.php
test/helper/Puppeteer_test.js

fix(Puppeteer): #waitForText - Cannot read property 'innerText' of null

---

lib/container.js
package.json
typings/Mocha.d.ts
typings/index.d.ts

- Resolves: https://github.com/Codeception/CodeceptJS/issues/2055

fix(mocha-ts): Fix conflicts with mocha and jest typings

---

lib/listener/helpers.js

Getting frustrated when I see some unreadable error.
- Logging what went wrong

Proper message for problem with addons

---

.github/PULL_REQUEST_TEMPLATE.md

- add new helper to list
- add plugin section
- polish template

(imp): add new helper

---

lib/command/run-workers.js
lib/workers.js
test/unit/worker_test.js

- Refactored run-workers with worker API
- Resolves #2161

Refractor run-workers

---

docs/basics.md

I guess docs had older version?

update interactive shell in basics.md

---

README.md
lib/codecept.js

- The example shows the wrong use of let, the value should be `const`
- when committing, an error about importing popped up, that's what my second commit fixes.
- [ x ] :bug: Bug fix
- [ x ] :clipboard: Documentation changes/updates
- [ x ] Documentation has been added (Run `npm run docs`)
- [ x ] Lint checking (Run `npm run lint`)
- [ x ] Local tests are passed (Run `npm test`)

Readme update and fix import

---

lib/command/run-workers.js

Fixed finishedTest checks in run-workers command with rerun parameter

---

package.json

- Bump `mkdirp` version to avoid warnings.
- Resolves #2279.

bump mkdirp version

---

docs/helpers/WebDriver.md
lib/helper/WebDriver.js
package.json

As wdio has its major release [v6](http://v6.webdriver.io/blog/2020/02/22/webdriverio-v6-released.html), we actively update our `WebDriver` helper to adapt new changes. We won't expect any breaking changes in CodeceptJS like we had with V5 before. Currently, the update is smooth, we don't see any much major changes in our helper.  Feel free to give it a try and give any feedbacks for us. That would be great!
```sh
1) WebDriver
#moveCursorTo
should not trigger hover event because of the offset is beyond the element:
expected element #show not to include "Hovered"
+ expected - actual
-------
-Hovered!
-------
+Hovered
2) WebDriver
window size #resizeWindow
should set initial window size:
expected element #height to include "Height 700"
3) WebDriver …
```

[WebDriver]: upgrade to wdio v6

---

lib/mochaFactory.js

Fix run-workers issue in gherkin 2.6

---

lib/mochaFactory.js

Fix run-workers issue in gherkin

---

.semaphore/appiumTests.yml
.semaphore/semaphore.yml
package.json

(enh): Introduce yaml config file for semaphore 2.0

---

lib/plugin/allure.js

- Resolves #2321.
[ForkLint.txt](https://github.com/Codeception/CodeceptJS/files/4449967/ForkLint.txt)
[ForkTest.txt](https://github.com/Codeception/CodeceptJS/files/4449968/ForkTest.txt)

#2321 - Modified the allure.js to support for custom runners

---

package.json

Added     "@codeceptjs/mock-request": "^0.3.0",
- Resolves #2338 

adding mock-request dep

---

lib/helper/Playwright.js
package.json
test/helper/Playwright_test.js

updated to Plawyright 0.13, added handleDownloads

---

CHANGELOG.md
package.json

Release v2.6.2

---

lib/command/run-workers.js
lib/command/workers/runTests.js
lib/reporter/cli.js

- Added `skipped` event for workers too

Add skipped event for workers

---

lib/workers.js

Ported #2387 to 3.0 branch
workers was refactored in 3.0 so a patch should be reapplied

Skipped tests for workers

---

docs/quickstart.md

- Resolves #issueId (if applicable). 
issue #2394

Fix valid data output (w3)

---

docs/ui.md

add alt for image UI page (fix w3 validator)

---

docs/basics.md

remove unnecessary select placeholder from basics.md

---

docs/changelog.md

fix display combination in changelog

---

docs/basics.md
docs/testcafe.md
docs/videos.md

add description to images

---

lib/event.js
lib/step.js
package.json
test/runner/run_workers_test.js
test/unit/steps_test.js

fix(metastep): Remove emitted events

---

docs/basics.md
docs/books.md
docs/changelog.md
docs/community-helpers.md
docs/custom-helpers.md
docs/examples.md
docs/hooks.md
docs/locators.md
docs/translation.md
docs/videos.md

issue #2441
- [] Tests have been added

update github links after repository migration

---

CHANGELOG.md
package.json

Prepare CodeceptJS to 3.0.0-beta.4

---

docs/videos.md

fix markdown video links

---

lib/plugin/allure.js
lib/plugin/autoDelay.js
lib/plugin/puppeteerCoverage.js
lib/plugin/retryFailedStep.js
lib/plugin/screenshotOnFail.js
lib/plugin/stepByStepReport.js
lib/plugin/wdio.js

update plugins page "h" tags for more readable

---

docs/helpers/WebDriver.md
lib/helper/WebDriver.js
test/helper/WebDriver_test.js

The PR solve the  issue of rightclick() for webdriver.
#2433, #2414, #1883
- [] Documentation has been added (Run `npm run docs`)

Right click issue fix for Webdriver

---

lib/plugin/autoDelay.js
lib/plugin/standardActingHelpers.js

fix no screenshot for failed tests

---

CHANGELOG.md
docs/books.md
docs/changelog.md
docs/community-helpers.md
docs/detox.md
docs/examples.md
docs/videos.md

update to relevant path & some fix

---

docs/helpers/Nightmare.md
docs/helpers/Playwright.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/TestCafe.md
docs/helpers/WebDriver.md
docs/webapi/saveElementScreenshot.mustache
lib/helper/Nightmare.js
lib/helper/Playwright.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/TestCafe.js
lib/helper/WebDriver.js
test/helper/webapi.js

User will be able to capture screenshot of specified element
#2401

element screenshot method added

---

docs/custom-helpers.md

📋  Fix generate:helper command doc

---

lib/helper/Playwright.js
lib/helper/Puppeteer.js

feat(helper): Clear SessinStorage

---

lib/helper/Playwright.js

Fix broken URLs

---

README.md

- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2533.

update readme file urls

---

docs/basics.md
docs/books.md
docs/changelog.md
docs/community-helpers.md
docs/configuration.md
docs/custom-helpers.md
docs/data.md
docs/email.md
docs/examples.md
docs/hooks.md
docs/locators.md
docs/translation.md
docs/ui.md
docs/videos.md

- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2526.

update docs md to relevant path

---

lib/container.js

Improve error message when helper load failed

Preserve initial error stack when helper load fail

---

CHANGELOG.md
docs/helpers/Appium.md
docs/helpers/Playwright.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md
package.json

Release 2.6.9

---

CHANGELOG.md
docs/advanced.md
package.json
test/unit/ui_test.js

Release 2.6.10

---

runio.js

update runio urls

---

lib/helper/Playwright.js

(fix): typo in playwright docs

---

docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Playwright.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/TestCafe.md
docs/helpers/WebDriver.md
docs/typescript.md
runio.js

doc(ts): Add typescript documentation

---

lib/helper/WebDriver.js

Code Fix for dragSlider issue
- Resolves #2557

Action Api Updated for dragSlider method

---

docs/bdd.md

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

:clipboard: Fix iteration over array values on bdd example doc

---

test/data/sandbox/configs/pageObjects/codecept.class.js
test/data/sandbox/configs/pageObjects/custom_objects_test.js
test/data/sandbox/configs/pageObjects/steps_file.js
test/runner/pageobject_test.js

- Proves https://github.com/codeceptjs/CodeceptJS/issues/2579 is a problem

broken test case for custom step files

---

lib/container.js

fix(#2579): say and retry methods now work correctly

---

lib/helper/Nightmare.js
lib/helper/Playwright.js
package.json
test/helper/Playwright_test.js

* updated Playwright to 1.4
* Fixed failing tests for Playwright

Playwright compat

---

CHANGELOG.md
docs/helpers/Playwright.md
package.json

prepare 2.6.11 release

---

lib/reporter/cli.js

Added skipped event if the test itself is skipped

Add skipped event for pending tests

---

docs/best.md

This PR adds small corrections / removes typos in best practices md file.

doc: typos in best practices documentation file

---

docs/angular.md
docs/basics.md
docs/data.md
docs/helpers/REST.md
docs/plugins.md
lib/helper/REST.js
lib/plugin/autoLogin.js

fix documentation

---

docs/advanced.md
docs/basics.md
docs/plugins.md

- Update documentations to reflect new I actor syntax

(docs): update some places in md files that missing new syntax

---

README.md
docs/helpers/Playwright.md
docs/helpers/Puppeteer.md
docs/plugins.md
lib/helper/Playwright.js

- Update docs of Playwrights, Puppeteer and contributor faces
- Resolves #2649 

docs: updates

---

lib/command/workers/runTests.js
lib/workers.js

- Fixes: https://github.com/codeceptjs/CodeceptJS/issues/2620

Autologin workers

---

docs/parallel.md

Add `event` import and fix `testGroups` reference
- Fix example code in docs so it works out of the box

Fix small issues with paralell example

---

CHANGELOG.md
docs/helpers/REST.md
lib/helper/Puppeteer.js
lib/helper/REST.js
package.json
test/rest/REST_test.js

Release 3.0.2

---

docs/examples.md

- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2676

update examples.md link

---

docs/examples.md
docs/typescript.md

fix this issue https://github.com/codeceptjs/CodeceptJS/issues/2680

update relative links

---

CHANGELOG.md
docs/changelog.md

- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2685

update relative links (changelog)

---

docs/playwright.md

docs: fix code for Multi Session Testing

---

docs/helpers/FileSystem.md
lib/helper/FileSystem.js

fixes #2653 remove private documentation

---

docs/typescript.md

doc(fix): typo in IntelliSense

---

CHANGELOG.md
docs/installation.md
lib/command/init.js
lib/container.js
lib/helper/Playwright.js
lib/helper/Puppeteer.js
lib/plugin/standardActingHelpers.js
lib/plugin/wdio.js
package.json

Release 3.0.3

---

.github/CONTRIBUTING.md
package.json

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
- Resolves: #2729

[Hotfix] Add cross-spawn package

---

lib/helper/WebDriver.js

- this is tiny typo fix "awailable -> available"

awailable -> available

---

package.json

The direct prod dependency "axios" has some security problems (Server Side Request Forgery) triggering multiple scanner. The update from currently used 0.19.1 to latest 0.21.1 fixes these problems.
https://npmjs.com/advisories/1594
As this is a prod dependency for CodecpetJS all other projects using codecept will get security warnings (e.g. from `npm audit`) depending on your project. This resolves these warnings.
This fix does not address security problems within Codecept dev dependencies.
For the following questions (helpers / plugins) i do not know which one are affected by this dependency updater, therefore not ticked anything.
Additional tests and documentation updates are not needed.

security update for axios (0.21.1)

---

.travis.yml

- disable 2 travis builds on PR

fix: Update .travis.yml

---

typings/index.d.ts

- TS complains when using `xFeature`, this PR aims to fix that.

fix: missing type of xFeature

---

docs/helpers/Nightmare.md
lib/helper/Nightmare.js

fix(typings): for grabValueFromAll method in Nightmare helper

---

docs/mobile.md

Hello, 
according to this issues : https://github.com/codeceptjs/CodeceptJS/issues/1672
I suggest to add platform value to the documentation (mandatory parameter).
Thank's for your documentation !
- This PR add a mandatory parameter for the Browserstack configuration file.
- Resolves #1672

[DOCUMENTATION] Update conf for Browserstack

---

lib/helper/WebDriver.js

fix(webdriver): parse locator object with JSON.stringify function to properly display locator in console

---

docs/helpers/Playwright.md
lib/helper/Playwright.js

fix(typings): seeTitleEquals, forceClick, executeScript methods for Playwright and api link

---

docs/data.md
docs/detox.md
docs/locators.md
docs/mobile-react-native-locators.md
docs/mobile.md

fixed issue 2755: global search/replace broke some code examples

---

CHANGELOG.md
package.json

Release PR for 3.0.5

---

lib/cli.js
lib/interfaces/gherkin.js
lib/output.js
lib/step.js
lib/within.js

* Fixes handling meta-steps with page objects
* Fixed CLI formatting for meta-steps
* Fixed BDD tests
Resolves  #2720 #2682

fixed cli reporter

---

docs/parallel.md

- The run-worker sample code in documentation had a parser error. Fixed the doc with a working code snippet

Fix documentation example code for worker config

---

docs/helpers/Playwright.md
lib/helper/Playwright.js
test/helper/Playwright_test.js

- Implements `launchPersistentContext` to be able to launch in Normal mode
- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2376.

Implements playwright persistent context

---

package.json

- Upgrades Puppeteer to its 8th version, therefore allowing us to get benefit from the latest [improvements](https://github.com/puppeteer/puppeteer/tags) since version 4.

Upgraded Puppeteer to 8th version

---

docs/examples.md

- fix issue https://github.com/codeceptjs/CodeceptJS/issues/2843

update examples docs link

---

CHANGELOG.md
docs/basics.md
docs/changelog.md

Fix links to `tryTo` function.

doc: fix links for tryTo function

---

docs/nightmare.md

- fix issue https://github.com/codeceptjs/CodeceptJS/issues/2842

remove broken link

---

docs/email.md

Fixing small errors in markdown file.

Small errors in email documentation file

---

docs/parallel.md

- Improves documentation of "Sharing Data Between Workers" in `docs/parallel.md`

PR: Improve documentation for "Sharing Data Between Workers" section

---

bin/codecept.js
lib/command/interactive.js

- Running codeceptjs shell with a custom configuration file. `npx codeceptjs shell -c foo.conf.js`
- Resolves #2879

feat: support config file for shell command

---

CHANGELOG.md
docs/helpers/MockRequest.md
docs/helpers/Playwright.md
docs/helpers/WebDriver.md
docs/parallel.md
package.json

release 3.0.7

---

docs/mobile.md

- fix for syntax error in documented code snippet for Appium helper
- [ x ] :clipboard: Documentation changes/updates

Appium Docs: Fix for wrong syntax

---

lib/actor.js

I just simplified the code with `Object.values` instead of `Object.keys + map`

Minor simplify add methods in actor

---

lib/listener/helpers.js

Just a little simplify `runHelpersHook`;

Minor simplify runHelpersHook

---

.github/workflows/appium.yml
.github/workflows/check.yml
.github/workflows/dtslint.yml
.github/workflows/playwright.yml
.github/workflows/puppeteer.yml
.github/workflows/test.yml
.github/workflows/testcafe.yml
.github/workflows/webdriver.yml
docs/changelog.md
docs/examples.md
docs/helpers/Playwright.md
lib/helper/Puppeteer.js
lib/helper/errors/ConnectionRefused.js
package.json
test/helper/WebDriver_test.js
test/support/TestHelper.js

- [ x] WebDriver
- [ x] Puppeteer

puppeteer and webdriver migrated

---

docs/plugins.md
lib/plugin/commentStep.js

Fix commentStep docs typo

---

docs/playwright.md
examples/codecept.conf.js
examples/launch-playwright.js
lib/helper/Playwright.js
lib/listener/exit.js
lib/locator.js
test/helper/Playwright_test.js

Playwright improvments

---

CHANGELOG.md
lib/helper/Appium.js
lib/helper/WebDriver.js
test/helper/Appium_test.js

fixed #2759

---

lib/plugin/customLocator.js
lib/plugin/tryTo.js

(chore) Fix typos in docs

---

lib/helper/Playwright.js

- Resolves #2986 
- Playwright
- bug: Bug fix

Fix for https://github.com/codeceptjs/CodeceptJS/issues/2986

---

lib/helper/Playwright.js

- Resolves #ihttps://github.com/codeceptjs/CodeceptJS/issues/3003

Fix for https://github.com/codeceptjs/CodeceptJS/issues/3003

---

lib/mochaFactory.js

- Showing info when while file is missing the Feature section
```
thanh@Thanhs-MacBook-Pro automation % npx codeceptjs run --verbose
Missing Feature section in:
/Usersthanh/Desktop/automation/apis/happy_paths/checkout_flow_test.ts
CodeceptJS v3.0.7
Using test root "/Users/thanh/Desktop/automation"
...
```
- Resolves #2988

improvement: showing missing feature in test

---

docs/reports.md

- Adding the testrail plugin report

docs: adding testrail-plugin report

---

.github/CONTRIBUTING.md
docs/changelog.md
docs/commands.md
docs/helpers/Appium.md
docs/helpers/Puppeteer.md
docs/playwright.md
examples/codecept.conf.js
lib/recorder.js

Recorder range error

---

docs/helpers/Appium.md
docs/helpers/WebDriver.md

- https://github.com/codeceptjs/CodeceptJS/issues/3106

update webdriver links

---

docs/basics.md

https://github.com/codeceptjs/CodeceptJS/issues/3108

update basics.md link

---

lib/command/info.js

Slack link points to unrelated YouTube channel

---

CHANGELOG.md
lib/helper/Playwright.js
lib/helper/Puppeteer.js
lib/plugin/retryFailedStep.js
package.json

fix browser crashes

---

docs/helpers/ApiDataFactory.md
docs/helpers/Appium.md
docs/helpers/GraphQLDataFactory.md
docs/helpers/Nightmare.md
docs/helpers/Playwright.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md

https://github.com/codeceptjs/CodeceptJS/issues/3129

update helpers links

---

docs/changelog.md

https://github.com/codeceptjs/CodeceptJS/issues/3138

update changelog links

---

typings/index.d.ts

Update type Cookie for playwright

---

lib/helper/Appium.js

Add to Appium Helper jsdoc missing return types

---

docs/configuration.md

https://github.com/codeceptjs/CodeceptJS/issues/3142

update configuration.md links

---

docs/custom-helpers.md

https://github.com/codeceptjs/CodeceptJS/issues/3151

update custom-helpers.md links

---

docs/data.md

https://github.com/codeceptjs/CodeceptJS/issues/3156

update data.md links

---

docs/installation.md
docs/mobile.md

update installation.md & mobile.md links

---

docs/nightmare.md
docs/playwright.md

https://github.com/codeceptjs/CodeceptJS/issues/3161

update nightmare.md & playwright.md links

---

docs/puppeteer.md
docs/reports.md
docs/testcafe.md
docs/translation.md
docs/videos.md
docs/visual.md
docs/vue.md
docs/webdriver.md

https://github.com/codeceptjs/CodeceptJS/issues/3164

update docs link

---

docs/plugins.md

Avoid dependency error reporting：assert not defined

Add documentation instructions

---

docs/advanced.md

Update advanced.md 

---

docs/mobile.md

Remove Excess close parenthesis

---

lib/helper/Playwright.js

Fix for https://github.com/codeceptjs/CodeceptJS/issues/3172

Fix for https://github.com/codeceptjs/CodeceptJS/issues/3172

---

docs/helpers/Playwright.md

add '=>' expected

---

.github/workflows/playwright.yml
.github/workflows/puppeteer.yml
.github/workflows/testcafe.yml
.github/workflows/webdriver.yml
CHANGELOG.md
docs/changelog.md
docs/helpers/ApiDataFactory.md
docs/helpers/Appium.md
docs/helpers/FileSystem.md
docs/helpers/GraphQLDataFactory.md
docs/helpers/Nightmare.md
docs/helpers/Playwright.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md
docs/plugins.md
lib/helper/FileSystem.js
lib/helper/Playwright.js
lib/plugin/autoLogin.js
lib/plugin/tryTo.js
package.json
test/acceptance/gherkin/shadow_dom.feature

3.2.3 release

---

docs/translation.md
test/unit/container_test.js
translations/pt-BR.js

- Update brasilian portuguese with contexts translations.

feat: upgrade pt-br translation with contexts

---

docs/playwright.md
docs/plugins.md
docs/puppeteer.md
docs/webdriver.md
examples/checkout_test.js
lib/plugin/eachElement.js
test/data/helper.js
test/unit/plugin/eachElement_test.js

Simplified API to iterate over elements

implemented eachElement plugin

---

lib/helper/Playwright.js
package.json
test/helper/Playwright_test.js

Playwright fixes
