README.md
lib/helper/WebDriverIO.js

It's my case, well, other developers might need this proxy option as well.
@DavertMik should add a configuration section for `codecept.json`?

Add proxy config

---

.gitignore
lib/codecept.js
lib/command/init.js
lib/utils.js

Add the test folder pass in argument to the init command to the resulted created json file.

Closes Codeception/CodeceptJS#9 , add the test folder to the codecept.json object

---

README.md

- reference in readme file was pointing to old link.
- Highlighted `I` to make reading easier

Fix reference link in Readme file

---

docs/pageobjects.md

fixes small typo in documentation:

Fix typo in Page Objects documentation

---

lib/helper/WebDriverIO.js
package.json

The original method of passing options to webdriverio caused some
confusion. If the user wanted to simply pass a webdriverio config
directly through the codeceptjs config some properties would get
overridden with undefined if they didn’t set `browser` or `url`.
It makes more sense to allow the passing of a webdriverio config rather
than attempting to map these properties and construct that object since
it can get extremely complex.
I.E
```js
// how you're currently doing it
{
"helpers": {
"WebDriverIO": {
"proxy": {
...
}
}
}
}
// it should be more like this
{
"helpers": {
"WebDriverIO": {
"desieredCapabilities": {
"proxy": {
...
}
}
}
}
}
```

better support for webdriverio options

---

lib/helper/WebDriverIO.js

```
I.scrollTo('.selector', 1500, 400)
**FAIL**  this.browser.scrollTo is not a function
```
WebDriverIO has no scrollTo function. I think it was typo.
Now, it's work.

fix WebDriverIO helper scrollTo

---

docs/helpers/WebDriverIO.md
lib/helper/WebDriverIO.js
test/unit/helper/WebDriverIO_test.js

I've been a big fan of CodeceptJS but missed support for IFrames since I switched from a Mocha & WebDriverIO testing stack to CodeceptJS. This merge implements the `frame()` method from https://github.com/webdriverio/webdriverio with a new method named `switchTo()` in the WebDriverIO helper.
`switchTo()` works the same as `frame()` by allowing the test case to change context to content inside an IFrame specified by a locator. Specifying a null locator (the default) will return the test case to the parent frame (usually the current window).
In addition to the new method in the WebDriverIO helper, I've added three test cases and updated the helper specific documentation.

Implemented WebDriverIO frame() with new method switchTo() in helper

---

lib/container.js

Before the change, I could not set an absolute path as my helpers path.
`path.join` would always stick the project directory in front.
`path.resolve` will, however, check if the path is already absolute, in which case it won’t do anything.

Fix path resolution for the helpers config values to support absolute paths

---

lib/codecept.js

Before the change, I could not set an absolute path as my output.
`path.join` would always stick the project directory in front.
`path.resolve` will, however, check if the path is already absolute, in which case it won’t do anything.

Fix path resolution for the output config value to support absolute paths

---

lib/command/utils.js

Before the change, I could not `codecept run /my/absolute/path`.
`path.join` would always stick the current working directory in front.
More proper path resolution is also simpler, as `path.resolve` will stick
the current working directory if the path is not already absolute.

Fix path resolution on the command line to support absolute paths

---

lib/reporter/cli.js

Just small change so that if both --debug and --steps are specified on the command line it will act as if both were applied. Previously only --steps would appear to take effect.

Make debug taken precedence if specifed with steps

---

lib/command/utils.js

Make it easier to configure CodeceptJS
- Not include keys in config files / source control
- Run on different browsers via env flags
RE Issue #59

Add in loading config from a JS file

---

lib/command/definitions.js
lib/command/list.js

When generating a step definition file steps.d.ts the custom defined steps (e.g. form custom_steps.js) are not listed.
The PR gets all supported actions and adds them to the definition file as well as to the list command

add custom steps to definition list

---

docs/basics.md
lib/codecept.js

* added teardown method to Codecept class - this checks config for a teardown path the same way as bootstrap, and requires it if present
* call teardown when mocha fires `end` event

Run arbitrary JS code after tests

---

lib/helper/WebDriverIO.js

Following http://webdriver.io/guide/usage/multiremote.html

fix(webdriverio): missing init for multiremote

---

docs/basics.md
docs/quickstart.md

The way it was written implies that it was hard, where you probably mean that it was simple
don't worry, it's a common error for post-soviet English speakers... :wink:

docs/quickstart.md: cross-culture translation fix + fix broken link 

---

lib/helper/WebDriverIO.js

I noticed that attachFile has not been working as expected in the WebDriverIO helper. It seems there is a small bug in the code when using the object returned from findFields. This change should fix it (I've tested it and it's now working as expected).

Fix attachFile on WebDriverIO helper

---

lib/helper/WebDriverIO.js

This adds support for each possible timeouts option in webdriver.io
In your codecept.conf.js you can express it something like:
```
{
...
WebDriverIO: {
url: 'http://localhost:8080',
browser: 'phantomjs',
timeouts: {
implicit: 10000,
'page load': 20000
script: 5000
}
}
}
```

Add support for webdriver.io timeouts

---

lib/command/generate.js

codeceptjs gt does not generate proper file without this, file has no extension. Also config.tests globs like `./test/folder/**/*.js` are not supported without this

fix codeceptjs gt file extension and glob support

---

docs/helpers/WebDriverIO.md
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js

To work with cloud services like browserstack it can be beneficial to control when the session is started and therefore start the session manually.
One case in which this is useful is issue #190. You can set the `desiredCapability.name` and then start the session by executing `this.helpers['WebDriverIO']._startBrowser()` 
As the manual option is set to false by default the behavior doesn't change.

Added option to manually start the browser.

---

bin/codecept.js
lib/command/generate.js
lib/command/init.js
package.json

Fixes #259
Example:
```
Welcome to CodeceptJS initialization tool
It will prepare and configure a test environment for you
Installing to /home/davert/projects/codeceptjs/examples/output
? Where are your tests located? ./test/e2e
? What helpers do you want to use? WebDriverIO
? Where should logs, screenshots, and reports to be stored? ./test/e2e/errorShots
? Would you like to extend I object with custom steps? No
? Do you want to choose localization for tests? English (no localization)
Adding default test mask: ./test/e2e/*_test.js
Configure helpers...
? [WebDriverIO] Base url of site to be tested http://localhost
? [WebDriverIO] Browser in which testing will be performed firefox
Config created at /home/davert/projects/codeceptjs/examples/output/codecept.json
Directory for temporaty output …
```

Generators fix

---

package.json

This PR updates the version of Mocha in order to prevent this [security issue](https://nodesecurity.io/advisories/118).
You can verify this by running [nsp](https://github.com/nodesecurity/nsp).

Updated Mocha version

---

bin/codecept.js
lib/command/run.js
lib/command/utils.js
lib/utils.js

Please let me know if this is ok or if anything needs to be changed.
I think it is vary useful to have different config files for different testing situations. For example, before  the deployment to a cloud env and after.
This could also solve issue #282.

added option to select config file

---

docs/configuration.md
lib/codecept.js

Current behaviour:
- when `bootstrap` is a path to a js file, the file is `require`d. If the file exports a function, the function is called with a callback
Proposed behaviour:
- when `bootstrap` is a path to a js file, the file is `require`d. If the file exports a function, the function is called with a callback
- when `bootstrap` is a function, it's called with a callback
Current behaviour:
- when `teardown` is a path to a js file, the file is `require`d. If the file exports a function, the function is *not* called (inconsistent with the `bootstrap` behaviour)
Proposed behaviour:
- when `teardown` is a path to a js file, the file is `require`d. If the file exports a function, the function is called (consistent with the `bootstrap` behaviour, aside from the callback which is not …

Extend bootstrap/teardown configuration options behaviour

---

lib/helper/SeleniumWebdriver.js

Fixes "Invalid Locator" exception on calling waitForElement method of SeleniumWebdriver helper.

Fix for waitForElement of SeleniumWebdriver helper

---

docs/nightmare.md
lib/helper/Nightmare.js
test/helper/Nightmare_test.js

`restart` option for tests run using nightmare helper. Defaults to
`true`. Setting the option `false` with run all the scenario’s of a
suite in a single browser instance.

Nightmare restart

---

test/runner/list_test.js

`fs.existsSync` will not throw if the file doesn't exist (it would probably not be much use if it did) so an assertion needs to be added to the return value for a meaningful test.

Apply an assertion to existence of definition file

---

lib/codecept.js

Using `join` to attach the configured test path to the project root prevents tests being loaded from an absolute path. Using `resolve` instead allows both relative and absolute paths to be used.
Fixes #361

Use `path.resolve` in favour of `path.join`

---

test/runner/list_test.js

Test fails when run for the first time on a new clone because it attempts to delete a file that does not exist (it is created by the same test).
Additionally the same test is currently failing on the `master` travis build - https://travis-ci.org/Codeception/CodeceptJS/builds/191168878

Ignore errors from trying to delete non-existent file

---

package.json

Previous version installed a pre-commit hook which required a global install of gulp to be present. New version uses the locally installed binary.
See https://github.com/therealklanni/guppy-cli/commit/7ddf899b6943e46a328f79c8d24dbd37f015d7c1 (Note: `guppy-cli` version was updated in `guppy-pre-commit@0.4.0`)

Update guppy-pre-commit version

---

lib/actor.js
lib/event.js
lib/helper.js
lib/listener/helpers.js
lib/reporter/cli.js
test/data/sandbox/fs_test.js
test/runner/interface_test.js

* Fixed async printing for step-by-step output (regression since 0.4.14)
* Added `step.started` event for running sync code before the step
* Removed `_beforeStep` and `_afterStep` dummy methods from Helper class, so they won't be added to promise chain. Nevertheless corresponding hooks can be implemened in custom helpers
Fixes #376 
Fixes #377

Fixed step by step output

---

lib/helper/Nightmare.js
test/data/app/controllers.php
test/data/app/index.php
test/data/app/view/timeout.php
test/helper/Nightmare_test.js
test/helper/SeleniumWebdriver_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js

Hi,
I spotted an issue with the waitFor functions in the Nightmare helper as mentioned in #236. 
In cases where the element you're waiting for takes longer than 30 seconds to appear, the default nightmare timeout is hit. The reason this is happening is that `optionWaitTimeout` isn't valid in Nightmare and was causing it to fall back to it's default of 30 seconds.
I've changed this to correctly set the Nightmare `options.waitTimeout` value. I also removed the /1000 on `waitForTimeout` as Nightmare requires milliuseconds and the functions below are the only place this was being used.
I added a test for for the timeout function on `waitForText`

Fix for Nightmare waitTimeout. Resolves #236

---

lib/interfaces/bdd.js
lib/listener/exit.js
lib/scenario.js

To reproduce create a test suite with beforeAll or beforeEach hooks. Then
run the tests without previously starting selenium/phantomjs. You should see the above error message which is also misleading since the actual error is 
```
[1] Error | Error: Couldn't connect to selenium server
```

Fix 'fullTitle() is not a function' in exit.js

---

lib/helper/Nightmare.js
test/helper/webapi.js

Needed to use 'getAttribute' to grab an attribute from an element - it was just returning 'null' for me otherwise.

Issue with 'grabAttributeFrom' method

---

README.md
lib/utils.js
package.json
test/unit/utils_test.js

Use goatslacker/get-parameter-names to read function parameter names in a more robust way. With this, single-param arrow functions that omit the parentheses do not produce an error anymore.
Fixes #127

Make function parameter name parsing more robust

---

lib/command/run.js

If an error is thrown by the `init` function on startup then the error is caught and the process exits with a zero exit code. This means that CI environments will yield a passing build, when in fact the test runner has suffered a catastrophic error.
Resolve this by exiting with a non-zero code if `init` throws an error.

Exit with non-zero code if init throws an error

---

lib/helper/WebDriverIO.js

Give the ability to not only see how many times an element appears in the DOM but how many times an element is actually visible.
Had to build this function as a custom helper for my project. I believe this should be implemented. Very useful, especially when writing acceptance tests.

Add seeNumberOfVisibleElements

---

docs/configuration.md

The configuration is in a json file not in a js file.

Typo: codecept.js ➡ json

---

lib/interfaces/bdd.js
lib/listener/helpers.js
lib/scenario.js

Passing suite object to event.suite.before/after handlers and helper's _beforeSuite/_afterSuite. Fix #495.

Passing "suite" object to event.suite.before/after handlers

---

docs/webapi/saveScreenshot.mustache
lib/helper/Nightmare.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
test/helper/Protractor_test.js
test/helper/webapi.js

Resolves #522.
-  `saveScreenshot()` - Takes a second argument of `true` to capture full page.
- `_failed` - Updated behaviour to take advantage of new functionality, failed tests now capture the full page.
- Documentation updated to reflect new functionality.
- Unit tests added for new functionality.

Expand saveScreenshot() functionality

---

docs/helpers/Nightmare.md
lib/helper/Nightmare.js
translations/it-IT.js
translations/pl-PL.js
translations/pt-BR.js
translations/ru-RU.js

Currently the Nightmare helper exposes electron's `sendInputEvent`, but only for key presses. This PR passes `sendInputEvent` through to the Nightmare helper so that in tests you can trigger mouse events (move, drag, mousedown, etc) at specific x/y coordinates, like so:
`
I.triggerMouseEvent({ type: "mouseDown", x: 100, y: 100, button: "left" });
I.triggerMouseEvent({ type: "mouseMove", x: 200, y: 200, button: "left" });
I.triggerMouseEvent({ type: "mouseUp", x: 200, y: 200, button: "left" });
`

Added method to nightmare helper to trigger electron mouse events

---

docs/advanced.md

- make the config consistent 
- reorder the options so that `--all` is top of the list. My assumption but this is probably the most common usage
- add `sh` to code blocks
- fix typo

docs: tidy up the advanced usage

---

lib/helper/WebDriverIO.js

Hi folks!
I found issue and tries to fix it, please, have look.
I am a little bit new in JS and may do it in a wrong way.
Thank you

#573 I.seeNumberOfVisibleElements() throws an error 'locator is not defined' 

---

lib/step.js

Error.captureStackTrace() call in Step consturctor causes
Step.prototype.toString() to be called when step.args is not
initialized yet. This happens on node.js 7+ when
source-map-support is installed.
Fixes #576

Fix TypeError when using babel-node or ts-node on node.js 7+

---

lib/helper/Nightmare.js

Fix 
`Error: .evaluate() fn should be a function` in after block for Nightmare when `restart:false`

Nightmare restart fix

---

lib/command/run.js

fs.mkdirSync fails if config.output has subdirectories

Use mkdirp to create output directory

---

docs/configuration.md

It should be capital 'F' instead of 'f' since the #387

Fix the "waitForTimeout" typo in configuration.md

---

docs/mobile.md
lib/helper/Appium.js
test/helper/Appium_test.js

To have one test for mobile and web app.
* added `runInWeb` method to execute code only in web
* added `web` locator type similarly to `android` and `ios`

Web specific locators for Appium

---

docs/acceptance.md
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/helper/clientscripts/nightmare.js
test/data/app/view/form/wait_clickable.php
test/helper/SeleniumWebdriver_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js

* fixed returning promise in `defineTimeout`
* fixed respecting context in `click`, `doubleClick`, `checkOption`
* added context test for `click`
* SmartWaits introduced. [What are SmartWaits](http://codeception.com/docs/03-AcceptanceTests#SmartWait)
If locator is defined and element is expected on page, we can wait for few more seconds before failing a test.
```js
I.click('#click');
I.click('Home', '#nav');
I.seeElement('#user');
```
Doesn't work with wide scope locators like:
```js
I.click('Hello');
```
Smart wait is disabled by default.

Smart Waits

---

lib/helper/WebDriverIO.js

Fix misprint in smart wait log message -
[SmartWait] Locating //*['test'] in **undefined**

Fix misprint in smart wait log message

---

docs/configuration.md

I was looking for this option on the website and I could not find it. Then I went to Google and I still could not find it. Finally I started looking through Github's issue tracker and I finally found the information I needed in issue #636.
I believe this information is important to have on the configuration page, as it's quite literally in the name.

Add documentation for --config

---

lib/helper/Appium.js
lib/helper/Mochawesome.js
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
lib/interfaces/bdd.js
lib/listener/helpers.js
lib/scenario.js
test/helper/Nightmare_test.js
test/helper/Protractor_test.js
test/helper/SeleniumWebdriver_test.js
test/helper/WebDriverIO_test.js

What is in this PR:
* Fix https://github.com/Codeception/CodeceptJS/issues/401
* Add more detailed error messages for Wait methods for Nightmare
* Fix adding screenshots to Mochawesome in Nightmare
* Fix unique screenshots names in Nightmare
* Fix Mochawesome context for failed screenshots. At this moment you have to put html report on the same folder, where you store screenshots
* Fix CodeceptJS work with hooks in helpers. Now we will finish codeceptJS correctly, if some errors appears in helpers hooks
* If we receive selenium grid error when use `restart:false`, then we will create a new session for next test
* Now CodeceptJS will create screenshots for failed hooks from Feature file
* Fix https://github.com/Codeception/CodeceptJS/issues/639
* Fix …

Nightmare re-inject scripts

---

lib/interfaces/bdd.js

Fix https://github.com/Codeception/CodeceptJS/issues/665 - Retries not working when using .only

fix retries when set only

---

docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/SeleniumWebdriver.md
docs/helpers/WebDriverIO.md
docs/webapi/waitUntilExists.mustache
docs/webapi/waitWhileElement.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/SeleniumWebdriver.js
lib/helper/WebDriverIO.js
test/data/app/controllers.php
test/data/app/index.php
test/data/app/view/index.php
test/data/app/view/spinner.php
test/helper/webapi.js

Hi, 
as described in the issue [waitWhileElement](https://github.com/Codeception/CodeceptJS/issues/682) I was trying to replicate a feature I was used to. I hope to have covered everything from helpers to docs update to tests coverage.
I hope it can be a useful feature. I often have to wait random amount of time due to slow DB, high loads, different environments to be tested, usually some graphical elements disappears (modals or spinner).
Best regards,
Karoly

waitWhileElement

---

docs/acceptance.md
lib/helper/WebDriverIO.js
test/acceptance/within_test.js
test/data/app/controllers.php
test/data/app/index.php
test/data/app/view/iframe_nested.php
test/helper/Nightmare_test.js
test/helper/SeleniumWebdriver_test.js
test/helper/WebDriverIO_test.js
test/helper/webapi.js

Adding support for setting nested iframes (i.e. as an array) to the WebDriverIO.
The application that I am testing makes heavy use of iframes, and overall WebDriverIO handles iframes better than Nightmare (though more on that later).
* Within block now accepts nested frames when using the WebDriverIO Helper. Previously only the Nightmare Helper was supported.
* Changed the default window size for the Helper tests because the tab tests were failing because the clickable element was "off screen"
* Fixed acceptance test cases which were failing in the Nightmare Helper because Nightmare has problems if the any further navigation (i.e. clicking on a link) is done from within an iframe.
Here is the example Scenario taken out of the `./test/acceptance/within_test.js` which shows the usage. …

WebDriverIO nested iframe support in the within block

---

lib/codecept.js

Prevent against missing config parameters when running codecept manually.  Fix #720

[Fix] Prevent against missing config parameters

---

docs/configuration.md
lib/container.js
test/data/dummy_page.js
test/unit/container_test.js

Currently `config.includes` expects a map with `require` paths as values. This change allows providing object instances as well, e.g.:
```
exports.config = {
includes: {
loginPageObject: './load/me/from/here',
homePageObject: new HomePageObject()
}
}
```

Allow providing arbitrary objects in config includes

---

lib/helper/REST.js
test/rest/REST_test.js

Closes #784. I linked this locally and ran it against my [reproduction repo](https://github.com/alexashley/codecept-headers) and everything looked good. The root cause was the assignment in the constructor causes the default headers to be mutated with every `haveRequestHeaders`.
The downside is that any tests that relied on this behavior are now broken (possibly including any `Before` hooks, but I haven't tested this).

Prevent REST helper from mutating default headers 

---

lib/helper/REST.js

Using haveRequestHeaders before sendPostRequest give us an empty header type.

Fixing the issue #790

---

.travis.yml
docs/acceptance.md
docs/pageobjects.md
lib/container.js
lib/recorder.js
lib/scenario.js
test/data/helper.js
test/data/sandbox/codecept.testscenario.json
test/data/sandbox/testhooks_test.testhooks.js
test/data/sandbox/testscenario_test.testscenario.js
test/runner/codecept_test.js
test/unit/scenario_test.js

Goals:
User benefits, when using async await:
if you want to use `grab` methods in pageObject, you have to create generator function in pageObject and then call this function with specific `yield*` in scenario
e.g.:
```
// pageObject:
goToTestPage: function* () {
const url = yield I.grabTextFrom('mylocator');
I.amOnPage(url);
}
// in Test:
Scenario('test', function* (myPageObject) {
yield* myPageObject.goToTestPage()
});
```
because of this `yield`'s tests will look ugly. And also you have to remember is your function in pageObject a generator or not.
With async/await you should pass await only in case, when you want to get returned value.
e.g.:
```
// pageObject:
async goToTestPage() {
const url = await I.grabTextFrom('mylocator');
I.amOnPage(url);
}
// in Test:
Scenario('test', …
```

Async await support

---

.circleci/build.sh
.circleci/config.yml
.circleci/test.sh
lib/utils.js
test/helper/AppiumWeb_test.js
test/helper/Appium_test.js
test/helper/Nightmare_test.js
test/helper/Protractor_test.js
test/helper/SeleniumWebdriver_test.js
test/helper/WebDriverIO_test.js
test/rest/ApiDataFactory_test.js

#747 introduced dockerized test environment for easier usage in development. However TravisCI still use non-dockerized way of running it. Also Docker is fun and I really want to have Appium tests working in emulator :D 
- builds against 3 node versions instead of 2 (6.9.5, 8.9.1 and 9.2.0)
- Running acceptance tests (we skip them on travis)
- Because of building docker containers and my lack of experience with optimizing it build takes a bit longer than TravisCI (~14min vs ~10min). However for one more node version and additional acceptance specs I'd say it's not bad for first version :)
@DavertMik I have two WebDriverIO exmaples failing on CircleCI unfortunately, I wasn't able to reproduce it locally and it also used to work OK there - I have no idea yet what is going on here :D   If you …

Circle ci: dockerized tests

---

lib/step.js
test/unit/steps_test.js

undefined args in test break it.
example:
Scenario.only('test', (I) => {
let b;
I.assertEqual(b, 'undefined');
});
expected:
```
@Test --
test
• I assert equal undefined, "undefined"
✖ FAILED in 7ms
-- FAILURES:
1) @Test: test:
undefined == 'undefined'
Scenario Steps:
- I.assertEqual(undefined, "undefined") at Test.Scenario (tests/test.js:12:5)
```
actual:
```
@Test --
test
✖ FAILED in 1ms
-- FAILURES:
1) @Test: test:
Cannot read property 'toString' of undefined
```
This PR will fix the issue

fix displaying undefined args in output

---

lib/helper/Appium.js
lib/helper/WebDriverIO.js

`xpathLocator()` in WebDriverIO.js take too long time, and locator ~ does not need it, so be the 1st commit.
JS code write once run on Android, iOS and Web by [react-native](https://github.com/facebook/react-native) and [react-web](https://github.com/flyskywhy/react-web), now test case with locator ~ write once run on them too, so be the 1st and 2nd commit.

Increase ~ considerable speed in Appium and support ~ with aria-label in WebDriverIO

---

lib/helper/WebDriverIO.js

Test case with locator ~ now can write once run on Android, iOS and Web with #728 , but if write I.runOnIOS() I.runOnAndroid() or I.runInWeb() in test case, then we also need a [reactweb_helper.js](https://github.com/flyskywhy/noder-react-native/blob/bdbaf35e5ab05b7de9d8c6ccb370a21827eb1424/e2e/helpers/reactweb_helper.js) required in [codecept.conf.js](https://github.com/flyskywhy/noder-react-native/blob/bdbaf35e5ab05b7de9d8c6ccb370a21827eb1424/codecept.conf.js) , if this PR is accepted and publish a new version, then the reactweb_helper.js is not needed.

placeholder for ~ locator only test case write once run on both Appium and WebDriverIO

---

docs/acceptance.md
docs/mobile.md
docs/nightmare.md
docs/puppeteer.md
lib/helper/Puppeteer.js
lib/scenario.js
lib/utils.js

* Docs for puppeteer
* Improved other guides
* Some refactoring inside scenario

Puppeteer docs

---

lib/command/run-multiple.js

The name of the report file for multiple runs is always report.xml. CI/CD Environments like Jenkins need unique names to recording test results

Add browser name to report file for multiple run

---

lib/step.js

Current output for array of objects:
[[object Object],[object Object]]
This change will display array of objects correctly, e.g.:
[{"myfar": "foo"},{"codeceptjs": "is the best"}]

Better arrays humanize

---

lib/helper/WebDriverIO.js

- Useful for further parsing and/or validations

Add grabBrowserUrl to WebDriverIO

---

docs/webapi/uncheckOption.mustache
lib/helper/WebDriverIO.js
translations/pt-BR.js

PR for this issue: https://github.com/Codeception/CodeceptJS/issues/853
Code is extremely similar to checkOption(). I included docs but not tests.

Implements uncheckOption in WebDriverIO

---

lib/helper/REST.js

- Use case: When several requests with different headers are sent within the same scenario, the **_resetHeaders: true_** within the config is not useful
`// if payload object was ---> payload = { "one": "The default", "two": false};`
`// when this was sent to a POST, the request object was converted it into:`
`// <uri>?one=The%20default&two=false`

Support JSON objects as payload within REST

---

lib/container.js

We use private npm registry to share custom helpers between several projects.
These changes will give ability to require custom helpers from node_modules

add ability to require helpers from node_modules

---

.circleci/config.yml
CONTRIBUTING.md
test/docker-compose.yml

- Fix broken command to execute CircleCI tests
- Add info about what tests and how are run on various CI services we use
- Remove Node 6.9.5 from CircleCI config
Successful Circle build for my fork: https://circleci.com/gh/jploskonka/CodeceptJS/tree/circleCI-fix

Fix CircleCI, update Contributing.md about CI services

---

lib/helper/Puppeteer.js

Hi, I saw issue #889 and #891 try to fix it.
But the solution is incorrect.
Base on the puppeteer [API](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-consolemessage) and [code](https://github.com/GoogleChrome/puppeteer/blob/cb684ebbc4de271c7f2187f4e52c0b3a83cc0122/lib/Page.js#L1032-L1064).
This object only have get method. And return value of `args()` is Non-nullable.
So I fix the code to align the API.
I have tested on my test case (encounter issue #889 before), and it works fine now.

Fix the way to use puppeteer console message

---

docs/helpers.md

Correct: https://codecept.io/helpers/#webdriverio-example
Wrong: https://codecept.io/helpers/#hook-usage-examples
Indentation is the only difference i noticed between those blocks of text.

Remove unnecessary indentation breaking formatting

---

lib/helper/Puppeteer.js

Fixed a bunch of issues with the Puppeteer helper.
- Exit gracefully after a test completes
- Add ability to set `user-agent` via config
- Add `keepCookies`,`keepBrowserState` and `restart` (feature parity between helpers)
Updated the documentation, but haven't added any tests for these. Wanted to fix the double-tab issue during startup, but see there's another PR already open for that from @reubenmiller.

Puppeteer fixes

---

lib/helper/REST.js
test/data/rest/db.json
test/rest/REST_test.js

The latest changes from 1.1.2 are not working anymore for sendPostRequest .. if you are trying to send an object it's trying to convert it to string but the request itself is not successful. 
So with this change you can pass JSON object and also form urlencoded payload types.
example:
let payload = { username: "user1", password: "xxx" };
let payload2 = 'username=user1&password=xxx';
extra unit tests added + fixed old ones

requests to API fix

---

lib/data/context.js
test/data/sandbox/ddt_test.ddt.js

* Support plain arrays again in the Data Driven Tests. (Fixes #920)
Plain arrays worked in v1.0.1 but broke some time later.
The docs (advanced.md) already mention that `Data sets can also be defined with array, generator, or a function.`. So no need to update them.
Here is the example which now works again.
```js
Feature('ehm');
// Case 1: Allow plain arrays
Data(['1', '2', '3']).Scenario('data table test array', (I, current) => {
I.amOnPage('/');
console.log(current);
});
```

[Data Driven Tests] Accept plain arrays (regression fix)

---

lib/interfaces/bdd.js

As mentioned in https://github.com/Codeception/CodeceptJS/pull/820#issuecomment-352279338
Now test object has injectDependencies method that allow to inject custom deps to test:
usage:
```
require('./common').forEach((t) => t.injectDependencies());
```

add injectDependencies method

---

lib/helper/Puppeteer.js

Since [click](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Puppeteer.js#L625-L641) return the value from `proceedClick`.
I think `proceedClick` should return waitForAction just like other actions.

Puppeteer helper, proceedClick should return _waitForAction

---

lib/helper/Puppeteer.js
lib/interfaces/bdd.js
test/helper/webapi.js

* Fixing #932. The TEXTAREA item wasn't being cleared because the innerhtml attribute was being cleared instead of the value attribute.
* Lint fix
* [text area value vs innerhtml](https://stackoverflow.com/questions/5314186/javascript-get-textarea-input-via-value-or-innerhtml)

[Bugfix #932] Clear value attribute instead of innerhtml for TEXTAREA elements

---

lib/helper/Nightmare.js

* Initialise Nightmare (in _startBrowser) on a blank page
* Fixes following issues, #786 & #898 
If a scenario fails before `I.amOnPage` is called, then the subsequent call to the _failed hook in the Nightmare helper, tries to take a screenshot of the browser. Before a screenshot is taken the height and width of the browser is retrieved using `browser.evaulate`, however if Nightmare has not had `.goto` called on it, then `.evaulate` will timeout.

[Nightmare|Bugfix] Init browser with about:blank so browser does not hang if scenario fails before I.amOnPage() is called

---

docs/webapi/pressKey.mustache

Fixed the typo in the source file rather than in the generated markdown file (as per suggestion in PR #916).

Fixed typo in pressKey function description

---

lib/helper/WebDriverIO.js

Assertion removed from grabNumberOfVisibleElements method to accept also zero visible elements.
- this method should return also value if no elements are displayed on the page
- issue was discussed also on slack channel

grabNumberOfVisibleElements to return also 0 visible elements

---

bin/codecept.js
docs/commands.md
lib/command/definitions.js
test/runner/list_test.js

* Add support for custom codeceptjs configuration files when using the `codeceptjs def` command. Usage `codeceptjs def --config /path/to/config.json`. #879

Add --config option to the codeceptjs def command

---

docs/webapi/grabBrowserUrl.mustache
docs/webapi/grabCurrentUrl.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/WebDriverIO.js
test/helper/webapi.js

* Adding support for `I.grabCurrentUrl` to all helpers. #952 
* Deprecated `I.grabBrowserUrl` in favour of `I.grabCurrentUrl` in WebDriverIO Helper

[Helpers] Adding grabCurrentUrl to Puppeteer, Protractor and Nightmare

---

lib/helper/Nightmare.js

* Changing detection of the Nightmare visibility detection to reflect that of the native Nightmarejs implementation (i.e. using the `offsetWidth` and `offsetHeight` attributes instead of `offsetParent`. Proposed in #614
* [Jquery note](https://makandracards.com/makandra/1339-check-whether-an-element-is-visible-or-hidden-with-javascript)
* [Nightmare implementation](https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L72)

[Nightmare] Changed visibility detection

---

lib/helper/Puppeteer.js

Fixing bug where a non-existant functions were being called when trying to clear the cookies and localstorage. Introduced with the Puppeteer restart = false browser logic. #954

[Puppeteer] Fixing function calls when clearing the cookies and localstorage

---

docs/webapi/dontSeeElement.mustache
docs/webapi/waitForInvisible.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/WebDriverIO.js
test/data/app/view/form/wait_detached.php
test/data/app/view/form/wait_invisible.php
test/helper/webapi.js

* Changed behaviour of the `I.waitForInvisible` so that it treats a nonexistent DOM element the same as an invisible DOM element. The behaviour is now the same across all of the Browser Helpers. #943 
* Added test cases for `I.waitForDetached` and changed the error messages so that are the same across the Helpers.
* Thanks to @JLRishe who originally created a similar PR #950 and originally pointed out this problem. Unfortunately I gave some misguided information which lead him on a wild goose chase and caused confusion from the main Contributors (my apologies). @JLRishe Please do not let this discourage you from future PRs :)

[Helpers] Changes to I.waitForInvisible behaviour and test cases for I.waitForDetached

---

docs/helpers.md
lib/codecept.js
lib/command/run.js
lib/helper.js
lib/listener/helpers.js
test/acceptance/codecept.Nightmare.js
test/acceptance/codecept.Puppeteer.js
test/acceptance/codecept.WebDriverIO.js
test/acceptance/event_test.js
test/acceptance/within_test.js
test/data/helper.js
test/data/sandbox/codecept.testevents.js
test/data/sandbox/eventHandlers.js
test/data/sandbox/testevents_test.testevents.js
test/runner/codecept_test.js
test/runner/interface_test.js

* Added event.all.before and event.all.after events. #604 
* Added unit and acceptance tests for events
* Adding new Helper hook (`_passed`) which is triggered after a passed tests (similar to _failed). #764 
These two events are already documented however there were not being emitted.

[Events] Added event.all.before and event.all.after events

---

docs/advanced.md
docs/configuration.md
docs/hooks.md
lib/command/run-multiple.js
lib/event.js

* New `bootstrapAll` and `teardownAll` hooks which are used when running the `run-multiple` command. The `bootstrapAll` hook is trigger before any test suites have started, and `teardownAll` is triggered once all of the suites have finished. The two hooks also have event equivalents; `multiple.before` and `multiple.after`. #957, #678 
Previously only `bootstrap` and `teardown` hooks were available. When using the `run-multiple` command, the `bootstrap` and `teardown` hooks trigger every time a suite starts and finishes. This makes them ill suited to perform general setup and cleanup tasks when using the [Multiple Execution](https://codecept.io/advanced/#multiple-execution) command.

[Multiple-Run] Adding new bootstrapAll and teardownAll hooks

---

lib/helper/Nightmare.js
test/helper/Nightmare_test.js

**[Nightmare]**
* Check if browser is already at given url in `I.amOnPage`. If so then don't navigate to it as it will cause an error in nightmare. Fixes #713 
* Using nodejs url.resolve rather than straight string concatenation so it is inline with the webdriverio behaviour.

[Nightmare] Prevent I.amOnpage navigation if the browser is already at the given url

---

lib/utils.js
package.json
test/data/sandbox/testscenario_test.testscenario.js
test/runner/codecept_test.js

Current library doesn't support syntax like this:
```
Scenario('test', async I => {
...
});
It returns error `Error: Object of type async I is not defined in container`
```
With updated library this will be fixed

change library for get params

---

lib/interfaces/bdd.js
package.json
test/data/helper.js
test/data/sandbox/codecept.testhooks.different.order.json
test/data/sandbox/testhooks_test.testhooks.different.order.js
test/data/sandbox/testhooks_test.testhooks.js
test/runner/codecept_test.js

Allow `AfterSuite` and `After` test hooks to be defined after the first Scenario. This allows for a more flexible and natural placement of these two test hooks. Previously these two hooks needed to be placed before the first `Scenario`. Fixes #857
```js
const assert = require('assert');
Feature('My new feature');
BeforeSuite((I) => {
console.log('Before suite');
});
Before((I) => {
console.log('Before each test');
});
Scenario('Test Case 1', (I) => {
I.amOnPage('/');
});
Scenario('Test Case 2', (I) => {
I.amOnPage('/');
});
After((I) => {
console.log('After each test');
});
AfterSuite((I) => {
console.log('Bfter suite');
});
```

[AfterSuite|After] Allow AfterSuite and After test hooks to be defined after the first Scenario

---

lib/helper/WebDriverIO.js
test/helper/WebDriverIO_test.js

* [WebDriverIO] Utilise the inbuilt WebDriverIO dragAndDrop function instead of doing mouse moves and clicks manually. Fixes #822
* This still does not work with Firefox

[WebDriverIO] Use inbuilt dragAndDrop function

---

lib/helper/Protractor.js
lib/helper/Puppeteer.js
test/helper/webapi.js

* Fixed bug with `I.click` when using an object selector with the xpath property. It only affected the **Puppeteer** and **Protractor** helpers. Fixes #989
* Added tests for all browser helpers to check for this condition
```js
Scenario('I click using custom xpath selector', (I) => {
I.amOnPage('/');
I.click({
xpath: '(//*[@class])[1]',
});
});
```

Fixing I.click so it accepts an explicit xpath selector. Fixes #989

---

lib/helper/Protractor.js
test/helper/webapi.js

* `I.seeAttributesOnElements` and `I.seeCssPropertiesOnElements` were incorrectly passing when the attributes/properties did not match.

[Protractor] Fixing bug with I.seeAttributesOnElements and I.seeCssPropertiesOnElement

---

lib/helper/Puppeteer.js

Puppeteer's `page.url()` ignores hash. This is an attempt to fix it in order to maintain consistency with other helpers.

Proper hash handling for Puppeteer URL

---

lib/command/definitions.js

Added Data, xData, xScenario definitions.
Added options for actor and Feature functions.
Rewrote declarations to "declare function ..." style to allow use of overloading for Scenario and xScenario. Now it allow use both with or without opts parameter.
Don't found variant to allow it with code style which has already been used. Therefore, rewrote all such declarations in single style.
Added declaration for codecept_helper, to remove errors in custom helpers. Maybe there are other ways to solve this, please, tell me if it's true. I'll remove it.

Updated typescipt definitions.

---

lib/command/definitions.js
package.json
test/unit/assert/equal_test.js

"npm test" did not use tests in nested directories, for example "test/unit/assert"
see https://mochajs.org/#the-test-directory
Fixed test according to linter rules.

Enable test runner for nested test directories

---

docs/advanced.md

- avoid `bash: !.*@smoke4: event not found` errors

added quotes for grep test groups

---

lib/helper/WebDriverIO.js

Fix typo (I think), made in [1049](https://github.com/Codeception/CodeceptJS/pull/1049/files#diff-c873b3f20f4ccf0b26a50fbebbf074d6R359) pull request.
Now WebDriverIO does not start driver/browser session after test completion.
#1069

fix-1069: fix WebDriverIO browser opening after tests with option restart=false

---

lib/command/run-multiple.js

This should address related issues #1084 and #1111 for which root cause was invalid output directory path on Windows due to colon character being present (i.e. `parallel:...`).  This was causing `mkdirp` module to infinitely recurse, leading to max call stack size error.
Proposed solution uses pre-existing `clearString()` function in `lib/utils.js` to replace invalid characters in string.

Fixing invalid output directory path for run-multiple

---

lib/container.js

I don't really see, why this wrapper would be needed. It silently catches any
errors thrown by async functions. Even if a rejected promise is being
returned. This is very different from just returning a promise. In case
it's rejected, the error will bubble up and fail any test.
This fixes #1109 for me.

properly propagate errors in asyncWrapper around async functions

---

docs/helpers/Protractor.md

Protractor needs 'directConnect': true in the config in order to use the 'direct' driver.
Otherwise it keeps trying to talk to the Selenium server.

Add info on using 'direct' Protractor driver

---

lib/parser.js

Methods with only one locator parameter should generate two methods in the interface definition.

Fix #1132 def generation for methods with only one param

---

docs/configuration.md

The configuration example said `includes:` with an additional `s` instead of `include:`.
I also added the actor import.

Fix typo in `include:` configuration, add actor include.

---

lib/locator.js

Context: when using `Locator.clickable.self`, the xpath generated starts with `./self::...`, but the locator was not considered as `xpath` (fallbacking to `css`) so it failed to select the element.

fix: xpath detection fails when it starts with `./`

---

lib/helper/Puppeteer.js

I.executeAsyncScript(function(done) {
done();
});
Will throw Error: Evaluation failed: SyntaxError: Unexpected token (
at __puppeteer_evaluation_script__:8:31

FIx executeAsyncScript Unexpected token ( issue

---

lib/command/generate.js

By using this regexp it will correctly match extensions from `config.test`, that fallow format like `./**/*_test.js`, or `./**/*.test.js`. 
Example on [regexer.com](regexr.com/3vo4k)
Also, forcing `_helper.js` extension in JS world is weird, therefor option to make it `.helper.js` would be nice.

Correctly extract default extension

---

lib/command/run-multiple/chunk.js

if multiple.parallel.chunks param in codecept.conf.js set as environment variable, codeceptjs throw "chunks is neither a finite number or a valid function".
example:
```
multiple: {
parallel: {
chunks: process.env.CHUNKS || 20,
...
}
```

fix multiple.parallel.chunks

---

lib/command/definitions.js

By adding type annotation to `customSteps`, we get hint, that `this` is actually `CodeceptJS.I` and therefore we can do much more, while having some type checks.

Make actor type definition useful

---

lib/plugin/screenshotOnFail.js

Moving to Allure screenshot attaching inside the screenshot try/catch block
If there is an exception saving a screenshot it should not try and add a file that does not exist to the Allure report.

Move Allure screenshot attachment

---

docs/advanced.md
docs/hooks.md
lib/command/definitions.js
lib/interfaces/featureConfig.js
lib/interfaces/gherkin.js
lib/interfaces/scenarioConfig.js
lib/ui.js
test/data/sandbox/features/examples.feature
test/helper/Puppeteer_test.js
test/runner/bdd_test.js
test/unit/bdd_test.js
test/unit/ui_test.js

Changes:
* Groups officially renamed to tags for compatibility with BDD layer
* Test and suite objects to contain `tags` property which can be accessed from internal API
* Fixed adding tags for Scenario Outline in BDD
* Added `tag` method to ScenarioConfig and FeatureConfig:
```js
Scenario('update user profile', () => {
// test goes here
}).tag('@slow');
```
* Added unit tests for ScenarioConfig, FeatureConfig, suite and test definitions

Fixed tags implementation

---

docs/advanced.md

Add more expressive examples for `run-multiple` command.
Move "parallel" section after "multiple", cause the first uses examples of browsers from the second.

Extend browsers description in docs

---

docs/helpers/Puppeteer.md
docs/webapi/clickLink.mustache
lib/helper/Puppeteer.js

Fixes the `click()` method so by default it doesn't trigger a `waitForNavigation()` and instead adds a new `clickLink()` method to trigger a `waitForNavigation()` when clicking an element that should trigger a navigation.

Adds clickLink method to Puppeteer helper

---

docs/plugins.md
examples/codecept.json
lib/plugin/autoDelay.js

While developing a test suite for one of my clients I found useful to put a small delay before and after click and fillField to ensure that page could respond to this actions. Here is a plugin which an easily add delays to your actions.
---
Sometimes it takes some time for a page to respond to user's actions.Depending on app's perfromance this can be either slow or fast.
For instance, if you click a button and nothing happens - probably JS event is not attached to this button yet. Also, if you fill field and input validation doesn't accept your input - maybe because you typed value too fast.
This plugin allows to slow down tests execution when a test running too fast.
It puts a tiny delay for before and after action commands.
```js
"plugins": {
"autoDelay": {
"enabled": true
}
}
```

Created autoDelay plugin

---

lib/helper/WebDriverIO.js

Modern browsers starts to drop out old webdriver syntax.
For example Safari 12 and FF 63 does not support old syntax for timeout setting.
We should use new w3c compatible syntax in such cases
http://webdriver.io/api/protocol/timeouts.html

fix timeouts definition for W3C compatible drivers for WebDriverIO

---

lib/utils.js

Trying to replace the escape character in before_* file name as suspected to cause the issue described here
https://github.com/Codeception/CodeceptJS/issues/1287

Exception in Before block w/ Mocha causes test not to report failure

---

lib/plugin/stepByStepReport.js

add option `output` to stepByStepReport plugin for customize output-directory.
Example:
```
"plugins": {
"stepByStepReport": {
"enabled": true,
"output": "./output/report"
}
}
```

Add option `output` to stepByStepReport plugin

---

lib/command/definitions.js

In order to get auto completion in test files for page objects the type of the page object must not be any in type definitions.

Changed type definition of PageObjects to get auto completion

---

lib/output.js
lib/step.js
test/data/sandbox/within_helper.js
test/runner/bdd_test.js
test/runner/within_test.js

Fix for #1321 
CLI output did not print steps for some types of async and arrow functions.
```
non-async non-arrow braces
Runner: runTest 
✔ OK in 3001ms
non-async arrow non-braces
Test: I 
✔ OK in 2136ms
non-async arrow braces
I am on page "/"
✔ OK in 1814ms
async non-arrow braces
Runner: runTest 
✔ OK in 1814ms
async arrow non-braces
I am on page "/"
✔ OK in 1852ms
async arrow braces
I am on page "/"
✔ OK in 1759ms
```
Also reworked `within` test, cause it used `step` class as logger for strings instead of creating Step.
It broke new logic, as `String` has not `Step`'s `hasBDDAncestor` method.
PS why we add spaces (` `) before literal strings in `Step.humanize()`?
```
// insert a space before all caps
.replace(/([A-Z])/g, ' $1')
```
PS, why spaces are added in the end of cli output? For …

Fix steps output for CLI for async/arrow functions

---

lib/listener/config.js

This fix resolves issue #217, which does not open browser in a shell mode.

Fix Issue #217

---

docs/commands.md

A colon is required between `generate` and the type of object to create

Fix syntax of the generate commands

---

lib/helper/Puppeteer.js

Hello,
With this PR will be possible to use remote chrome instances like https://www.browserless.io/ or docker containers like https://github.com/joelgriffith/browserless.
I saw that currently the project is not mocking Puppeteer and we don't have tests to `_startBrowser`, so I don't know how test it. Should I mock Puppeteer?

Add support to use WSEndpoint on Puppeteer

---

docs/helpers/WebDriver.md
lib/helper/WebDriver.js
package.json

* Update webdriverio package to version 5.2.0.
* Allowing to define timeouts accordingly for Firefox/Safari (fixes #1393)
* Set window size without specifying position at 0x0 coordinates, which are incorrectly evaluated as boolean by Safaridriver.
* Properly clear cookies when no `desiredCapabilites` defined. (fixes #1407)
* Check both W3C WebDriver web element identifier (`element-6066-11e4-a52e-4f735466cecf`) and JsonWireProtocol identifier (`ELEMENT`) when retrieving element id.

Resolve several issues with WebDriver helper.

---

CHANGELOG.md
RoboFile.php
docs/acceptance.md
docs/data.md
docs/helpers/ApiDataFactory.md
docs/plugins.md
lib/helper/ApiDataFactory.js
lib/helper/WebDriver.js
lib/pause.js
lib/plugin/autoLogin.js
lib/plugin/retryFailedStep.js
lib/scenario.js
lib/store.js
lib/utils.js
test/data/rest/db.json
test/rest/ApiDataFactory_test.js

* [**autoLogin plugin**](https://codecept.io/plugins#autoLogin) added. Allows to log in once and reuse browser session. When session expires - automatically logs in again. Can persist session between runs by saving cookies to file.
* Fixed `Maximum stack trace` issue in `retryFailedStep` plugin.
* Added `locate()` function into the interactive shell.
* [WebDriver] Disabled smartWait for interactive shell.

AutoLogin plugin and some important fixes for 2.0.3

---

lib/plugin/autoLogin.js

Prevents from using last user's methods in all cases. E.g. `admin` actually ends up using `inactiveUser`'s login.
```js
plugins: {
autoLogin: {
enabled: true,
saveToFile: false,
inject: 'loginAs', // use `loginAs` instead of login
users: {
admin: {
// methods
},
activeUser: {
// methods
},
inactiveUser: {
// methods
},
},
},
},
```

Fixes users from merging on autoLogin plugin

---

lib/plugin/autoDelay.js

WebDriverIO is deprecated and should be removed from the list when the deprecation notices are removed. For now, both should be supported.

Added WebDriver to autoDelay plugin supported helpers list

---

lib/plugin/allure.js

Good decision will be then when will be added event `test.skipped`.
But this decision faster and lighter.

Skip test in allure-report

---

lib/helper/WebDriver.js
test/data/app/view/form/file.php
test/helper/WebDriver_test.js

Original WebDriver helper's `attachFile()` method could'nt attach file to hidden input element, such as: 
```
<input type="file" id="upload" style="display: none;">
```
Given error was: 
```
Error: element not interactable
(Session info: headless chrome=70.0.3538.77)
(Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.17.9-041709-generic x86_64)
```
This patch will fixed that problem.

Enable Uploading To Hidden Input Element

---

.eslintrc.json
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md
docs/helpers/WebDriverIO.md
docs/webapi/grabAttributeFrom.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js

Fixed this case:
> I have noticed one thing about grabAttributeFrom method: there are 6 elements on a page and I expected grabAttributeFrom to return me an array. Here is my code
I.amOnPage('https://www.mcmakler.de/lp/de/immobilienbewertung'); const src = await I.grabAttributeFrom('.footer-branded div img', 'src'); console.log(src);
but it actually returns the value from the first element and that’s it. The page I am testing is public, so you can see that there are actually 6 elements found using this selector.

fixed the case when there are more than one matched element

---

package.json
test/unit/utils_test.js

This was a bug at `fn-args` library that got fixed with https://github.com/sindresorhus/fn-args/pull/10 . Before upgrading the `fn-args` library the test I added fails with:
```console
1 failing
1) utils
#getParamNames
should handle trailing comma:
AssertionError: expected [ 'I', 'trailing', 'comma', '' ] to deeply equal [ 'I', 'trailing', 'comma' ]
+ expected - actual
[
"I"
"trailing"
"comma"
-  ""
]
at Context.it (test/unit/utils_test.js:18:21)
```
The upgrade fixes that issue:
```console
✓ should handle trailing comma
```

Handle trailing comma at `utils.getParamNames`.

---

docs/hooks.md
lib/command/definitions.js
lib/parser.js
lib/utils.js

Fixed doc to avoid https://codecept.discourse.group/t/boostrap-is-not-a-function-error/64
After #1270 
Also fix a few lines to linter requirements.
@DavertMik, maybe we should add linter run on commit before test run?
And add ~"run linter" line in CONTRIBUTING doc ?

docs: fix bootstrap description for custom runner documentation

---

lib/command/run-multiple.js

`run-multiple` generates some overridden configs based on config file.
The current problem we have is that when we try to override one of the `run-multiple` generated config, it will simply pass down to the child runner and not respecting the `run-multiple` generated configs.
One of the symptoms is that when we override the `tests` config, it will make all runner running the same tests because the chunked config is being overridden.
This PR is to make `run-multiple`generate config based on the overridden version so that when we overrides the setting, it is still respecting the `run-multiple` generated configs.

Make override option in `run-multiple` to respect the generated overridden config

---

lib/command/definitions.js
lib/command/run-multiple.js
lib/command/run.js
lib/parser.js
lib/utils.js
package.json

I trying to write custom runner with custom mochaFactory.
I used `container.append()` for replaced default mocha
```js
codecept.init(testRoot)
container.append({
mocha: MochaFactory.create({}, codecept.opts || {}),
})
```
MochaFactory contains the same code like default MochaFactory and ui.js. Without changed!
But when I run the tests, none of them run!
After debugging I found that deepMerge work incorrectly.
Before merge i have object like:
```js
mocha:
Mocha {
files: [],
options:
{ commands: [],
options: [Array],
_execs: {},
_allowUnknownOption: false,
_args: [Array],
_name: 'collect-only',
_noHelp: false,
parent: [Command],
_description: 'Executes tests',
_argsDescription: undefined,
_events: [Object],
_eventsCount: 17,
config: './tests/user-scenario/configs/puppeteer.config.js', …
```

WIP: Fix deep merge for container.append(). Use lodash.merge()

---

lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
test/data/sandbox/page_slider.html
test/helper/Puppeteer_test.js

1. Fixed url protocol detection for non-http urls.
Now `file://path/to/file`, `ftp://...` and similar is correct fo Puppeteer, Nightmare and Protractor helpers.
Before `https` and `https` have worked only.
2. Fixed test for page slider in `Puppeteer_test.js`
It could not load w3c site and test fails last 2 days.
Now this test use local sandbox html.

Fix url protocol detection for non-http urls

---

lib/command/interactive.js

fix https://github.com/Codeception/CodeceptJS/issues/1414
With Allure plugin, `codeceptjs shell` failed with those errors:
```
TypeError: suite.fullTitle is not a function
```
```
TypeError: suite.tests is not iterable
```
```
TypeError: Cannot read property 'title' of undefined
```
These are occured by lack of parameters on `event.emit()`.
```
event.emit(event.suite.before, {}); // should have fullTitle() and tests
event.emit(event.test.before); // should have title
```
This PR fixes those errors.

Fix errors on using interactive shell with Allure plugin

---

lib/plugin/stepByStepReport.js

Fix two problems: 
That's simple :innocent: 
When using session, the console log is colored with ANSI escape character.
However, it should not be displayed in the report.
before | after
--- | ---

Enable to use Step-by-step Report for WebDriver Plugin

---

lib/helper/WebDriver.js
test/helper/WebDriver_test.js

Before 2.0, grabHTMLFrom returned an array of strings with innerHTML of the set of matched elements. After 2.0, it returns the outerHTML of the first element. That it returns the outerHTML is a bug as documentation says that it returns innerHTML and other helpers also return innerHTML. 
That it returns an array instead of just the first element is similar to the usage of getHTML of webdriverio, where you have a $(selector).getHTML(false) to return innerHTML for a set of matches. And it is very useful when you need to test multiple elements (e.g. "ul > li"). And if you only need the first result, you can simply use destruction (like "const [html] = await I.grabHTMLFrom(...);" ). Last but not least, an upgrade to 2.0 would not break the grabHTMLFrom function.

Webdriver: grabHTMLFrom returns array of innerHTML from the set of matched elements

---

lib/command/run-multiple.js

Fix for #1346;
global variable with path was not defined for `run-multiple`, so `bootstrapAll` and `teardownAll` were run with error
```
TypeError: Path must be a string. Received undefined
at assertPath (path.js:28:11)
at Object.join (path.js:1236:7)
at module.exports (CodeceptJS/lib/hooks.js:8:31)
at Command.module.exports (CodeceptJS/lib/command/run-multiple.js:67:3)
```

Fix bootstrapAll and teardownAll launch with path as argument

---

lib/helper/WebDriver.js
lib/helper/WebDriverIO.js

Add 4th argument to `waitUntil` in `WebDriver` and `WebDriverIO`
It defines interval time between conditional checks.
https://webdriver.io/docs/api/browser/waitUntil.html
http://v4.webdriver.io/api/utility/waitUntil.html

Webdriver. Add possibility to define conditional checks interval for waitUntil

---

docs/hooks.md
lib/command/run-multiple.js
test/data/sandbox/bootstrapall.function.js
test/data/sandbox/bootstrapall.object.js
test/data/sandbox/codecept.bootstrapall.multiple.code.js
test/data/sandbox/codecept.bootstrapall.multiple.function.js
test/data/sandbox/codecept.bootstrapall.multiple.object.js
test/data/sandbox/teardownall.function.js
test/data/sandbox/teardownall.object.js
test/runner/run_multiple_test.js

`bootstrapAll` and `teardownAll` were not called, if created as `bootstrap` and `teardown` in object, like:
```
module.exports = {
"bootstrapAll": () => {...},
"teardownAll": () => {...},
};
```
Before this fix, to call `bootstrapAll` and `teardownAll` from object, object should be defined this way:
```
module.exports = {
"multiple.bootstrap": () => {...},
"multiple.teardown": () => {...},
};
```
It's not obvious and it is not described anywhere in docs.
Fixed and wrote some tests for `bootstrapAll`/`teardownAll`.

Fix bootstrapAll and teardownAll calls from exported object

---

lib/data/context.js

Fixed storing all data in the test instance.
Previously, the instance had only the latest data, like:
```json
"opts": {
"data": {
"data": {
"fieldValue": "admin"
}
}
}
```
Now:
```json
{"fieldVelue":"admin"}
{
"title": "При смешанном вводе не форматирует. Корректно форматирует при блюре @FBCARDS-654 | {\"fieldValue\":\"admin\"}",
"body": "",
"async": true,
"sync": false,
"timedOut": false,
"pending": false,
"type": "test",
"tags": [
"@FBCARDS-654"
],
"file": "Properties/dontPrettifyOnInput.test.js",
"inject": {
"current": {
"fieldVelue": "admin"
}
},
"steps": [],
"parent": "#<Suite>",
"ctx": "#<Context>",
"opts": {
"data": [
{
"fieldValue": "davert"
},
{
"fieldValue": "admin"
},
{
"fieldValue": "admin"
}
]
}
}
```
Test:
```js
Data(function * () {
yield { fieldValue: 'davert' }
yield { …
```

Fixed storing all data in the test instance.

---

lib/helper/WebDriver.js

`undefined` was assigned to `hostname` config options,
So cloud provider host detection was broken: 
object 
```
{"protocol":"https","hostname":"hub-cloud.browserstack.com","port":443}
```
was rewrited by incorrect object field:
```
{ ...,
hostname: undefined,
...
}
```

WebDriver: Fix cloud provider hostname rewrite

---

lib/helper/WebDriver.js

`I.saveScreenshot(filename, fullPage)` with `fullPage = true` takes full page screenshot, but doesn't preserve or restore original windowsize. 
This PR will fix it.

Restore original window size when taking full size screenshot

---

lib/plugin/puppeteerCoverage.js

After creating your beautiful tests, you'll eventually get asked what is your code coverage.
This plugin will dump the code coverage for you.
You'll need to convert the coverage to istanbul readable coverage and run istanbul to create the report.
(I'll provide my script that does exactly that when I get time to clean it up for public use).

New puppeteer plugin to dump code coverage

---

lib/data/context.js
lib/data/dataScenarioConfig.js
test/unit/data/ui_test.js

Currently the `ScenarioContext` functions `throws()`,` fails()`, `retry()`, `timeout()`, `config()` and `tag()` are not supported when running data driven scenarios with `Data()`. The pull request would make them available for data driven scenarios and apply them to all scenarios within the data table.

Enable ScenarioContext functions for data driven tests

---

docs/webapi/rightClick.mustache
lib/helper/Nightmare.js
lib/helper/Protractor.js
lib/helper/WebDriver.js
lib/helper/clientscripts/nightmare.js
test/data/app/view/form/rightclick.php
test/helper/webapi.js

rightClick now works similarly for WebDriver, Nightmare, Protractor, Puppeteer
And added tests

Implemented right click for WebDriver, Nightmare

---

lib/helper/WebDriver.js

This PR updated some deprecated method names when running against wdio v5 with firefox for instance and will fix the issue in https://github.com/Codeception/CodeceptJS/issues/1524
- https://webdriver.io/docs/api/element/getTagName.html
- https://webdriver.io/docs/api/element/getAttribute.html
- https://webdriver.io/docs/api/element/getValue.html

WDIO v5 - Updated some deprecated methods

---

lib/interfaces/gherkin.js
lib/scenario.js
lib/ui.js
test/unit/bdd_test.js
test/unit/scenario_test.js

typescript may not mark async functions correctly so just await everything

---

docs/plugins.md
lib/command/definitions.js
lib/parser.js
lib/plugin/stepByStepReport.js
lib/utils.js

By this reported https://github.com/Codeception/CodeceptJS/issues/1494 I found out that:
- The screenshot to attach to allure for failed test cases is already handled in `screenshotOnFail.js`
```
const allureReporter = Container.plugins('allure');
if (allureReporter) {
allureReporter.addAttachment('Last Seen Screenshot', fs.readFileSync(path.join(global.output_dir, fileName)), 'image/png');
}
```
so, we don't need to handle it again in `stepByStepReport.js`
```
const allureReporter = Container.plugins('allure');
if (allureReporter && (step.status !== 'success')) {
output.plugin('stepByStepReport', 'Adding screenshot to Allure');
allureReporter.addAttachment('Screenshot', fs.readFileSync(path.join(dir, fileName)), 'image/png');
}
```
this will lead to 
- duplicate screenshots on allure …

fixed no screenshots on passed cases allure

---

docs/helpers/Puppeteer.md
docs/webapi/downloadFile.mustache
lib/command/definitions.js
lib/helper/Puppeteer.js
lib/parser.js
lib/utils.js
test/helper/Puppeteer_test.js

- Introduce download action for puppeteer.
- test is added.
This is basically to click a button, link in AUT to download file. This file is downloaded to output folder. And this function makes sure download function is working on the application.
For instance: you have a web application that let users can upload/ download their images, documents. By using `I.downloadFile('locator')`, if the file is downloaded to output folder, then downloading function is working. Moreover, after the file is downloaded, we can do further check with downloaded file if we want, like parsing the pdf and checking contents, etc.

adding downloadFile action for puppeteer

---

lib/plugin/allure.js

See [Allure Screenshot Plugin](https://github.com/allure-framework/allure2/blob/master/plugins/screen-diff-plugin/README.md)

Allure/ Add ability enable screenshotDiff plugin

---

lib/helper/Appium.js
lib/locator.js

Fix error `TypeError: locator.stringify is not a function` for iOS app testing
https://stackoverflow.com/questions/54992632/codeceptjs-locator-stringify-is-not-a-function-error-while-running-codecept-with/
I think it will not fully fix error.
fuzzy selectors are not processed for iOS app testing

fix locator's simplify call, fix toXPath function

---

lib/command/definitions.js
lib/helper/WebDriver.js
lib/parser.js
lib/utils.js
test/helper/WebDriver_test.js

**What are you trying to achieve?**
I want to test if the exact text "Authentication failed." appears in the p subelement of
```
<div class="ui error message">
<div class="content">
<p></p>
</div>
</div>
```
**Let's say now there is no value in p.**
`So I.seeTextEquals("Authentication failed.", ".error.message"); should fail.`

fixed issue 1561

---

lib/helper/WebDriver.js

WebDriver helper's method `seeElement`.
`browser.isElementDisplayed(elemId)` will be  deprecated.
Changed to `elem.isDisplayed()`
https://webdriver.io/docs/api/element/isDisplayed.html
#1518
This PR fix WDIO call, but there are WDIO error, due to not implemented driver's API:
https://github.com/webdriverio/webdriverio/pull/3601

WebDriver (WDIO 5): Change isElementDisplayed to isDisplayed API call.

---

lib/command/init.js

I think grouping the questions by topic makes sense - or why do I get asked about custom steps, then about translations and then about custom steps again? Any specific reason?

Fix typo. Improve order of prompts.

---

lib/codecept.js

I found an issue with running a single test by absolute path, which doesn't allow to run or debug tests in WebStorm IDE

fix absolute path support

---

docs/helpers/Appium.md
lib/helper/Appium.js
test/helper/Appium_test.js

This PR aims to fix/improve the following issues with appium-wdiov5:
- https://github.com/Codeception/CodeceptJS/issues/1538 -> due to those such methods like `swipeUp`, `swipeDown`, `swipeLeft`, `swipeRight` are replaced by `touchAction`
- https://github.com/Codeception/CodeceptJS/issues/1535 -> call the appium api endpoint to remove app.
- https://github.com/Codeception/CodeceptJS/issues/1528 -> due to those such methods like `swipeUp`, `swipeDown`, `swipeLeft`, `swipeRight` are replaced by `touchAction`
- https://github.com/Codeception/CodeceptJS/issues/1527 -> call the appium api endpoint to set the orientation.

[Appium helper] Improvements on wdiov5

---

lib/assert/equal.js
lib/helper/WebDriver.js
test/helper/WebDriver_test.js

well the previous patch for `seeTextEquals` is not proper. This aims to make a proper fix.
I found the root cause, the problem is when `codeceptjs` try to get the text from the locator, it returns an `array`
```
const selected = await forEachAsync(res, async el => this.browser.getElementText(getElementId(el)));
```
In this case, the locator has no text it returns an `empty array`. However the the text you want to compare is a `string`. And the `equals` method is 
```
const comparator = function (a, b) {
return a === b;
};
```
and by this, it returns `false`, even though both are empty but one is `string`, one is `array`.

fixed 1561 properly

---

lib/helper/Puppeteer.js

Puppeteer crashes with `WebSocket is not open: readyState 3 (CLOSED)` because we call `closeOtherTabs` before set a current page.
Example config
```
Puppeteer: {
url: "http://localhost",
chrome: {
browserWSEndpoint: "ws://localhost:9990/devtools/browser/1bcc1a6c-faa7-42c2-a229-ac20ebac7b36",
ignoreHTTPSErrors: true
}
},
```

Fix Puppeteer launch with browserWSEndpoint

---

lib/helper/WebDriver.js

Fixed this issue
```
Lokyy   [Today at 2:43 PM]
Hello All , For Mobile Testing,  when I use,  I.scrollTo('some-locator'); is giving me the following error -  `Error: Malformed type for "xoffset" parameter of command touchScroll
Expected: number
Actual: string`
```

fixed the scrollTo does not work when running in mobile testing

---

lib/command/definitions.js
lib/parser.js
test/unit/locator_test.js
test/unit/parser_test.js
typings/index.d.ts

Updated `ILocator` definition (not founded use of `value` and removed it, added `id`)
Simplify TS definitions for functions with `locator`.
Fixed tests for parser.
Added tests for locator constructor (not necessary, but why not).
Need some TS developers review for errors, style and improvements

Update ts Locator definitions

---

lib/data/context.js
test/unit/data/ui_test.js

The [document](https://codecept.io/advanced#data-driven-tests) says:
> HINT: If you don't use DataTable. add toString() method to each object added to data set, so the data could be pretty printed in a test name
but it doesn't works, so this PR will fix it :)

Enable to show `toString()` in the each scenario names when it is defined

---

lib/command/definitions.js

Add typescript definition of `secret` function for #1598 
In ideal, it should looks like `declare function secret<T>(secret: T): T;`
Because it get any param and return it as is. Only `humanizeArgs` change it to `"*****"`
But `fillField` in definitions requires string as argument:
`fillField(field: LocatorOrString, value: string): void`
But it's not required in code - it use `value.toString()` (code from WebDriver helper):
```
async fillField(field, value) {
const res = await findFields.call(this, field);
assertElementExists(res, field, 'Field');
const elem = usingFirstElement(res);
return elem.setValue(value.toString());
}
```
Possible, it's better to change `toTypeDef` to generate `any` for `value` or in default case.
But it will require to do a correction of some helpers to make them …

Add ts definition of secret function

---

bin/codecept.js
docs/commands.md
lib/command/definitions.js

Added a param `--to`.
It will allow to generate file directly in described folder:
`codeceptjs def --to ./tests/typings`
will create file `<dir path>/tests/typings/steps.d.ts`
I am not sure about name of parameter, and should it generate file name or leave `steps.d.ts`?

Feature: add target folder parameter to def command

---

docs/helpers/Puppeteer.md
docs/webapi/grabDataFromPerformanceTiming.mustache
lib/helper/Puppeteer.js
test/helper/Puppeteer_test.js

**grabDataFromPerformanceTiming**
Grab the data from performance timing using Navigation Timing API Resumes test execution, so should be used inside an async function with await operator.
```javascript
await I.amOnPage('https://example.com');
let data = await I.grabDataFromPerformanceTiming();
//Returned data
{ // all results are in [ms]
responseEnd: 23,
domInteractive: 44,
domContentLoadedEventEnd: 196,
loadEventEnd: 241
}
```

(feat): grab perfermance timing data - puppeteer helper

---

docs/bdd.md
lib/command/gherkin/snippets.js

In reference to #1171 this would allow a user to target a specific file to upload snippets do rather than the first file in the steps array. 
Usage "codeceptjs  bdd:snippets [--path=PATH]"
For this to work the file must already exist and be included in the config steps.

Adding optional path parameter to bdd:snippets command

---

docs/mobile-react-native-locators.md
docs/mobile.md

I'm pretty new to the CodeceptJS, so maybe I'm missing some obvious approach to do the same thing.
Please suggest if I'm reinventing a wheel.
When I tried to make a test that would work on both platforms in the React Native app, I found out that test works on iOS but fails on Android. After some investigation I figured out that on Android React Native uses `setTag` to set test id, but UIAtomator2 doesn't have any means to query a view using tag.
After some researches I came to the point that the easiest way will be to use Espresso driver, which has built-in support for tags. But I was not able to use it's `view-tag` strategy directly, as `helper/Appium.js` has very strict rules on possible strategies. After several experiments and diving into espresso-appium-driver source code I finally …

Added Documentation for possible ways to locate elements in React Native apps

---

lib/helper/Puppeteer.js

fix: add Promise support to avoid UnhandledPromiseRejectionWarning on #page.on('load')# when #page.$('body')#

fix: add Promise support to avoid UnhandledPromiseRejectionWarning

---

docs/helpers/WebDriver.md
docs/plugins.md
lib/plugin/autoLogin.js

From v2.1.0, autologin plugin needs ｀await｀ syntax.
```js
// before v2.0.8
Scenario('login', (I) -> {
login('foo')
})
//after v2.1.0
Scenario('login', async (I) -> {
await login('foo')
})
```
Actually, `await` really needs when using async function in the autoLogin.
So that any functions invokes with `await` only if they are async function.

Enable to use autoLogin without await

---

docs/acceptance.md
docs/best.md

This PR fixes a small typo in the docs (accoross => across).

Fix small typo (accoross => across)

---

lib/helper/REST.js
test/rest/REST_test.js

Fix detection of urls without protocols in REST helper.
Fixes #1658
@DavertMik not sure, that tests for REST helper are running anywhere. Is it true?

Fix url autocompletion for REST helper

---

lib/command/run-multiple.js

Issue https://github.com/Codeception/CodeceptJS/issues/1636
When browser config has many settings, it would try to create output folder with too long name. With this PR, it will hash the `browserConfig` object and use it as a part of output folder name.

Fix 'ERROR: ENAMETOOLONG' when creating screenshots directory

---

lib/plugin/puppeteerCoverage.js

When running multiple testing scenarios, the output coverage test fail with already exist error

Fixing path already exists error

---

lib/locator.js
test/data/app/view/info.php
test/helper/WebDriverIO_test.js

This is about improving a11y selection support in the Webdriver.io helper. Currently, only strings in aria-label are recognized. With this commit, the prefix "~" would also check for the title attribute (which is not only an a11y method to describe icons or abbreviations) and also aria-describedby and aria-labelledby. The aria-describedby and aria-labelledby methods are the same as the lookup of inputs by their labels text.

Improve a11y selector support

---

lib/command/definitions.js

Fixed a silly error made in #1687 
Without pages it generates double commas:
```js
type ICodeceptCallback = (i: CodeceptJS.I, , ...args: any) => void;
```
Also added `IData` interface for `xData` and fixed a couple of linter errors

Fix extra comma in definition without pages

---

.travis.yml

for some reason, using latest chrome fails the webdriver tests.
Stick to a version of selenium standalone + chrome which is known to work.

workaround for selenium standalone chrome issues

---

lib/command/run-multiple.js

`config.tests` can be Undefined if the test suite only has Gherkin Files. 
When it's undefined, it throws an error: 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
at assertPath (path.js:39:11)
at Object.resolve (path.js:1088:7)```

Fix Run-Multiple when `tests` is undefined

---

docs/acceptance.md
lib/helper/WebDriver.js
test/helper/WebDriver_test.js

Sometimes we are testing the functionality of websites that we cannot control, such as a closed-source managed package of Salesforce, like ZQuotes within our instance. There are popups that either remain open for configuring data on the screen, or that close as a result of clicking a window, and we need more control over which page is being tested with Codecept at any given time. We use WebDriver to accomplish this. We have a workaround in place by using a custom helper, but it would be nice if these methods to control window handle properties on the Webdriver browser object were available in the core WebDeriver API.
- added methods to WebDriver and mocha test to WebDriver_test
- added mocha test 'allow back and forth between handles: #getWindowHandles #getWindowHandle #switchToWindow'

Allow Control between Specified Window Handles with WebDriver

---

lib/scenario.js

Root cause:
- Throwing an error in Scenario make recorder stopped. Then "after each" hook will restart recorder by using recorder.startUnlessRunning() and its error handler also will be reset to null. Finally, the hook cannot done and hang at this time.
Solution:
- Fix logic code

Fix issue 1161

---

lib/listener/config.js

**type:** bug
**What was the exact problem:**
When dynamic config was set on default to picking `helper[0]`. At that time for multiple helpers, to apply config for the first helper ( `helper[0]` ), it was using an array of `helpers` as name to find `helpers[name]`.
In short,
```js
if (name === '0') { // first helper
name = Object.keys(helpers);
// Now, typeof name is Array.
}
const helper = helpers[name];  // here, you can't use array to get particular helper
```
resolve #1742

fix: dynamic config applied for multiple helpers

---

lib/plugin/stepByStepReport.js

Currently the generated report folder names collide when tests have similar titles.
For example when you have test titles which start with "As a customer I want to..."
Different tests will end up being reported in same folder:
`<dir>/record_As_a_customer_I_want_1561724771/index.html`
With this fix a `md5 hash` is generated to avoid collisions in the reporting folders.
To calculate the md5 hash, `test.file` and `test.title` is used, just in case duplicate titles exist in a project.
After fix:
`<dir>/record_d43336466a7e65faf417d9ea70b3df70/index.html`

fix(plugin): stepByStepReport unique report folder

---

lib/pause.js

* show results for `grab*` methods
* show when assertions pass

Improved interactive pause

---

lib/container.js
test/unit/container_test.js

some change to how the support objects are initialized removed the original
reference to the support object and replaced it a "cloned" object. However,
since Object.assign was used, not all properties have been copied and especially
the original reference was lost.
This implementation uses a proxy object to load the injected modules on demand
and returns the original reference to the module. This should fix all usages
of support objects, where the type is not a plain object.
Fixes: #1679

fix references to support objects when using DI

---

CHANGELOG.md
RoboFile.php
docs/changelog.md
docs/helpers.md
docs/helpers/Puppeteer.md
docs/plugins.md
docs/puppeteer.md
lib/helper/Polly.js
lib/helper/Puppeteer.js
lib/plugin/autoLogin.js
package.json
website/sidebars.json

2.2 release

---

lib/helper/WebDriver.js
lib/utils.js

Using file content in base64 as an argument to `uploadFile`.
` Error: ENAMETOOLONG: name too long, open... `
Use filename as an argument to `uploadFile`.
Checkout official [doc](https://webdriver.io/blog/2019/06/25/file-upload.html)

fix: use filename for uploadFile in webdriver

---

lib/command/definitions.js
lib/container.js
test/runner/list_test.js

Provide more proxy traps to inspect support object, so generating the definitions file works fine, again.
Fixes #1795

fix: missing support object definition in steps.d.ts

---

lib/command/utils.js

When uses config with error, CodeceptJS throw non-informative message, like: 
```sh
$ codeceptjs run --config ./tests/codeceptjs/configs/ts.config.js --debug
Unexpected identifier
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
But with my fix, I get:
```sh
$ codeceptjs run --config ./tests/codeceptjs/configs/ts.config.js --debug
/home/avvorobey/git/form-builder/packages/codeceptjs/setup/bootstrap.ts:2
import codeceptjs from 'codeceptjs'
^^^^^^^^^^
SyntaxError: Unexpected identifier
at Module._compile (internal/modules/cjs/loader.js:721:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad …
```

fix(getConfig): threw a non-informative message if the config loading failed

---

lib/data/dataScenarioConfig.js

Fix: "TypeError: scenario.injectDependencies is not a function" on use Data().Scenario().injectDependencies() or Data().Scenario().inject();

 Fix:Data().Scenario().injectDependencies() is not a function

---

lib/ui.js

By returning the object of Scenario it continues to support other methods provided by Scenario.
resolves #1751

fix: Crash when using  xScenario & Scenario.skip with tag

---

lib/helper/Puppeteer.js

**Problem** 
With the puppeteer helper using `I.scrollTo()` on an element that's well below the viewport won't scroll to the element. The browser will remain in the upper area of the page instead.
**Solution**
The `elementCoordinates` returned by `_clickablePoint()` are **viewport** coordinates  (not window coordinates). Since we have already scrolled to the element via `_scrollIntoViewIfNeeded()`, we need scrollBy (not scrollTo) those coordinates to bring the element to the top the way webdriver does.
**Problem 2** 
When switching to an iframe, scroll is not correctly applied. 
**Solution 2**
Using `executeScript` instead of `this.page.evaluate`, since `executeScript` uses the current context (`_locate`, `_scrollIntoViewIfNeeded` and `_clickablePoint` use the it as well).

fix: puppeteer scroll to locator

---

lib/command/gherkin/snippets.js
test/data/sandbox/support/dummy.feature
test/runner/bdd_test.js

Fix issue when running snippets command with a .feature file that has steps with Gherkin special characters (any of  { } ( ) / )
Instead of creating strings, create regular expressions that will match
This fixes the problem where the generated snippets won't match the steps from the original .feature file

Fix for snippets command with a .feature file that has special characters

---

bin/codecept.js

PR https://github.com/Codeception/CodeceptJS/pull/1688 added support to direct new snippets to a specific file, but forgot to add the `--path` option to the command line parser.  Without this fix, `codeceptjs gherkin:snippets --path=foo` results in an error "error: unknown option `--path'"

Fix the --path option on gherkin:snippets

---

lib/helper/TestCafe.js

Testcafe tests were failing sometimes due to a promise being passed to `this.t.switchToIframe`. By adding the await, we make sure that the promise is resolved before passing it.

Fix TestCafe SwitchTo

---

lib/helper/Polly.js
lib/utils.js

Improve code coverage by checking the type of arguments.
resolves #1815

refactor: check typeof arguments for mock requests in Polly

---

docs/visual.md

Remove `adminPage` as this parameter is not needed and probably will break the scenario if not present.

Fix Parameter in Scenario Example

---

lib/command/run-multiple/chunk.js

Currently, it is impossible to run tests in parallel with TS, as regex finds only `.js` files. 
I've just updated the regex.

fix run-multiple with typescript

---

lib/locator.js

Without this change you need everytime and everywhere print "()" brackets.

fixed element position bug

---

lib/command/definitions.js

Error `Cannot find name 'EventEmitter'.ts(2304)` ocures without fix
was added in https://github.com/Codeception/CodeceptJS/pull/1800

Add NodeJS scope for EventEmitter

---

lib/helper/WebDriver.js

Made changes for the fillField helper. Added a line to speed up adding of text for an element having accessibility ID. Efficiency improved for fill field for iOS guys

Updated webdriver.js

---

lib/locator.js
test/unit/locator_test.js

After #1829 the locator functions `.at(i)`, `.first()` and `.last()` create xpath locators with round brackets. This may lead to "is not a valid XPath expression" exceptions (see #1866).
The changes of this PR
* "allows xpath locators to start with round brackets" for the `isXPath()`-method
* "prevents round brackets for nested selectors" by refactoring the old six times used  `removePrefix((new Locator(locator, 'css')).toXPath()))` expression to a new method called `convertToSubSelector(locator)` which also throws a specific error if the locator `isXPathStartingWithRoundBrackets`

Improve handling of xpath locators with round brackets

---

lib/plugin/wdio.js

Currently the `wdio` plugin isn't passing in all the arguments it can and should according to the launcher construction method signature as [specified by webdriverio](https://webdriver.io/docs/customservices.html). This PR seeks to rectify that.
Fixes #1868

Use WebDriver capabilities config in wdio plugin

---

lib/helper/WebDriver.js
package.json

When using client.newWindow function in openNewTab, windowName parameter is not set. This makes impossible to open a second tab.
Adding optional parameters to openNewTab allows to fix this issue without having a breaking change

fix #1874 Can not open more than one tab with webdriver helper

---

lib/command/run-workers.js

remove config from workerData

---

lib/helper/Puppeteer.js
lib/plugin/retryFailedStep.js
lib/plugin/screenshotOnFail.js
lib/utils.js
test/data/sandbox/codecept.retryFailed.json
test/data/sandbox/flaky_test.retryFailed.js
test/data/sandbox/retry_helper.js
test/runner/interface_test.js
test/unit/plugin/retryFailedStep_test.js

Got some improvements to retryFailedStep plugin.
* is activated only for tests
* contains blacklist of steps to ignore
* can be turned off for a specific test

Improved retryFailedStep plugin

---

Dockerfile

Fixes #1900 . Uses NodeJS 12.10.0 because it is currently the latest version.

Update Node version to 12.10 to support new CodeceptJS features

---

docs/angular.md

Modified the wording of the Angular documentation.
Tried to keep the original intent of the documentation, while adding missing particles and rearranging sentences in order to improve readability.

docs: clarified sentences in angular documentation

---

docs/configuration.md

The configuration page contains a dead link to the multiple execution details.
Adjusted link to point to the correct page containing the multiple  execution details.

Fix broken 'Multiple  Execution'-link

---

lib/plugin/puppeteerCoverage.js

Docs were talking about `outputDir` while in reality `coverageDir` was used.

Fix documentation of puppeteerCoverage plugin

---

lib/helper/TestCafe.js

TestCafe port's management removed (left on TestCafe itself)

---

lib/step.js

This creates a deep copy of the `include` part from configuration.

Fix #1903 make a copy of page objects config per step although it is deprecated

---

CONTRIBUTING.md
docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/TestCafe.md
docs/helpers/WebDriver.md
docs/helpers/WebDriverIO.md
docs/webapi/dontSeeCheckboxIsChecked.mustache
docs/webapi/dontSeeInField.mustache
docs/webapi/pressKeyDown.mustache
docs/webapi/pressKeyUp.mustache
docs/webapi/pressKeyWithDetectOS.mustache
lib/helper/Puppeteer.js
lib/helper/WebDriver.js
lib/utils.js
test/docker-compose.yml
test/helper/Puppeteer_test.js
test/helper/WebDriver_test.js

* Changed `pressKey` method to resolve issues and extend functionality.
* Did not properly recognize `'Meta'` (or `'Command'`) as modifier key.
* Right modifier keys did not work in WebDriver using JsonWireProtocol.
* `'Shift'` + `<key>` combination would not reflect actual keyboard behavior.
* Respect sequence with multiple modifier keys passed to `pressKey`.
* Add support to automatic change operation modifier key based on operating system.
* Updated `pressKey` documentation to show a proper list of available key names which are available **both** in [Puppeteer](https://github.com/GoogleChrome/puppeteer/blob/v1.20.0/lib/USKeyboardLayout.js) and [WebDriver](https://www.w3.org/TR/webdriver/#keyboard-actions).
* Added `pressKeyDown` and `pressKeyUp` methods with similar functionality as …

Improve handling of pressing keys for Puppeteer and WebDriver

---

lib/helper/Puppeteer.js

switchTo did not work as expected in some situations, because the lookup code did not consider every possibility. However, given a ElementHandle, the corresponding frame can be fetched directly using Puppeteer API. This allows to remove a lot of code and should still work as expected.
I tried to add failing tests, but could not come up with a minimal example. I'll try a little harder to come up with something, but wanted to get this PR out of the door.
Fixes: #1439

fix(Puppeteer): simplify switchTo iframe by selector

---

docs/email.md

MailSlurp was spelled wrong in one place, and the link associated with their guide went to a 404 page. This fixes those issues.

Fixing typo in email testing guide

---

website/static/css/custom.css

fix search input on focus & active (table & mobile)

---

package.json

`parse-function` has been fix the [issue][] that cause `Cannot find module './utils'` error, so we don't need to keep version in 5.2.x 🎉
[issue]: https://github.com/Codeception/CodeceptJS/issues/1976

upgrade parse-function to 5.4.x

---

docs/configuration.md

fix(docs): add "Allows to enter glob pattern" for configuration

---

docs/helpers/TestCafe.md
lib/helper/TestCafe.js
package.json

Saw this very nice functionality of TestCafe was not supported yet, so I have implemented it. You can now configure your TestCafe helper with browser: 'remote' that results in a testcafe remote connection. It will print the url and a QR-Code to automatically scan and navigate to it via the browser of the remote device. 
For more information/background about remote test see: 
https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html

Support remote connections for TestCafe helper

---

lib/ui.js
test/unit/ui_test.js

- Codecept will always match test case title prefix ‘@’ string and push to test tags array,
If match failed will cause the null tag issue.

fix: mismatch tags from title will cause null tag

---

bin/codecept.js
lib/command/info.js

This gives more info when using `npx codeceptjs info`
```sh
$npx codeceptjs info
Environment information:-
codeceptVersion:  "2.3.0"
nodeInfo:  10.15.0
osInfo:  macOS Mojave 10.14.6
cpuInfo:  (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
chromeInfo:  78.0.3904.108
edgeInfo:  N/A
firefoxInfo:  65.0.1
safariInfo:  13.0.4
helpers:  {
"WebDriver": {
"url": "https://www.amazon.de",
"browser": "chrome",
"desiredCapabilities": {
"chromeOptions": {
"args": [
"--headless",
"--disable-gpu",
"--window-size=1440,700"
]
}
},
"windowSize": "1440x700"
}
}
plugins:  "You don't have any enabled plugins"
***************************************
If you have questions ask them in our Slack: shorturl.at/cuKU8
Or ask them on our discussion board: https://codecept.discourse.group/
If you …
```

improve the codeceptjs info

---

lib/helper/Puppeteer.js
test/helper/Puppeteer_test.js

- The following code failed with Error: JSHandles can be evaluated only in the context they were created!
```
it('should grab inner html from within an iframe', () => I.amOnPage('/iframe')
.then(() => I.switchTo({ frame: 'iframe' }))
.then(() => I.grabHTMLFrom('#new-tab'))
.then(html => assert.equal(html.trim(), '<a href="/login" target="_blank">New tab</a>')));
```

Fixed puppeteer grabhtml to refer to current context

---

lib/plugin/screenshotOnFail.js
lib/utils.js
test/unit/utils_test.js

Cannot use absolute directory and absolute filenames for screenshots.
I have config in e2e folder path:
`/Users/<username>/workbase/<project>/src/ts/specs/E2E/codecept.conf.js`
And I want to save reports and screenshots in project folder:
`/Users/<username>/workbase/<project>/test_output/mochawesome`
`/Users/<username>/workbase/<project>/test_output/screenshots`
So I set in codecept config:
```
output: path.resolve(process.cwd(), "test_output/screenshots"),
...
mocha: {
reporterOptions: {
reportDir: path.resolve(process.cwd(), "./test_output/mochawesome"),
...
```
(Also tests run form project folder: `NODE_ENV=test TS_NODE_PROJECT='./src/ts/specs/E2E/tsconfig.json' codeceptjs run -c ./src/ts/specs/E2E/codecept.conf.js --reporter mochawesome`)
`screenshotOutputFolder` generates screenshot …

Screenshots path correction

---

lib/output.js

`say` require 2 arguments, instead of 1

fix: update JSDoc for `say`

---

lib/helper/WebDriver.js

I just stumbled upon the issue, that the return values from certain grab*-functions are different in webdriver and puppeteer, when just a single element has been found. This PR affects the functions `grabValueFrom`, `grabCssPropertyFrom` and `grabAttributeFrom` for webdriver. As Puppeteer always returns just the element when the selector just found one. `grabTextFrom` and `grabHTMLFrom` webdriver does the same thing. Therefore, I applied this functionality also to the above mentioned functions.

Streamlined return values from grab*

---

lib/command/init.js

Since `console.print()` does not exists 😄
`console.print()` does not exists

fix: replace console.print with console.log

---

lib/helper/FileSystem.js
test/unit/helper/FileSystem_test.js

- For a project I've been working with I need to download and assert the downloaded file but filenames are partially unique, so I only know a part of the file I want to see/assert. I've added support for asserting that any file exists including the given text.
- Also for this issue I needed get the filenames in current directory, I've exploited the getFileNames() function for further use.

File system extended

---

lib/helper/Puppeteer.js
lib/utils.js
test/data/app/view/form/doubleclick.php
test/helper/webapi.js

Before this fix, `grabCssPropertyFrom` for values with hyphen always returned undefined because `getComputedStyle` returns the css properties in camelcase.

fix: cannot grab for css attributes with hyphen

---

.eslintignore
lib/helper/TestCafe.js
test/helper/webapi.js

`grabAttributeFrom()` method not returning the attribute value
https://stackoverflow.com/questions/59133688/grabattributefrom-method-not-returning-the-attribute-value

fix: TestCafe grabAttributeFrom method not works

---

lib/container.js

- This feature deals with the Steps config under Gherkin Key of codecept.conf.js. Previously, we had to enter all Step Definition files. In order to permit users to specify single *.js file so that all files under that folders will be read, this feature has been added to lib/container.js code.
- [https://github.com/Codeception/CodeceptJS/issues/1911]

#1911 - Regex for step Def file

---

lib/helper/MockRequest.js

I wanted to configure Polly to use `mode: replay`.
The [docs](https://codecept.io/helpers/MockRequest) indicate that you can pass a config object to `MockRequest`, but this isn't used when instantiating Polly.
In this PR, the default configuration passed to Polly is merged with the config from `MockRequest`, making it possible to have something like this and instantiating Polly in `replay` mode.
```js
helpers: {
Puppeteer: {
// regular Puppeteer config here
},
MockRequest: {
mode: 'replay',
},
}
```
I wanted to add tests but wasn't sure if there were any tests for `MockRequest` and how I could add one. Just tell me how and where if you need one.

Allows overriding default Polly config in MockRequest

---

lib/parser.js

When running codeceptjs in a CommonJS (CJS) environment, there is an error running the `codecept` command.
Error as below:
```
TypeError: require(...) is not a function
at Object.<anonymous> (/MyApp/node_modules/codeceptjs/lib/parser.js:1:103)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/MyApp/node_modules/codeceptjs/lib/command/list.js:5:27)
at Module._compile (internal/modules/cjs/loader.js:701:30) …
```

Add Interoperable Code for supporting both CJS & ESM environments

---

docs/helpers.md

fix(docs): add info about _after hook in helper

---

lib/helper/TestCafe.js
test/helper/TestCafe_test.js

`waitForFunction` was breaking when using the TestCafe helper. The error suggested adding `.with({ boundTestRun: this.t })`. Upon inspecting the code, it looks like the function was not doing what I was expecting: it had the same logic as `waitUrlEquals` and the `fn` parameter (the function to wait for) was not being used.
I think now it has the expected functionality. I added the same tests as the Puppeter helper.

Fix waitForFunction in TestCafe helper

---

lib/listener/exit.js

TestCafe returns 0 exit code on test failure. In this PR `beforeExit` listener is registered which will exit the process with appropriate exit code
Fixes #2090

Fix: Add beforeExit listener in exit.js

---

lib/codecept.js

Fix for No error stack trace for syntax error #2118
**No error stack trace for syntax error #2118**
- [x ] Lint checking (Run `npm run lint`)

No error stack trace for syntax error #2118

---

typings/jsdoc.namespace.js

Added possibility to ignore JSDoc doclet in doc/typings.
Now `@private` and `@ignore` JSDoc annotations will allow not to build doc/typings for code.
Added to allow not to build typings for internatl methods, such as `filterAsync`/`forEachAsync` in WebDriver helper.

feat: add possibility to ignore doclet with 'ignore' and 'private' tags

---

lib/helper/WebDriver.js

This reverts commit 4a769f144c9b02708f3e2c6f30590aaafeb0756c.
Previous PR broke backwards compatibility. 
We will change how grab* methods work but once we will be releasing 3.0
- [ x ] Webdriver

Revert "Streamlined return values from grab* (#2054)"

---

docs/bdd.md
lib/data/dataTableArgument.js
lib/helper/FileSystem.js
lib/interfaces/gherkin.js
test/unit/bdd_test.js
test/unit/data/dataTableArgument_test.js

providing datable by header in steps' arguments
parsed DataTable in steps arguments
**Description of this PR, which problem it solves**
A 'parse' method in the DataTable object that provide a simplidied version of it. It also provides methods for using it with headers : 
- raw : returns the table as a 2-D array
- rows : returns the table as a 2-D array, without the first row
- hashes : returns an array of objects where each row is converted to an object (column header is the key)
this work is inspired by the same feature from cucumber-js module : https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/data_table_interface.md
**A link to the corresponding issue (if applicable).**
https://github.com/Codeception/CodeceptJS/issues/2081

providing a parsed DataTable in steps' arguments

---

lib/command/run-workers.js
lib/command/workers/runTests.js
test/data/sandbox/workers/retry_test.workers.js
test/runner/run_workers_test.js

Tests are not reported as passed if the test is passed in a retry while using run-workers.
While appending test status, passing of already failed test is not accounted for. So adding a map with `test.id` and appending status accordingly fixes the issue.
- Fixes #1985

fix: Avoid failiure report on successful retry in worker

---

docs/basics.md
lib/pause.js

Ability to add and use variables in pause() interactive CLI.
```js
I.click('xxx');
pause({
variable1, variable2, pageObject1 // pass in all objects as parameters into pause
})
```
Prefix `=>` to run JS commands
```
=>console.log(variable1);
=> pageObject1.open();
```
- Fixes #2132 Fixes #1184 Fixes #396

Add ability to pass variables to pause()

---

test/acceptance/mock_test.js

Fix circle-ci tests to fail intermittently
```sh
1) Mocking
should request for original data after mocking stopped @Puppeteer @WebDriver:
expected element #data not to include "_uniqueId_u4805sd23"
+ expected - actual
-------
-comment	CUSTOM _uniqueId_u4805sd23
-------
+_uniqueId_u4805sd23
```

(fix): wait for text instead of waiting for 2 secs

---

lib/helper/WebDriver.js

Fixed timeout, native webdriverio method requires timeout in ms
I verified the fix manually, on the example attached in the issue, with default WebDriver timeout and with timeout passed to `waitForClickable()`.
- Resolves #2166  (if applicable).

Fix: waitForClickable: Timeout doesn't work, method call fails immediately

---

lib/helper/Puppeteer.js
test/helper/Puppeteer_test.js

Noticed an issue with basic auth in the puppeteer helper when running multiple sessions.  The authentication would be sent in the first scenario, but in subsequent scenarios it wouldn't get sent.  
I found that the `isAuthenticated` boolean wasn't getting reset to `false`, so this adds that reset in `_stopBrowser`.  This also adds an `await` to the `authenticate` call so that it doesn't set `isAutheticated` before successfully authenticating.

fix: puppeteer basic auth fix

---

lib/plugin/selenoid.js

If desiredCapabilities is provided selenoid fails to pass options to webdriver. This PR fixes the issue
- Resolves #2183

Fix: Add deepMerge to selenoid options

---

bin/codecept.js
lib/command/run-multiple.js
lib/helper/WebDriver.js

I want to have colors in console output when running parallel tests in dockerized environment.
The fix allows passing the option `--colors` to child processes. If you omit `--colors`, it works as before - in docker, colors won't work. In non-docker env, colors will work.
- Resolves #1876

Fix: Missing colors in output from run-multiple in docker

---

docs/bdd.md

Adds npx command where it's missing at the BDD documentation section.

Doc: Add npx command where it is missing

---

lib/command/generate.js

`codeceptjs generate:test` is not detecting the suffix used in the project config.
I have this in my config:
```
tests: `./tests/**/*.spec.ts`
``` 
but the command still suggests `_test.js`.
This is solved with a small bugfix in the pattern line.

fix(command): generate test not respecting config

---

docs/helpers/Appium.md
docs/helpers/WebDriver.md
docs/webapi/type.mustache
lib/helper/WebDriver.js
test/helper/WebDriver_test.js

Adding a type function to Webdriver, when `fillField` is not a valid option to use.
- Resolves #2185

added webdriver type function

---

lib/command/generate.js

`codeceptjs generate:test` is lower casing the input, restricting projects to define their own naming convention for the test files.
Also, for a newbie, it's helpful to have an introductory example showing that it's possible to use paths, and encourage its usage for better categorization of the tests :)

fix(command): respect case generate test 

---

lib/plugin/screenshotOnFail.js

- The `screenshotOnFail` plugin doesn't work on the Playwright helper. The fix is simple by just adding the helper to the helper list.

Add Playwright support on screenshotOnFail plugin

---

lib/interfaces/gherkin.js
test/unit/bdd_test.js

Gherkin allows to set different tags per example https://github.com/cucumber/cucumber/tree/master/gherkin#pickles
In codecept the examples tags are ignored

Gherkin - including examples tags into test tags

---

lib/helper/TestCafe.js

Earlier it seems like it was clicking the first element. Now it clicks the first visible element,
- Resolves https://github.com/Codeception/CodeceptJS/issues/2226

Updated to click the firstVisibleElement

---

docs/helpers/Playwright.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/webapi/seeInPopup.mustache
lib/helper/Playwright.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js

I noticed that the typescript interface of the seeInPopup was missing the input parameter, so I went ahead and added it in the JSDoc from which type definitions are generated.

add missing JSDoc parameter for seeInPopup method, update documentation

---

lib/helper/Nightmare.js
test/helper/webapi.js

Added grabCssPropertyFrom support for Nightmare helper.
fixes #642

feat : Add grabCssPropertyFrom method for Nightmare

---

lib/helper/WebDriver.js

On BrowserStack and current latest Appium available `v1.9.1` the following occurs when trying to run a test on a real iOS device:
`Parameters were incorrect. We wanted "MJSONWP protocol requires type and ms" and you sent {"script":1000}`.
I think this is a bug related to Appium on iOS. BrowserStack does not give any ETA when a newer Appium version will be available for iOS on their platform.
In the WebDriver spec the default script timeout is set to `30000 ms`, I think it is safe to fallback to that value. See https://w3c.github.io/webdriver/#timeouts.
Fix #1529

Remove default script timeout config.

---

lib/locator.js

Many CSS starts with "[", specifically with `data` attributes. For an example "[data-automation="some-automation-attributes"]". Adding one more check to the CSS strategy.

CSS check to include `[` to determine if locator is CSS or not

---

lib/helper/scripts/isElementClickable.js
package.json
test/data/app/view/form/wait_for_clickable.php
test/helper/Puppeteer_test.js
test/helper/WebDriverIO_test.js

- Changed the logic, since the source and clickable elements were compared. This led to instability, since the properties could change

fix: change overlapping logic

---

docs/helpers/Playwright.md
docs/playwright.md
lib/helper/Playwright.js
lib/helper/extras/PlaywrightPropEngine.js
lib/locator.js
package.json
test/helper/Playwright_test.js

- Following on from https://github.com/Codeception/CodeceptJS/pull/2274
- Blocked until playwright release for: https://github.com/microsoft/playwright/issues/1238
- Haven't updated: `waitNumberOfVisibleElements` not sure what to do here. Might need to put the waitFor/retry logic into the Playwright.js and make use of $$eval which will return an array of elements,
- Need to look at what I might have broken
- Needs tests

Custom locators playwright 0.12.1

---

docs/helpers/Puppeteer-firefox.md
lib/helper/Puppeteer.js
package.json

- Bump puppeteer to v2 which is supporting running tests with firefox instead of using `puppeteer-firefox`
- Resolves #2282.
- Currently there are only 2 failed tests. I logged that issue in Puppeteer https://github.com/puppeteer/puppeteer/issues/5543
- I don't expect any breaking changes for any one is using `puppeteer-firefox` but yeah, probably there is.

bump puppeteer to v2

---

lib/helper/REST.js
test/rest/REST_test.js

- Adds check for if Content-Type header is already set by user before defaulting to x-url-encoded when data is string. Also adds tests for this. Let me know if I should add documentation as well for this
- Resolves #2224 

#2224 Rest helper should respect content type header

---

lib/plugin/allure.js
test/data/sandbox/configs/allure/allure-failed.conf.js
test/data/sandbox/configs/allure/before_suite_test_failed.conf.js
test/data/sandbox/configs/allure/before_suite_test_failed.js
test/runner/allure_test.js

- Fixes issue with allure when BeforeSuite fails in parallel workers codeceptjs still output success when allure is enabled. Observe this is marked as `OK` rather than failed:
This underlying error is masked in workers mode, but if you run in non workers mode you'll see this error:
```
TypeError: Cannot read property 'end' of undefined
at Allure.endCase (/Users/myuser/Code/codecepttest/node_modules/allure-js-commons/index.js:50:26)
at EventEmitter.<anonymous> (/Users/myuser/Code/codecepttest/node_modules/codeceptjs/lib/plugin/allure.js:219:16)
at EventEmitter.emit (events.js:208:15)
at Object.emit (/Users/myuser/Code/codecepttest/node_modules/codeceptjs/lib/event.js:115:28)
at errHandler (/Users/myuser/Code/codecepttest/node_modules/codeceptjs/lib/scenario.js:101:13)
at …
```

handle beforesuite failures when allure enabled and report beforesuite failures

---

lib/plugin/autoDelay.js
lib/plugin/screenshotOnFail.js
lib/plugin/standardActingHelpers.js
lib/plugin/stepByStepReport.js
lib/plugin/supportedHelpersList.js

We have added 2 more helpers and forgot to add them to supported helpers array of this plugin. 
By separating the supported helpers into a file, we could prevent the missing update on many places, in another words, we just update the new support helper into the list in file and we are all good. One place to update.

(fix): add missing supported helpers

---

lib/helper/Playwright.js
lib/helper/extras/PlaywrightPropEngine.js
test/helper/Playwright_test.js

- Fixing issues with playwright
- Fixed waitForValue so far
- [/ ] Playwright

Playwright fixes - Work in progress

---

docs/basics.md

fixed typo in basic within section ReadMe

---

docs/basics.md
docs/configuration.md
examples/codecept.conf.example.js
lib/command/interactive.js
lib/command/run-multiple.js
lib/command/run-rerun.js
lib/command/run-workers.js
lib/command/run.js
test/data/sandbox/config.js

Add --profile Support for run-multiple and run workers.
Resolves #1968 #1315

Add --profile Support for run-multiple and run workers

---

lib/plugin/screenshotOnFail.js
test/unit/plugin/screenshotOnFail_test.js

- Fix issue when having the flag `uniqueScreenshotNames` true of `screenshotOnFail` plugin results undefined in screenshot file name.
- Resolves #2301.

(fix): undefined in screenshot name

---

lib/command/gherkin/snippets.js
test/data/sandbox/codecept.duplicate.bdd.json
test/data/sandbox/support/duplicate.feature
test/runner/bdd_test.js

- Avoid generating duplicated steps with `gherkin:snippets` command
- Resolves #2316

Gherkin: avoid creating duplicated steps

---

lib/helper/WebDriver.js

- When using WebDriver helper with webdriverio@^6.0, the `waitForElement` function is not applying the optional second argument to override the default timeout length. 
- WebDriverIO v6 updates `waitUntil` method which is used by all of the `wait*` functions. Many of these function were updated, such as `waitForVisible` and `waitInUrl` however `waitForElement` appears to still use the webdriverio@^5.0 code.
- This updates the `waitForElement` function by the same convention used to update `waitForVisible` and `waitInUrl` to be compatible with both WebDriverIO v5 & v6.
- I was unable to configure the repo to run the tests in examples directory. I implemented tests for this fix on a branch I use myself, so any guidance in implementing a test for this would be …

update waitForElement to support waitUntil in webdriverio^6.0

---

docs/custom-helpers.md

- Fix typos and rephrase some places.

(fix): some typos in custom-helpers.md 

---

lib/helper/WebDriver.js
lib/plugin/screenshotOnFail.js
lib/session.js
test/acceptance/codecept.Playwright.js
test/acceptance/codecept.Puppeteer.js
test/acceptance/codecept.WebDriver.js
test/acceptance/session_test.js
test/unit/plugin/screenshotOnFail_test.js

In multi-session mode when test failed screenshot was not taken because browser of a session was already closed at that point. 
This PR changes event when sessions are closed (from test.finished to test.after) and adds a test.

Fixed screenshot on failure for active session of WebDriver

---

lib/helper/Playwright.js

- https://github.com/microsoft/playwright/blob/master/docs/api.md#pagesetcontenthtml-options. According to the doc, only use either one of those values 
```
"load"|"domcontentloaded"|"networkidle0"|"networkidle2"
```
- Resolve #2328, #2305

(docs): update playwright docs for how to use the waitForNavigation

---

lib/helper/WebDriver.js
lib/plugin/wdio.js

- Due to the changes on the way how services is initialized in wdio, we need to update our wdio plugin to make it work again with wdio v6.
- Resolves #2315, #2288.

(fix): wdio plugin issue with wdio v6

---

lib/helper/WebDriver.js

- Faced issues with using of waitForEnabled - it used waitUntil with default 3000 ms for timeout
- Pretty similar fix as [this one](https://github.com/Codeception/CodeceptJS/pull/2313) but for waitForEnabled method of WebDriver

waitForEnabled fix for webdriver 6

---

lib/command/run-workers.js
lib/command/workers/runTests.js
test/data/sandbox/configs/workers/codecept.workers-negative.conf.js
test/data/sandbox/workers/negative_results/negative1.workers.js
test/data/sandbox/workers/negative_results/negative2.workers.js
test/runner/run_workers_test.js

fix(workers): If fail scenario with same name, but diff feature - shows negative result

---

lib/event.js
lib/reporter/cli.js
test/data/sandbox/before_failure_test.js
test/data/sandbox/codecept.beforetest.failure.json
test/runner/before_failure_test.js

If a test is failed in `before` , the rest of the tests are not executed and the status of the test is also not reported.
Hereafter these tests are marked as skipped and a new event `test.skipped` will be triggered
Fixes #2349

Add mocha before hook issue fix

---

lib/plugin/allure.js
lib/reporter/cli.js

Add skipped event listener for allure

---

lib/plugin/stepByStepReport.js

Fixed. Steps from BeforeSuite are skipped now when running `stepByStepReport` plugin.
- Fixes failed test if a helper method is used in `BeforeSuite`
- Resolves #2337 (if applicable).

Test fails with plugin stepByStepReport applied on step in function BeforeSuite

---

CHANGELOG.md
docs/basics.md
docs/changelog.md
docs/helpers/Appium.md
docs/helpers/Playwright.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md
package.json
test/acceptance/codecept.Puppeteer.js

Release 2.6.3

---

.github/workflows/appium.yml
.github/workflows/playwright.yml

@PeterNgTr I could not migrate our Semaphore Ci setup to a new version
It appeared they require to create a new account to access Semaphore 2.0 which is not useful.
So I  moved things to Github Actions, probably we should have done it in the beginning but I didn't know Semaphore is such a mess in migration :(

Appium tests

---

docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Playwright.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/TestCafe.md
docs/helpers/WebDriver.md
docs/webapi/grabAttributeFrom.mustache
docs/webapi/grabCookie.mustache
docs/webapi/grabGeoLocation.mustache
docs/webapi/grabNumberOfOpenTabs.mustache
docs/webapi/grabNumberOfVisibleElements.mustache
docs/webapi/grabSource.mustache

Add missing `async` descriptions for `grab*` methods.

docs: add missing async in grab* functions docs

---

lib/helper/Playwright.js
test/helper/Playwright_test.js

Updated Playwright grab functions to match new spec

updated grabbers

---

docs/helpers/WebDriver.md
lib/helper/WebDriver.js

The [`/quickstart/#prepare-selenium-server`](https://codecept.io/quickstart/#prepare-selenium-server) path cannot found.
Fix link to [`/webdriver#what-is-selenium-webdriver`](https://codecept.io/webdriver/#testing-with-webdriver)

Fix a borken link to webdriver

---

.eslintrc.json
examples/codecept.conf.js
lib/plugin/tryTo.js
test/unit/plugin/tryTo_test.js

Added `tryTo` function which won't fail a test on step failure
```js
const isSeen = await tryTo(() => {
I.see('Some text');
});
```
This also helps when you need to click a button on a condition.
```js
// we are not sure if cookie bar is displayed, but if so - accept cookies
tryTo(() => I.click('Accept', '.cookies'));
```

added conditional actions plugin

---

.github/workflows/playwright.yml
.travis.yml
Dockerfile
docs/custom-helpers.md
docs/helpers/Playwright.md
docs/playwright.md
lib/helper/Playwright.js
package.json

- Upgrade playwright to their first Major release.
- 2 breaking changes: waitFor method gone, and waitFor attribute of waitForSelector ranamed to state
- networkidle2 removed, networkidle0 === networkidle

Upgrade playwright to 1.0.0

---

docs/hooks.md
lib/event.js
lib/interfaces/gherkin.js
test/unit/bdd_test.js

I was looking for a way to create a better BDD reporter but could not get a hook to a bdd steps. This adds a way to hook before/after a bdd step. Hope I did not mess this up as this is my first try here.

feat: add bddStep before/after step hook

---

docs/commands.md

docs: fix typo in commands.md

---

docs/detox.md
docs/mobile-react-native-locators.md
docs/mobile.md
lib/helper/Appium.js
test/unit/utils_test.js

- Currently, appium helper does not work with android native locator so this pr is made to resolve #2428 
- Update doc for android typo
- Update FileHelper unit test to work correctly on windows platform

Fix android native locator support for appium helper

---

lib/actor.js

minor thing but color param in `I.say` is required in typings

chore: jsdoc color param optional in `I.say`

---

lib/helper/WebDriver.js
lib/helper/WebDriverIO.js

`waitNumberOfVisibleElements` is broken in WebDriver helpers
**Usecase:** 
When a locator returns 2 elements with 1 visible and other is not ,
Calling `I.waitNumberOfVisibleElements(locator,1)` fails everytime. 
The root cause is that the helper functions get an array of visibility booleans but does not filter them by value `true` 

Fixed waitNumberOfVisibleElements for Webdriver

---

lib/step.js
test/data/sandbox/configs/pageObjects/codecept.logs.json
test/data/sandbox/configs/pageObjects/customHelper.js
test/data/sandbox/configs/pageObjects/fs_test.logs.js
test/data/sandbox/configs/pageObjects/pages/logs_page.js
test/runner/pageobject_test.js

If helper method gets args of object type, our logs become not readable. Like: 
```js
I wait for visible { property: 'value', ... }
```
This MR adds a feature which allows pass args with custom parse-function for print pretty args. Example:
Create function `humanizeArgs` which return some string from your value or your data. 
```js
// PageObject.js
module.exports = {
_init() {
this.value = 'Logs Page Value';
},
humanizeArgs() {
return this.value;
},
};
```
In Custom Helper creates function which gets object with some value.
```js
// CustomHelper.js
class CustomHelper extends Helper {
getHumanizeArgs(objectArgs) {
console.log(objectArgs.value);
}
}
module.exports = CustomHelper;
```
And call this custom method on your scenario
```js
// Scenario.test.js
Feature('Filesystem'); …
```

tests(step-log): Custom pretty logs for method args

---

tsconfig.json

This resolves (#2483), since async and await are no long transpiled to ES generators
This will allow CodeceptJS TypeScript asynchronous tests to run correctly. Errors are correctly reported back to the CodeceptJS test runner with this change. Asynchronous scenarios are correctly determined as completed with this updated. 
Note that without this configuration change at this time, all TypeScript projects will not work properly if they use asynchronous Scenarios. This would impact all helpers. 
- [X ] :bug: Bug fix

Update compilerOptions.target to es2017

---

lib/helper/Playwright.js
lib/mochaFactory.js

- If an array of cookies gets passed to `setCookie` and Playwright is being used as the helper, it fails because the helper spreads the cookies when calling the browser context method i.e. `this.browserContext.addCookies(...cookie)` when Playwright is expecting an array i.e. `this.browserContext.addCookies(cookie)`. 

Fix playwright set cookie

---

.github/workflows/check.yml

This will create test documents in wiki page like this https://github.com/testomatio/check-tests/wiki/Tests. Test doc generated for codeceptJS is attached to this PR
Doc generated for this project
📝 [test/graphql/GraphQL_test.js](https://github.com/codeceptjs/CodeceptJS/tree/master/test/graphql/GraphQL_test.js) 
* 📎 **GraphQL** 
* 📎 **basic queries** 
* ✔️ `should send a query: read` 
* 📎 **basic mutations** 
* ✔️ `should send a mutation: create` 
* ✔️ `should send a mutation: delete` 
📝 [test/graphql/GraphQLDataFactory_test.js](https://github.com/codeceptjs/CodeceptJS/tree/master/test/graphql/GraphQLDataFactory_test.js) 
* 📎 **GraphQLDataFactory** 
* 📎 **create and cleanup records** 
* ✔️ `should create a new user` 
* ✔️ `should create a new user with predefined field` 
* ✔️ `should …

Add documentation changes for check-tests

---

docs/react.md

Just a fix for typo in documentation - `minifcation` -> `minification`

Fix typo in locators docs section

---

docs/bdd.md
lib/command/gherkin/steps.js
lib/interfaces/bdd.js

When running `bdd:steps` displays step & file on the same line so they could be easily grepped

added grep support

---

lib/plugin/standardActingHelpers.js

- Currently using REST helper to writing API tests, I would like to add the delay in between those steps, so we miss the REST helper in the standard acting helpers. This aims to add the missing helper.

add missing REST helper

---

lib/plugin/screenshotOnFail.js

Improve error logging for screenshotOnFail

---

lib/helper/Puppeteer.js

fix(page-timeouts): method amOnPage freezing, when  equal 0.

fix(page-timeouts): the amOnPage method freezes when getPageTimeout is 0.

---

lib/step.js

Error:
Cannot read property 'toString' of null
typeError: Cannot read property 'toString' of null
at G:\CodeceptJS-Test\node_modules\codeceptjs\lib\step.js:115:22
Solution: Rearranged typeof check to handle crash when helper method is called with null parameter.
- Resolves #2493 .

Rearranged typeof check to handle null parameter

---

CHANGELOG.md
docs/books.md
docs/changelog.md
docs/community-helpers.md
docs/examples.md
docs/helpers/Appium.md
docs/helpers/WebDriver.md
docs/playwright.md
docs/videos.md
docs/webapi/type.mustache
lib/helper/Nightmare.js
lib/helper/Playwright.js
lib/helper/Protractor.js
lib/helper/Puppeteer.js
lib/helper/TestCafe.js
lib/helper/WebDriver.js
lib/step.js
runio.js
test/helper/WebDriver_test.js
test/helper/webapi.js
test/unit/steps_test.js

Release 2.6.8

---

lib/helper/TestCafe.js

I tried the beta of codeceptjs and I got an error on the grabAttributeFrom.

fix(testcafe): fix debug in grabAttributeFrom method

---

lib/ui.js

For our allure integration we want to add some common fields just one time for suite.
```
Feature('Suite title', { allureLabels: { component: 'auth' } })
Scenario('Scenarion one title', { allureLabels: { package: 'package1' } })
Scenario('Scenarion two title', { allureLabels: { package: 'package2' } })
```
`component auth` is common for several Scenarios, and we dont want to copypaste it for every test.
Right now it is not possible to get `component auth` inside our allure plugin. With this pr it will be possible.

Save feature opts in suite

---

docs/basics.md

We ran into issues using the within() function. It seems that when running with Selenoid, the within() step would never complete and need to be aborted manually. However this was fixed easily by adding an `await` to our within function call (we were using async Webdriver methods inside the `within` call). I thought adding a line about this to the existing warning about `within` in the docs might help, though I'm open to other ways of doing this!
None I think

add warning await within()

---

.mocharc.js
lib/actor.js
lib/config.js
lib/recorder.js
lib/step.js
package.json
test/data/sandbox/configs/steps/codecept-2000.conf.js
test/data/sandbox/configs/steps/codecept-500.conf.js
test/data/sandbox/configs/steps/customHelper.js
test/data/sandbox/configs/steps/first_test.js
test/runner/allure_test.js
test/runner/consts.js
test/runner/interface_test.js
test/runner/steps_test.js
test/unit/actor_test.js
test/unit/worker_test.js

feat(timeout): Added timeouts for steps

---

lib/helper/Playwright.js
package.json

I am exploring playwright as an option in my organization and SSL certificate errors plus forceClick fix was one of the functions that we needed to fix so that we could proceed further
This pull request resolves both the issues. Note the description of playwright configuration has to be updated to include ignoreHTTPSErrors 
None applicable
- [-] Playwright
- [-] :nail_care: Polish code
- [-] Local tests are passed (Run `npm test`) Yes they passed only for file system it failed but the contents seemed similar

Adding code to fix force click and ignore HTTPS errors in playwright

---

lib/scenario.js
test/unit/bdd_test.js

This PR will fix next behavior:
1. Add to codeceptjs.config.js some Include with incorrect name of unexisting file like that:
```
include: {
someObject: 'unexisted-file.js',
},
```
2. Use this object in Scenario **without any Data()** methods (this is important):
```
Scenario('my scenario', async ({ I, someObject }) => {
await someObject.method()
})
```
3. Got an error - this is OK
4. Got an **exit code 0** - this is the problem.
Also, if test looks like this:
```
Scenario('my scenario', ({ I, someObject }) => {
someObject.method()
})
```
We got **exit code 1**, what is ok.
The problem is in **getInjectedArguments**, which error doesn't throw into `recorder.catch` and `recorder.throw`.

Fixed error handling in Scenario.js

---

typings/index.d.ts

According documentation (https://codecept.io/pageobjects/#dependency-injection) actor can be extended with function that can have any arguments. But the present type definition (`() => void`) allows only functions without arguments.
This bug fix changes type definition in order to allow the use of functions with any number of any arguments.

fix: Fix actor type

---

lib/container.js

This will allow using code `codeceptjs.container.plugins('allure')` in `.ts` files without cast to `unknown`
- None
- None

Set return type of `plugins` and `helpers` to any

---

docs/helpers/Puppeteer.md
lib/helper/Puppeteer.js

The predicate method accepts the `response` object and not `request`
Simple doc update. I believe it is a simple copy&paste mistake.

doc: Fix Pupeteer documentation for waitFroResponse

---

lib/command/definitions.js

- Not sure if it is the proper fix for this issue `fix TS2339: Property 'current' does not exist on type 'SupportObject'.` but at least this worked, no more complain.

(fix): complain on TS2339: Property 'current' does not exist on type 'SupportObject'

---

lib/helper/Playwright.js

In our team we use remote execution e2e tests with Moon and Playwright. When I setup config from documentation: https://codecept.io/helpers/Playwright/#configuration I got error with connection. Playwright not connect to remote browser.
I went inside `lib/helper/Playwright.js` and viewd Playwright documentation on link https://playwright.dev/ I was found that Playwright use other option for connect to remote browser: `wsEndpoint`.
https://github.com/codeceptjs/CodeceptJS/blob/a72aa750003734f926cd55c14bd6dfeeea6ea104/lib/helper/Playwright.js#L549
After fix it I got next error with disconnect from remote browser:
https://github.com/codeceptjs/CodeceptJS/blob/a72aa750003734f926cd55c14bd6dfeeea6ea104/lib/helper/Playwright.js#L584
In Playwright doc for all of versions I culdn't find this …

(fix): Incorrect work with Playwright helper

---

lib/workers.js
test/runner/run_workers_test.js

- The suites flag for workers is not working, wrote runner test to prove it

fix --suites flag for run workers

---

lib/mochaFactory.js

- Tests in codeceptjs must be unique, in codeceptjs3 run workers completely falls over if they are not.
Output example:
I wanted to throw an error but this would be a breaking change

feat: detect duplicate test names

---

package.json

Upgrade dependency to remove unnecessary webdriverio@5 istalling.
see `@codeceptjs/configure` PR https://github.com/codeceptjs/configure/pull/12
not sure, should be PR to `master` done, or `3.x` only

update @codeceptjs/configure dependency

---

lib/listener/helpers.js
lib/recorder.js
test/rest/REST_test.js
test/unit/plugin/retryFailedStep_test.js
test/unit/recorder_test.js

- during debugging I recognised retries on hooks

improve recorder a little: don't retry hooks

---

lib/actor.js
lib/recorder.js
test/unit/actor_test.js
test/unit/plugin/retryFailedStep_test.js

- the retries order was turned around each time a promise was recorded
- this was a problem because `retryOpts` are extracted from the last element in the array
- have a look at the code and attach a debugger, while running a test with special `retriy()`-options

♨️ Hot fix (recorder): don't mess retries order any more

---

test/unit/actor_test.js
test/unit/assert/empty_test.js
test/unit/assert/equal_test.js
test/unit/assert/include_test.js
test/unit/assert_test.js
test/unit/bdd_test.js
test/unit/container_test.js
test/unit/data/dataTableArgument_test.js
test/unit/data/table_test.js
test/unit/data/ui_test.js
test/unit/helper/FileSystem_test.js
test/unit/helper/element_not_found_test.js
test/unit/locator_test.js
test/unit/output_test.js
test/unit/parser_test.js
test/unit/plugin/customLocator_test.js
test/unit/plugin/retryFailedStep_test.js
test/unit/plugin/screenshotOnFail_test.js
test/unit/plugin/tryTo_test.js
test/unit/recorder_test.js
test/unit/scenario_test.js
test/unit/steps_test.js
test/unit/ui_test.js
test/unit/utils_test.js

- Move all unit tests to 'expect' assert library
- Resolves #2451

move all unit tests to expect chai lib

---

docs/locators.md
lib/helper/WebDriver.js
lib/locator.js
test/unit/locator_test.js

- We need to use scrollTo method for scrolling on shadow elements - it didnt work correctly for this case.
- We also use resemble helper for visual testing, which uses webdriver methods and here was also problem with shadow selectors. This PR resolves both.
- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2585 
- [ok] Tests have been added
- [ok] Documentation has been added (Run `npm run docs`)
- [ok] Lint checking (Run `npm run lint`)
- [ok] Local tests are passed (Run `npm test`)

fix(shadow): Fix shadow support in locator.js

---

lib/helper/Playwright.js

We have a test that opens a link in a new tab, switches to that tab and tries to click a button. Some example code:
```javascript
I.click(locate('.some-button'));
I.switchToNextTab();
I.waitForElement('Get Started');
I.retry(5).forceClick('Get Started');
```
and we get this error intermittently (maybe 50% of our runs):
```
Cannot read property '$$' of null
at Playwright.findElements (node_modules/codeceptjs/lib/helper/Playwright.js:2152:18)
at Playwright.findClickable (node_modules/codeceptjs/lib/helper/Playwright.js:2186:47)
at Playwright.proceedClick (node_modules/codeceptjs/lib/helper/Playwright.js:2162:35)
```
After some spelunking, we discovered that sometimes `this.context` gets set to `null`. No clue how that's happening as `_setPage` is meant to set the context and gets called …

fix(Playwright): handle null context in proceedClick

---

lib/command/definitions.js

- This PR aims to resolve the issue that there is no autocomplete for custom helper.

fix(autocomplete): no autocomplete for custom helper

---

lib/workers.js

- When a test fails, ex: an assertion, running in parallel, the error is never visible

Emit test.after on workers

---

lib/data/context.js
test/data/sandbox/codecept.skip_ddt.json
test/data/sandbox/ddt_test.skip_ddt.js
test/runner/interface_test.js

- Quality of life fix that instead of having one skipped test for data driven scenarios when using xData you get a skipped test for each entry in the data table.
Old behavior:
New behavior, as proved in runner test:

feat: Ensure skipped data driven tests have a skip entry per data entry

---

lib/config.js

current implementation does not allow using of `.ts` files as an config files.

allow .ts config files

---

docs/helpers/Appium.md
docs/helpers/Playwright.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/WebDriver.md
lib/command/definitions.js
runok.js

- fixed runok definitions generation due to wrong processing of optional `LocatorOrString?` use. See [runok.js#R159](https://github.com/codeceptjs/CodeceptJS/compare/3.x...elukoyanov:fix-defenitions-generation?expand=1#diff-bb428a0aedf8f49004edf14c2c9e9de29cb6c342ac68189101d8ac247ba31c76R159)
- fixed lint errors in `definitions.js` - strange, how can such errors pass commit hooks and PR checks
- rewrite some of `definitions.js` file to be more readable
- fixed typo in `defintions.js` :
```
hasCustomStepsFile && hasCustomStepsFile ?
```

Fix defenitions generation error

---

CHANGELOG.md
docs/changelog.md
lib/plugin/commentStep.js

When the method __ is called, an endless loop occurs because the added step is recursively appended to the end of the chain.
The added condition fixes method loop.
Add reporting support for run-workers command. 
Can be used to get junit reports.
Example command:
npx codeceptjs run-workers 2 --reporter mocha-junit-reporter
- Fixes [1938](https://github.com/codeceptjs/CodeceptJS/issues/1938)

 Fix method loop and adding report support for run-workers command

---

lib/helper/Playwright.js

Related to this fix
https://github.com/codeceptjs/CodeceptJS/pull/2667
Occasionally, we also see this error:
```
Cannot read property '$$' of null
at findElements (node_modules/codeceptjs/lib/helper/Playwright.js:2151:18)
at Playwright._locate (node_modules/codeceptjs/lib/helper/Playwright.js:840:12)
at async Playwright._withinBegin (node_modules/codeceptjs/lib/helper/Playwright.js:611:17)
```
Seems like we should be using `this._getContext()` here as well. Still not quite sure how `this.context` is `null` in these cases.

fix(playwright): use _getContext for _locate

---

lib/workers.js

- When a test fails, ex: on a `BeforeSuite`, running in parallel, there is no way to map to a specific test

Emit hook.failed in workers

---

lib/listener/helpers.js

In case of error in _after function, for example, browser is closed during test, tests executions is stopped, but error is not logged.
It lead to tests are failed, but exit code is returned 0.
example:
```
sspjs % yarn test:e2e && echo 'ok'
yarn run v1.21.1
$ codeceptjs run -c ./specs/e2e/codecept.conf.js --reporter mochawesome
Banner initialization methods
✓ 'test name' (800ms)
(node:71219) UnhandledPromiseRejectionWarning: no such window: no such window: window was already closed
(Session info: chrome=87.0.4280.88)
at Object.getErrorFromResponseBody (<there is path>/node_modules/webdriver/build/utils.js:94:12)
at WebDriverRequest._request (<there is path>/node_modules/webdriver/build/request.js:133:31)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
at …
```

fix: catch error in after test

---

lib/helper/Puppeteer.js

I've just updated to angular 11 in my project, and had the waitForValue function start failing for input values which are of type Number. The query selector was returning the Number value, which didn't have the indexOf function so was throwing errors. 

Fixed error with waitForFunction not working with number values

---

lib/plugin/retryFailedStep.js
test/unit/plugin/retryFailedStep_test.js

This contribution avoids an exception in `retryFailedStep` caused by regular expressions in `ignoredSteps`
```js
{
retryFailedStep: {
enabled: true,
defaultIgnoredSteps: [/haveMail/],
}
}
```
```
TypeError: ignored.indexOf is not a function
at EventEmitter.event.dispatcher.on (/appsuite-ui/ui/node_modules/codeceptjs/lib/plugin/retryFailedStep.js:105:19)
at EventEmitter.emit (events.js:203:15)
at EventEmitter.emit (domain.js:448:20)
at Object.emit (/appsuite-ui/ui/node_modules/codeceptjs/lib/event.js:117:28)
at recorder.add (/appsuite-ui/ui/node_modules/codeceptjs/lib/actor.js:89:13)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

fix(retryFailedStep): regexp based ignored steps

---

lib/plugin/autoDelay.js

Description of this PR, which problem it solves
In the changes to remove the REST helper from list supoortedHelpers, we added this bug :'(
In the autoDelay.js file, the supoortedHelpers variable is declared by reference.
If a variable by reference is changed, all other plug-ins will have their values ​​changed as well, so by adding REST helper to the autoDelay.js file, the plugin, stepByStepReport.js will have 'REST' as well.
In this PR we changed the declaration of the variable to be by value, so we changed the list only in this plugin.
The fail "helper.saveScreenshot is not a function" occur when we use simultaneous:
helpers [REST, WebDriver]
plugins [autoDelay, stepByStepReport]
Original message fail: <Can't save step screenshot: TypeError: helper.saveScreenshot is not a function> …

Fix: Fail "helper.saveScreenshot is not a function" on stepByStepReport plugin

---

lib/interfaces/gherkin.js

I wanted to enhance bddStep reporting a bit more as a follow up to PR #2343 
Just as @wojtkowiak reported initially when there are no helper methods fired in a bdd step, it is hard to extract relevant information. Emitting an event was a good step forward. However, I have add some more properties - status, start/end time, error,  and step match location for enhanced reporting when the event is fired.

feat: add status, start/end time, and matchline for bddStep event

---

lib/command/run.js
test/data/sandbox/codecept.multiple.initFailure.json
test/data/sandbox/support/failureHelper.js
test/runner/run_multiple_test.js

When running run-multiple and there's an error during initialization (such as an exception when loading helpers for example), codeceptjs would return a 0 exit code, because the error becomes an unhandled promise rejection.
With this change, the error is handled by run.js, and the process returns a non 0 exit code.

fix: catch init failures during run

---

lib/helper/Playwright.js

- The main problem was in Firefox and the `JSON.stringify` method since the `grabCssPropertyFromAll` method uses `JSON.parse` and `JSON.stringify` to deep clone the object and returns serialized data. Unfortunately, this approach doesn't work in Firefox and loses all significant data. Moreover, I've optimized and improved the method by removing the deep clone step and updating the get property step by the `getPropertyValue` method to avoid converting CSS property into a camel case.
- Tested in Chromium, WebKit, and Firefox
test case:
```js
Scenario('should get background color @debug', async ({ I }) => {
I.amOnPage("https://github.com/")
const bgColor = await I.grabCssPropertyFrom("button.btn-mktg-fluid", "background-color")
I.say(bgColor)
});
```
- Resolves #2422 …

fix(playwright): #2422 - fix grabCssPropertyFromAll method

---

docs/helpers/Appium.md
docs/helpers/Nightmare.md
docs/helpers/Playwright.md
docs/helpers/Protractor.md
docs/helpers/Puppeteer.md
docs/helpers/TestCafe.md
docs/helpers/WebDriver.md
docs/webapi/fillField.mustache
runok.js
typings/index.d.ts

- Currently, the `fillField` method takes a value as a `string` only, but it could be a `secret` too. So, I've fixed that to make it work with both of them.
- Resolves #2767

fix(typings): value of the fillField method for all helpers

---

lib/plugin/allure.js

When working with the allure plugin and multiple sessions, codeceptjs will throw an error. The name of the actor will be highlighted using [ANSI color codes](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) that represent invalid characters for the allure XML report.
The following test will fail
```typescript
Feature('sample-test')
Scenario('test something', ({ I }) => {
I.amOnPage('https://github.com')
session('Second Actor', () => {
I.amOnPage('https://github.com')
})
})
```
with this error:
```console
Error processing suite.after event:
Error: charData should not contain characters not allowed in XML
```
There already was some logic in place to replace the ANSI code for the color cyan, not however, for the other possible colors.

fix: allure report for multi sessions

---

docs/helpers/REST.md
lib/helper/REST.js

- Sometimes the payload of API tests for POST/PUT contain sensitive info and you don’t want those info are showing in console logs when running tests with `--verbose`. So taking the advantage of Secret class, now we can mask the payload and you're feeling good to see no sensitive info are showing in console logs.
```
...
I send post request "customers/login", *****, {"x-component":"google"}
› [Request] {"baseURL":"https://thisisatest/customers/login","method":"POST","data":"*****","headers":{"x-component":"google"}}
...
```

feat: mask the payload with sensitive info in console logs

---

lib/command/interactive.js

- It looks like `runBootstrap` was updated to a promise-based `bootstrap` in #2385 
- see https://github.com/codeceptjs/CodeceptJS/commit/03c5c910272b8a2cd2aefe29d279c35511c97856#diff-0d969c34cdd37d1e94a88372a2bf51abb40fb512da7a4d92ae118b2ca6bd6bfeL112-R108
- This fix updates the old code to use the new `bootstrap` promise.
- Resolves #2711

Fix interactive shell bug

---

test/rest/ApiDataFactory_test.js

- I noticed this test failed intermittently.
```
28 passing (1m)
1 failing
1) ApiDataFactory
create and cleanup records
should cleanup created data:
AssertionError: expected 'Yorik' to deeply equal 'Tapac'
+ expected - actual
-Yorik
+Tapac
at Context.<anonymous> (test/rest/ApiDataFactory_test.js:117:31)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

fix: apiDataFactory_test failed intermittently

---

lib/config.js

- I've added the ability to run the `codecept.conf.ts` config file with the command `npx codeceptjs run`
Output after running the `npx codeceptjs run` command with the `codecept.conf.ts` config file:
```bash
Error: Can not load config from /Users/Ivan/Desktop/codecept.conf.js or  /Users/Ivan/Desktop/codecept.json
CodeceptJS is not initialized in this dir. Execute 'codeceptjs init' to start
```
Output after running the `npx codeceptjs run` command with the `codecept.conf.ts` config file:
```bash
CodeceptJS v3.0.4
Using test root "/Users/Ivan/Desktop"
Call functionality --
...
```

feature(config): add ability to run ts config file

---

docs/reports.md
lib/plugin/screenshotOnFail.js

This PR will fix the issue in #1502 regarding double setting of the `attachments` setting (described in https://github.com/codeceptjs/CodeceptJS/issues/1502#issuecomment-494112578)
The current implementation checks for the `attachments` option in the
wrong location, which requires the user to set `attachments:true` in two
places, the current location and within the `options` object.
This changes the check and docs to only use the `options` object which is
what `mocha-junit-report` is actually looking for.
Does not directly effect helpers

Fix attachments usage for `mocha-junit-reporter`

---

docs/pageobjects.md

- Small error visible in the generated documentation.
- Resolves #2782 

doc: unclosed code block in page objects markdown file

---

lib/interfaces/gherkin.js
test/unit/bdd_test.js

- Accidently broke gherkin when trying to catch error in https://github.com/codeceptjs/CodeceptJS/pull/2678. Meant to throw error after evaluating it. Currently if gherkin step encounters an error, it will return and other steps within the gherkin step wont run.

Fix error suppression for failed gherkin step

---

Dockerfile

- Resolves issue #2654 regarding ourdated Dockerfile on https://hub.docker.com/r/codeception/codeceptjs
- Note: Current image is based on playwright's original image https://hub.docker.com/_/microsoft-playwright. Since Microsoft does not set tags on their Playwright images, it will be always based on the latest `playwright:bionic` image. Also worth mentioning that chrome is now installed inside base playwright image, so i removed additional installation of chrome dev package.

Update Dockerfile to support CodeceptJS 3.x.

---

docs/typescript.md
typings/index.d.ts

#2797 +CustomLocators interface

---

lib/workers.js

This PR adds more events to be propagated to who ever uses the custom script for parallel execution

feat: propagate more events for custom parallel script

---

lib/helper/Playwright.js

- This PR fixes a bug with websocket connection for playwright tests, currently with the latest version of CodeceptJS, the websocket being passed doesn't allow to connect to the end point because it is passing a wrong value to connect. 
https://playwright.dev/docs/api/class-browsertype#browsertypeconnectparams 

Add the property for config and update instruction

---

docs/parallel.md
lib/helper/Playwright.js
lib/workers.js
test/data/sandbox/codecept.non-test-events-worker.js
test/data/sandbox/non-test-events-worker/non_test_event.worker.js
test/unit/worker_test.js

This PR will allow to propagate non test cycle events to the custom worker parallelisation script.
Example:
```js
// parallelisation script
workers.on('message', (data) => {
console.log(data)
});
```
This will allow any `js` file that wants to communicate with the main thread can use the `parentPort.postMessage();` to send custom data.

feat: propagate non test cycle events to main thread

---

docs/helpers/Playwright.md
lib/config.js

- Make the params optional for config get function. -> https://codecept.io/hooks/#config
`let config = require('codeceptjs').config.get();`

style: optional params for config get function

---

docs/bdd.md
lib/codecept.js

- This Pr is designed to allow people to add different paths for their feature files. This way there can be better organization for frontend vs api features or old vs new, etc etc. This is for gherkin.
- [x ] WebDriver
- [x ] Nightmare
- [] TestCafe

Add ability to use an array of feature files

---

lib/recorder.js

- As a QA, I want to get the queue id from the recorder so I can run the second retry in a different environment and/or with mocked data.

Get the queue id from recorder

---

docs/helpers/MockRequest.md

- Quick fix in the documentation. :clipboard: Renamed MockRequestHelper to MockRequest because the documentation had referred to 2 different names.

Renamed MockRequestHelper to MockRequest in the documentation

---

.circleci/config.yml
.gitignore
docs/plugins.md
lib/interfaces/gherkin.js
lib/plugin/fakerTransform.js
lib/transform.js
package.json
test/acceptance/session_test.js
test/bdd/codecept.faker.js
test/bdd/defs/faker.js
test/bdd/features/faker.feature
test/docker-compose.yml

- I added a plugin called fakerTransform. This plugin adds a callback on transform function that will turning the faker API using a mustache string format inside example of the gherkin scenario outline before running the test steps
- :rocket: New functionality
- [ x ] Tests have been added
- [ x ] Documentation has been added (Run `npm run docs`)
- [ x ] Lint checking (Run `npm run lint`)
- [ x ] Local tests are passed (Run `npm test`)

feat: adding faker.js support to gherkin

---

lib/helper/REST.js

- Use class instance of axios, not the global instance, to avoid contaminating global configuration.
- Fixes #2652 
I'm not sure I can think of any new tests for this, the REST helper seems quite well tested already....

Use class instance of axios in REST helper

---

lib/helper/Appium.js

…sting an app
-  This PR fixes the problem if some one has to connect to sauce labs via the tunnel to test the app (Android & IOS)
- [*] Appium
- [*] :rocket: New functionality

Adding the code to connect to sauce labs using a sauce tunnel when testing an app

---

lib/helper/GraphQL.js

This uses a helper-specific instance of Axios instead of the global instance, to keep from changing global defaults.

GraphQL Helper - use helper-specific instance of axios instead of global

---

lib/output.js
test/unit/output_test.js

fix: Second argument of I.say throw misleading error with invalid system color

---

lib/helper/Playwright.js
test/data/app/controllers.php
test/data/app/index.php
test/data/app/view/invisible_elements.php
test/helper/Playwright_test.js

- When calling `I.click('Hello World')` and `Hello World` matches multiple elements in the DOM, the Playwright helper will call `click()` on the ElementHandle of the first element.
- When calling `click()` on an ElementHandle that is not visible, Playwright will wait until the element becomes visible.
- When the element does not become visible in a certain time, Playwright times out and the test will fail.
- This can be problematic if there is an invisible element in the DOM above the element that I'm trying to select and both share the same selector. Eventually this will result in:
```sh
elementHandle.click: Timeout 30000ms exceeded.
=========================== logs ===========================
attempting click action
waiting for element to be visible, enabled and stable
element is not …
```

fix: dont call click on invisible elements

---

docs/playwright.md

- This PR fixes some broken links that point to the Microsoft Playwright docs.

Fixed broken links in playwright.md

---

package.json
runok.js

- Introduce the versioning automatically, it follows the semantics versioning. If no arg is passed, it's a patch version, otherwise we could pass `major`, `minor`, `patch`.
```
thanh@Thanhs-MacBook-Pro CodeceptJS % ./runok.js versioning
Version updated 3.0.8 => 3.0.9
Creating and switching to release branch...
[#1 EXEC] › ℹ  git checkout -b release-3.0.9
M       package.json
M       runok.js
[#1 EXEC] › ✔  Finished  in 38 ms
```

feat: versioning automatically

---

docs/reports.md

Add missing closing brace and fix indentation.
The example for configuring mocha-multi can't be directly copied because it's missing a closing brace.
- [not needed] Tests have been added
- At least, the failures were the same as on the main branch

Fix mocha-multi config example

---

lib/helper/Playwright.js
test/acceptance/codecept.Playwright.js

- `grabTextFrom` is broken on some elements since it does not call the Playwright's default method but reads the `innerHTML`
- **grabTextFrom** should call the `page.textContent` method of Playwright

Fix: Playwright grabTextFrom()

---

lib/plugin/screenshotOnFail.js

This PR is the partner to a [PR](https://github.com/ktryniszewski-mdsol/codeceptjs-cucumber-json-reporter/pull/2) in `codecept-cucumber-json-reporter` which will enable embedding of screenshots in Cucumber JSON when it has been specified as a plugin

Adding support for attaching screenshots to cucumberJsonReporter

---

docs/plugins.md

- Fix autoLogin example: autoLogin > Usage
- Fix broken markdown code block in commentStep part
In the commentStep part of the plugin, I found that the last code block was broken.

[Fix] Plugin documentaion

---

Dockerfile

- Resolves: CircleCI build was failing after update of npm to version 7 in base image which by default fails on unresolved peer dependencies.

Fix failing build by adding compatibility flag required after switch to npm version 7

---

.travis.yml

Travis CI setup instructions are in the comments for https://github.com/nikocanvacom/CodeceptJS/pull/3
PR adds following TravisCI build environment variables: 
- DOCKER_PASSWORD
- DOCKER_USERNAME
**They would NEED TO BE SETUP in CodeceptJS TravisCI build configuration.**

Fix TravisCI failure on docker pull limit, fixes #2932

---

lib/helper/extras/Popup.js

Fixing popup property initialisation not to use truthy value which was incorrectly indicating presence of popup alert on each page by default
- `{}` was used as empty value for initialisation of internal popup object but it wasn't correct as the places where that property was used were clearly expecting default not to be truthy:  
```
Popup.js
constructor(popup, defaultAction) {
this._popup = popup || {};
this._actionType = '';
this._defaultAction = defaultAction || '';
}
set popup(popup) {
if (this._popup) {
console.error('Popup already exists and was not closed. Popups must always be closed by calling either I.acceptPopup() or I.cancelPopup()');
}
this._popup = popup;
}
clear() {
this._popup = null;
this._actionType = '';
}
assertPopupVisible() {
if (!this._popup) {
throw new …
```

Popup initialisation should not use truthy value

---

lib/output.js

- xpath selectors and other test data output on verbose level might be longer than 200 characters. As a test automation developer I want to see full strings in verbose log so I could use them while debugging or investigating the issues.  

Do not truncate log output on verbose level

---

docs/helpers/REST.md
lib/helper/REST.js

The return type of the rest helpers was void which is incorrect. They actually return the Axios response object
- Resolves #2590
I can't install detox locally for some reason which makes testing, linting... locally hard. I did notice though that the JSDoc I've written is assumably not correct but I have no clue why... If somebody could help me that would be greatly appreciated!

Add return type for REST helpers

---

lib/helper/Puppeteer.js
package.json

This PR will fix the issues when using `scrollTo()`, `moveCursorTo()`, `dragSlider()`, or `proceedDragAndDrop()` function. This function will causes test fail, because of defined problem in issue #2244 . 
The problem is occured on latest version of puppeteer (10.0.0+). Due to some of method changes, especially on `_clickablePoint()`. Which this function is public right now (changed to `clickablePoint()` ) . This is the link of documentation: [ElementHandle.clickablePoint](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#elementhandleclickablepoint).
Glad to see if this PR is merged. Thanks! 
- Resolves #2244 

Fix issue #2244 _clickablePoint() is not a function

---

lib/helper/Playwright.js
test/data/app/view/form/field.php
test/data/app/view/info.php
test/helper/webapi.js

Playwright (dont)SeeVisible/grabNumberOfVisibleElements do not filter out elements with visibility:hidden css #2928
- playwright helper and tests were updated to use isVisible playwright method and test visibility related functions on elements with visibility:hidden style
- Playwright helper uses incomplete visibility test, elements with visibility:hidden style considered visible
- Resolves #2928.
it's not happy with `work/CodeceptJS/lib/mochaFactory.js` which wasn't modified by me :(

Playwright helper grab and see functions should respect visibility:hidden css #2928

---

.github/CONTRIBUTING.md
docs/react.md
lib/helper/Playwright.js
lib/helper/Puppeteer.js
lib/helper/extras/React.js
test/acceptance/react_test.js

- Add react locator support to Playwright. Help keeps the API more uniform.
- Resolves #2696
- Also added Playwright to the Contribution doc.
- [ X] Playwright
- [X ] :rocket: New functionality
- [X ] Tests have been added
- [X ] Documentation has been added (Run `npm run docs`)
- [X ] Lint checking (Run `npm run lint`)
- [ X] Local tests are passed (Run `npm test`)

Add React Locator Support to Playwright

---

lib/interfaces/gherkin.js

This PR fixes issue where  cucumberJsonReporter plugin fails to generate report when `Scenario Outline` uses fakerTransform plugin .
The root cause is that `fakerTransform` transform function updates all the steps and suite object but the underlying gherkin feature still has `Examples` with the faker mustache strings. 
Replacing those cells with faker transformed value resolves the issue.

Fixed issue where cucumberJsonReporter not working with fakerTransform plugin 

---

lib/plugin/allure.js

- All actions put in Before/All and After/All will be logged in Allure reports
- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2689

Content of Before/After/All hooks will be logged in Allure report now

---

lib/command/definitions.js
lib/plugin/allure.js

Fixes broken paths in the typings file, if it located in sub-folders of a project, generated by the command
```bash
npx codeceptjs def -o folder/sub-folder
```
on Windows
- Resolves #2937

Issue 2937 fix

---

lib/command/run-multiple/collection.js

When using `run-multiple` with a custom defined path to the features files, if you enable chunks, custom path is ignored.
This happens because when calling `createChunks` at `prepareChunks`, it only tests the paths against previously added to the pattern array, see [collection.js:87](https://github.com/codeceptjs/CodeceptJS/blob/9c3aeb894d843c93a385f89fb74a012be1e5f050/lib/command/run-multiple/collection.js#L87) and [chunk.js:65](https://github.com/codeceptjs/CodeceptJS/blob/9c3aeb894d843c93a385f89fb74a012be1e5f050/lib/command/run-multiple/chunk.js#L65).  As a next step it removes the run configuration and only the configuration created by the chunks remains.
When `chunks` property is omitted it works because it doesn't remove the run config, see …

Fix missing run-multiple gherkin features when using chunks

---

lib/helper/Playwright.js

- Playwright Alert popup handling code register multiple event listeners when multiple scenarios executed in one browser which causes error situation and error logging to console when an alert appear on the page.
- Resolves #2945.

Reset of playwright dialog event listener before registration of new one

---

bin/codecept.js
test/data/sandbox/codecept.async.bootstrapall.multiple.code.js
test/data/sandbox/configs/codecept-invalid.config.js
test/runner/codecept_test.js
test/runner/run_multiple_test.js
test/runner/run_workers_test.js

If we have error in `codecept.config.js`, command `codeceptjs run-workers` will print `exit code 0`, so it will be false-positive. Meanwhile, there is no same bug in command `codeceptjs run`.
Problem appeared in **3.x**, in CodeceptJS **2.x** version all worked correctly.
All .bin-commands now wrapped into errorHandler to avoid UnhandledPromiseRejection, also added tests for `run`, `run-multiple`, `run-workers`.

Fixed bug when run-workers prints exit code 0 cause of bad CodeceptJS config file

---

lib/helper/Puppeteer.js
test/helper/webapi.js

Hidden inputs are considered by fillField, but only visible and focusable inputs and text areas should get filled. I assumed that this also is valid for appendField, selectOption and proceedSeeInField.
- Add function 'findVisibleFields' to get only visible fields
- Replace function 'findFields' through 'findVisibleFields' for the following actions: 'fillField', 'appendField', 'selectOption' and 'proceedSeeInField'
(no changes by my commit)

Fix: Hidden inputs are considered by fillField

---

lib/container.js

I had an error in my project and I was not able to solve because the error message did not tell me enough so I added the stack trace to error message to identify the error origin
Could not include object Step Definition from /home/runner/work/*/*.def.js from module '/home/runner/work/*/*.js'
Unexpected token '.'
Error: 
at loadSupportObject (/home/runner/work/*/node_modules/codeceptjs/lib/container.js:383:11)
at loadGherkinSteps (/home/runner/work/*/node_modules/codeceptjs/lib/container.js:315:7)
at Function.create (/home/runner/work/*/node_modules/codeceptjs/lib/container.js:47:25)
at Codecept.init (/home/runner/work/*/node_modules/codeceptjs/lib/codecept.js:56:15)
at Command.module.exports (/home/runner/work/*/node_modules/codeceptjs/lib/command/run.js:24:14)
at Command.listener …

Adding more details in the error message

---

lib/helper/Playwright.js
lib/plugin/allure.js

- When error happens in Before with Playwright, video and trace will be assigned to `test.artifacts`
- Resolves #3032

Fix/define artifacts before/issue 3032

---

lib/helper/Playwright.js

- Make sure Playwright browser context set on creation when possible
- Resolves #3035

Add http credentials to browserContext options

---

docs/bdd.md
docs/helpers/Appium.md
docs/helpers/Puppeteer.md
docs/plugins.md
lib/codecept.js
lib/data/dataTableArgument.js
lib/index.js
lib/plugin/coverage.js
test/unit/data/dataTableArgument_test.js
typings/index.d.ts
typings/jsdoc.conf.js

Lack of typing `DataTableArgument`, it is difficult to work with this class using TS.
Some methods for working with the cucumber-like table are not implemented.
Typing an existing `DataTableArgument` class. Extending it's API.
Added:  `rowsHash()` and `transpose()` methods. 
Added unit tests for new methods.
The `BDD` doc has been expanded and examples of `DataTableArgument` usage.
[#2081](https://github.com/codeceptjs/CodeceptJS/issues/2081)

FEATURE: add new public api, tests and docs. Typed dataTableArgument

---

lib/helper/WebDriver.js

- Update webdriverio default version to 6.12.1. As it is pointing to a deprecated version, that makes the setup not working.

Update webdriverio default version

---

lib/interfaces/gherkin.js
lib/mochaFactory.js

When a Feature file is empty, instead of showing an error that the Feature file is empty, the below error is displayed.
This is irrelevant to the actual problem and as a result users will not understand what the problem is, thereby costing a lot of time for resolution.
TypeError: Cannot read property 'name' of undefined
at module.exports (/Users/node_modules/codeceptjs/lib/interfaces/gherkin.js:18:39)
at /Users/node_modules/codeceptjs/lib/mochaFactory.js:38:32
at Array.map ()
at Mocha.mocha.loadFiles (/Users/node_modules/codeceptjs/lib/mochaFactory.js:36:21)
at Mocha.run (/Users/node_modules/codeceptjs/node_modules/mocha/lib/mocha.js:966:10)
at /Users/node_modules/codeceptjs/lib/codecept.js:188:15
at new Promise ()
at Codecept.run (/Users/node_modules/codeceptjs/lib/codecept.js:171:12)
at …

Fixed unhandled empty feature files

---

lib/config.js

I am attempting to set my project to be a esm module by using the package.json property "type" with the value of "module".
Noticed codecept didn't support importing esm so I changed all of my acceptance testing files to be commonjs files denoted with the .cjs file extension. Need to add this extension to the list of checked extensions so the config file will be loaded.
On a side note is there any plan to support esm modules. Would have to swap to use dynamic imports or first try to use require then fallback to dynamic import if the error is "ERR_REQUIRE_ESM".  Mocha currently supports esm modules but have to use loadFiles Aync instead of loadFiles. I looked at your require code a bit and wasn't sure how to best handle having to deal with the fact dynamic imports return a promise.

improve(config): Support cjs file extensions for config file

---

lib/helper/Playwright.js
lib/plugin/allure.js

- Once custom headers are applied with I.haveRequestHeaders, they will be effective not only on the first tab, but on all ones opened from the first one
- Resolves #3048

Playwright I.haveRequestHeaders should affect all the tabs

---

docs/helpers/Appium.md
lib/actor.js
lib/helper/Appium.js
typings/tests/actor.types.ts
typings/tests/helpers/Appium.types.ts

- Resolves #3039
Lint check fails in my env, seems to be caused by #3046:
```
/home/mirao/workspace/CodeceptJS/lib/interfaces/gherkin.js
17:21  error  Requires a space after '{'   block-spacing
17:96  error  Requires a space before '}'  block-spacing
```

Fixed TS definitions of Appium methods touchPerform, hideDeviceKeyboard, removeApp

---

lib/interfaces/gherkin.js
lib/listener/helpers.js

When there are multiple helper files, there is no way to link feature files to the helper files and thus all hooks are executed. Which might be unnecessary in some cases.
This enhancement helps link a specific feature file to the helper file which ensures that the before/after hooks for tests and suites are executed only for that particular feature file.
Example:
The "feature" variable is the name of the feature file to which the helper is linked to.
If this variable is not set, the usual execution flow happens.
```
class MyHelper extends Helper {
feature = "feature_one.feature"
_after() {
}
_beforeStep(step) {
}
_beforeSuite(suite){
}
}
module.exports = MyHelper;
```

Enhancement to optionally link feature files to helper files

---

typings/index.d.ts

This PR adds type declarations for the `@codeceptjs/helper`. I know there is a separate repo for this package but IMO it is more straightforward to keep all the types here as the other package probably doesn't make sense standalone.
This reduces the amount of errors returned by `dtslib` but there are still a few remaining that I will annotate in the comments.
I am also debating if it isn't better to also change this to an `interface` so that it could be extended in custom types, but will not allow for using visibility modifiers on the fields.
If everything looks alright, I'll change the PR status to ready for review.

Add type declarations for @codeceptjs/helper package

---

lib/locator.js

This PR fixed wrong type definition of  `Locator.filters` and `Locator.addFilter`.
These caused TypeScript's error.
#2794

Add type declaration to jsdoc of `Locator`.

---

lib/helper/Puppeteer.js
test/helper/Puppeteer_test.js

Remote browser or not, we should always close the browser. 
Closing the browser will actually tell the remote browser provider that the session is to be ended (logs to be consolidated and session terminated), whereas only disconnecting might keep the session hanging for no reason.
When executing Codeceptjs/Puppeteer test suite using the browserstack grid, the session hang for 15min after the test suite finished executing and logs are not properly uploaded to the plateform. 
I don't have an issue ID as I identified the bug at the same time, I fixed it.
No test added as it would require credentials for a remote browsers provider. 
`npm test` -> 2 tests fail but they …

We should always close the browser

---

docs/helpers/Playwright.md
lib/helper/Playwright.js
lib/plugin/screenshotOnFail.js

- We have to test our application with differentes locales (french and english). Playwright provides an attribute 'locale' to change browser user locale. I added the mapping between CodeceptJS configuration and Playwright to correctly defined this property.

playwright configuration - added locale

---

docs/helpers/Puppeteer.md
lib/helper/Protractor.js
lib/helper/Puppeteer.js

- fix `seeTitleEquals` Puppeteer and Protactor typings
- [] Local tests are passed (Run `npm test`)

fix(typings): fix seeTitleEquals Puppeteer and Protactor typings

---

lib/listener/timeout.js

- In CodeceptJS 3.2.1 release step timeout is always reset to NaN so does not apply on steps when no test timeout set.

Step timeout not working due to override by NaN by test timeout

---

.github/workflows/appium.yml
.github/workflows/dtslint.yml
.github/workflows/playwright.yml
.github/workflows/puppeteer.yml
.github/workflows/test.yml
.github/workflows/testcafe.yml
.github/workflows/webdriver.yml

- Build is going to be a bit faster when `npm install` skips downloading of browsers for framework not tested in pipeline

Github actions could skip playwright browser download where browser not used

---

docs/plugins.md
lib/actor.js
lib/listener/timeout.js
lib/plugin/stepTimeout.js
lib/step.js

- Step timeout is set form multiple sources and need to be selected using following logic:
- between step timeout set on action from code with `I.limitTime` and timeout set with configuration of stepTimeout plugin one from the code has priority unless stepTimeout.config.force===true
- test/suite timeout counter update stepTimeout if it is smaller than stepTimeout set from other sources. 

Timeout operation priority according to the source

---

lib/helper/WebDriver.js

- Fixes error happening on startup of Appium tests when manualStart is true
- Resolves #3140 

#3140 [BUG] Appium helper logs type error when manualStart is true

---

lib/cli.js

- Programmatic invocation of CodeceptJS allows multiple reruns of the tests from one node process with the logging registering on each test run and producing duplication of the log entries in console output being only problem so far. The change in CodeceptJS cli reporter insures logger is registered only once.

Guard mocha cli reporter from registering step logger multiple times

---

lib/command/workers/runTests.js

- Resolves #2889
Currently using patch-package with this fix on version 3.0.7 and been testing since then. With the complexity of the core api of codeceptjs, I could not find a way to replicate the error by sending an invalid object with **inspect** and **cliMessage** functions on it like shown in the reported issue. I would be glad to add some tests if someone could point me on how to build these tests to track the exact problem.

fix(#2889): return always the same error contract from simplifyTest

---

docs/helpers/Playwright.md
lib/helper/Playwright.js

While Playwright can download and use the recent Chromium build, it can operate against the stock Google Chrome and Microsoft Edge browsers available on the machine. In particular, current Playwright version will support Stable and Beta channels of these browsers.
https://playwright.dev/docs/browsers/#google-chrome--microsoft-edge

support channel for chromium playwright

---

package.json

https://snyk.io/blog/open-source-maintainer-pulls-the-plug-on-npm-packages-colors-and-faker-now-what

chore: pin `faker` to `5.5.3`

---

docs/helpers/Playwright.md
lib/helper/Playwright.js
test/helper/Playwright_test.js

I noticed that there was ambiguity in the method block comment and the generated readme for the `Playwright.usePlaywrightTo` method regarding the param naming.  In some places the BrowserContext object was called `browserContext` and in others it was only `context`. Since `browserContext` is the correct naming, I updated the comments to reflect that and hopefully save others some confusion in the future.  I also added a small unit test that checks the names and presence of all 3 params on that method callback.

fix: update playwright comments / docs for usePlaywrightTo method

---

lib/helper/ApiDataFactory.js

Handle Rosie feature for programmatic generation of attributes
https://github.com/rosiejs/rosie#programmatic-generation-of-attributes

Feature for handle options in Rosie

---

lib/helper/Playwright.js
lib/helper/Puppeteer.js
lib/utils.js
test/unit/utils_test.js

- Resolves #2663 .
Added a simple utility that allows the require fallback of npm packages. If the first is not found it will try the next one in the chain.
I have been using it to include playwright-core instead of playwright because I don't want to download the browser binaries on yarn/npm install. This approach can be used for other helpers as well if you guys think it's worth it.
For example, it would be possible as well for puppeteer without adding 
```
npm config set puppeteer_skip_chromium_download true
```
as explained in https://github.com/codeceptjs/CodeceptJS/issues/2076

feat(#2663): support for playwright-core usage

---

lib/interfaces/bdd.js
test/unit/bdd_test.js

- Fixed issue - Handle flags of Regex expression for cucumber step definition.
- Resolves #3212.
If you create a step definition like ``` Given(/^I am on "([^"]+)" page$/i, openPageStep); ``` and use ``` Given I am on "Login" page```, you will get error stating ````# No steps matching "I am on "Login" page"```` but It will work for ``` Given(/^I am on "([^"]+)" page$/, openPageStep); ```

Handle flags of Regex expression for cucumber

---

docs/plugins.md
lib/plugin/allure.js
runok.js

- Description of the missed allure plugin public API `createStep`
- Clarifying issue #2982

DOCS(#2982) allure createStep public API description
